/*
   Copyright (C) 2004 - 2018 Université de Versailles Saint-Quentin-en-Yvelines (UVSQ)

   This file is part of MAQAO.

  MAQAO is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public License
   as published by the Free Software Foundation; either version 3
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#ifndef ARM64_ARCHMACROS_H_
#define ARM64_ARCHMACROS_H_

/**\todo (2016-06-21) Create the macros here from the list below*/

/*
arm64_TMPL_OPRN_IMMEDIATE_DATASZ_12b_READ

arm64_TMPL_OPRN_IMMEDIATE_DATASZ_13b_READ

arm64_TMPL_OPRN_IMMEDIATE_DATASZ_16b_READ

arm64_TMPL_OPRN_IMMEDIATE_DATASZ_3b_READ

arm64_TMPL_OPRN_IMMEDIATE_DATASZ_4b_READ

arm64_TMPL_OPRN_IMMEDIATE_DATASZ_5b_READ

arm64_TMPL_OPRN_IMMEDIATE_DATASZ_6b_READ

arm64_TMPL_OPRN_IMMEDIATE_DATASZ_7b_READ

arm64_TMPL_OPRN_IMMEDIATE_SYSTEM_DATASZ_4b_READ

arm64_TMPL_OPRN_MEMORY_DATASZ_32b_READ

arm64_TMPL_OPRN_MEMORY_DATASZ_32b_WRITE

arm64_TMPL_OPRN_MEMORY_DWORD_REGISTER_INDEX_DATASZ_32b_READ

arm64_TMPL_OPRN_MEMORY_DWORD_REGISTER_INDEX_DATASZ_32b_WRITE

arm64_TMPL_OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_DATASZ_32b_READ

arm64_TMPL_OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_DATASZ_32b_WRITE

arm64_TMPL_OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_WRITEBACK_DATASZ_32b_READ

arm64_TMPL_OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_WRITEBACK_DATASZ_32b_WRITE

arm64_TMPL_OPRN_MEMORY_SIGNED_IMMEDIATE_POST_INDEX_DATASZ_32b_READ

arm64_TMPL_OPRN_MEMORY_SIGNED_IMMEDIATE_POST_INDEX_DATASZ_32b_WRITE

arm64_TMPL_OPRN_MEMORY_SWORD_REGISTER_INDEX_DATASZ_32b_READ

arm64_TMPL_OPRN_MEMORY_SWORD_REGISTER_INDEX_DATASZ_32b_WRITE

arm64_TMPL_OPRN_MEMORY_UNSIGNED_IMMEDIATE_INDEX_DATASZ_32b_READ

arm64_TMPL_OPRN_MEMORY_UNSIGNED_IMMEDIATE_INDEX_DATASZ_32b_WRITE

arm64_TMPL_OPRN_POINTER_DATASZ_14b_READ

arm64_TMPL_OPRN_POINTER_DATASZ_21b_READ

arm64_TMPL_OPRN_POINTER_DATASZ_28b_READ

arm64_TMPL_OPRN_REGISTER_DWORD_OR_STACK_DATASZ_DWORD_READ

arm64_TMPL_OPRN_REGISTER_DWORD_OR_STACK_DATASZ_DWORD_WRITE

arm64_TMPL_OPRN_REGISTER_DWORD_OR_ZERO_DATASZ_DWORD_READ

arm64_TMPL_OPRN_REGISTER_DWORD_OR_ZERO_DATASZ_DWORD_WRITE

arm64_TMPL_OPRN_REGISTER_SWORD_OR_STACK_DATASZ_SWORD_READ

arm64_TMPL_OPRN_REGISTER_SWORD_OR_STACK_DATASZ_SWORD_WRITE

arm64_TMPL_OPRN_REGISTER_SWORD_OR_ZERO_DATASZ_SWORD_READ

arm64_TMPL_OPRN_REGISTER_SWORD_OR_ZERO_DATASZ_SWORD_WRITE

arm64_TMPL_OPRN_REGISTER_SYSTEM_DATASZ_DWORD_READ

arm64_TMPL_OPRN_REGISTER_SYSTEM_DATASZ_DWORD_WRITE

 * */

#endif /* ARM64_ARCHMACROS_H_ */
