/*
   Copyright (C) 2004 - 2018 Université de Versailles Saint-Quentin-en-Yvelines (UVSQ)

   This file is part of MAQAO.

  MAQAO is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public License
   as published by the Free Software Foundation; either version 3
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */


/**
* \file arm64_fct.h
* \brief This file contains the prototypes of functions corresponding to semantic actions
* \warning This file has been automatically generated by MINJAG from file arm64_6bf96bbfcca0afd1af78d50ba75869a8.bdf and should not be modified
* */
#ifndef ARM64_FCT_H_
#define ARM64_FCT_H_

#ifdef BIN_CONDITION_0101
void *arm64_coder__0(void** vars,int var0);
#endif
#ifdef BIN_VAL_0_0000
extern void arm64_coder__1(void** vars);
extern void arm64_coder__2(void** vars);
extern void arm64_coder__3(void** vars);
extern void arm64_coder__4(void** vars);
extern void arm64_coder__5(void** vars);
extern void arm64_coder__6(void** vars);
#endif
#ifdef BIN_VAL_10_0000
extern void arm64_coder__7(void** vars);
extern void arm64_coder__8(void** vars);
extern void arm64_coder__9(void** vars);
#endif
#ifdef BIN_VAL_11_0000
extern void arm64_coder__10(void** vars);
extern void arm64_coder__11(void** vars);
extern void arm64_coder__12(void** vars);
#endif
#ifdef BIN_VAL_12_0000
extern void arm64_coder__13(void** vars);
extern void arm64_coder__14(void** vars);
extern void arm64_coder__15(void** vars);
#endif
#ifdef BIN_VAL_13_0000
extern void arm64_coder__16(void** vars);
extern void arm64_coder__17(void** vars);
extern void arm64_coder__18(void** vars);
#endif
#ifdef BIN_VAL_14_0000
extern void arm64_coder__19(void** vars);
extern void arm64_coder__20(void** vars);
extern void arm64_coder__21(void** vars);
#endif
#ifdef BIN_VAL_15_0000
extern void arm64_coder__22(void** vars);
extern void arm64_coder__23(void** vars);
extern void arm64_coder__24(void** vars);
#endif
#ifdef BIN_VAL_16_0000
extern void arm64_coder__25(void** vars);
extern void arm64_coder__26(void** vars);
extern void arm64_coder__27(void** vars);
#endif
#ifdef BIN_VAL_17_0000
extern void arm64_coder__28(void** vars);
extern void arm64_coder__29(void** vars);
extern void arm64_coder__30(void** vars);
#endif
#ifdef BIN_VAL_18_0000
extern void arm64_coder__31(void** vars);
extern void arm64_coder__32(void** vars);
extern void arm64_coder__33(void** vars);
#endif
#ifdef BIN_VAL_19_0000
extern void arm64_coder__34(void** vars);
extern void arm64_coder__35(void** vars);
extern void arm64_coder__36(void** vars);
#endif
#ifdef BIN_VAL_1_0000
extern void arm64_coder__37(void** vars);
extern void arm64_coder__38(void** vars);
extern void arm64_coder__39(void** vars);
extern void arm64_coder__40(void** vars);
extern void arm64_coder__41(void** vars);
extern void arm64_coder__42(void** vars);
#endif
#ifdef BIN_VAL_20_0000
extern void arm64_coder__43(void** vars);
extern void arm64_coder__44(void** vars);
extern void arm64_coder__45(void** vars);
#endif
#ifdef BIN_VAL_21_0000
extern void arm64_coder__46(void** vars);
extern void arm64_coder__47(void** vars);
extern void arm64_coder__48(void** vars);
#endif
#ifdef BIN_VAL_22_0000
extern void arm64_coder__49(void** vars);
extern void arm64_coder__50(void** vars);
extern void arm64_coder__51(void** vars);
#endif
#ifdef BIN_VAL_23_0000
extern void arm64_coder__52(void** vars);
extern void arm64_coder__53(void** vars);
extern void arm64_coder__54(void** vars);
#endif
#ifdef BIN_VAL_24_0000
extern void arm64_coder__55(void** vars);
extern void arm64_coder__56(void** vars);
extern void arm64_coder__57(void** vars);
#endif
#ifdef BIN_VAL_25_0000
extern void arm64_coder__58(void** vars);
extern void arm64_coder__59(void** vars);
extern void arm64_coder__60(void** vars);
#endif
#ifdef BIN_VAL_26_0000
extern void arm64_coder__61(void** vars);
extern void arm64_coder__62(void** vars);
extern void arm64_coder__63(void** vars);
#endif
#ifdef BIN_VAL_27_0000
extern void arm64_coder__64(void** vars);
extern void arm64_coder__65(void** vars);
extern void arm64_coder__66(void** vars);
#endif
#ifdef BIN_VAL_28_0000
extern void arm64_coder__67(void** vars);
extern void arm64_coder__68(void** vars);
extern void arm64_coder__69(void** vars);
#endif
#ifdef BIN_VAL_29_0000
extern void arm64_coder__70(void** vars);
extern void arm64_coder__71(void** vars);
extern void arm64_coder__72(void** vars);
#endif
#ifdef BIN_VAL_2_0000
extern void arm64_coder__73(void** vars);
extern void arm64_coder__74(void** vars);
extern void arm64_coder__75(void** vars);
extern void arm64_coder__76(void** vars);
extern void arm64_coder__77(void** vars);
extern void arm64_coder__78(void** vars);
extern void arm64_coder__79(void** vars);
#endif
#ifdef BIN_VAL_30_0000
extern void arm64_coder__80(void** vars);
extern void arm64_coder__81(void** vars);
#endif
#ifdef BIN_VAL_3_0000
extern void arm64_coder__82(void** vars);
extern void arm64_coder__83(void** vars);
extern void arm64_coder__84(void** vars);
extern void arm64_coder__85(void** vars);
#endif
#ifdef BIN_VAL_4_0000
extern void arm64_coder__86(void** vars);
extern void arm64_coder__87(void** vars);
extern void arm64_coder__88(void** vars);
extern void arm64_coder__89(void** vars);
#endif
#ifdef BIN_VAL_5_0000
extern void arm64_coder__90(void** vars);
extern void arm64_coder__91(void** vars);
extern void arm64_coder__92(void** vars);
extern void arm64_coder__93(void** vars);
#endif
#ifdef BIN_VAL_6_0000
extern void arm64_coder__94(void** vars);
extern void arm64_coder__95(void** vars);
extern void arm64_coder__96(void** vars);
extern void arm64_coder__97(void** vars);
extern void arm64_coder__98(void** vars);
#endif
#ifdef BIN_VAL_7_0000
extern void arm64_coder__99(void** vars);
extern void arm64_coder__100(void** vars);
extern void arm64_coder__101(void** vars);
extern void arm64_coder__102(void** vars);
#endif
#ifdef BIN_VAL_8_0000
extern void arm64_coder__103(void** vars);
extern void arm64_coder__104(void** vars);
extern void arm64_coder__105(void** vars);
#endif
#ifdef BIN_VAL_9_0000
extern void arm64_coder__106(void** vars);
extern void arm64_coder__107(void** vars);
extern void arm64_coder__108(void** vars);
#endif
#ifdef INSN_OPCODE_0a00
extern void arm64_coder__109(void** vars);
extern void arm64_coder__110(void** vars);
extern void arm64_coder__111(void** vars);
extern void arm64_coder__112(void** vars);
#endif
#ifdef INSN_OPCODE_1a00
extern void arm64_coder__113(void** vars);
extern void arm64_coder__114(void** vars);
extern void arm64_coder__115(void** vars);
extern void arm64_coder__116(void** vars);
extern void arm64_coder__117(void** vars);
extern void arm64_coder__118(void** vars);
extern void arm64_coder__119(void** vars);
extern void arm64_coder__120(void** vars);
extern void arm64_coder__121(void** vars);
extern void arm64_coder__122(void** vars);
extern void arm64_coder__123(void** vars);
extern void arm64_coder__124(void** vars);
extern void arm64_coder__125(void** vars);
extern void arm64_coder__126(void** vars);
extern void arm64_coder__127(void** vars);
extern void arm64_coder__128(void** vars);
extern void arm64_coder__129(void** vars);
extern void arm64_coder__130(void** vars);
#endif
#ifdef INSN_OPCODE_1a01
extern void arm64_coder__131(void** vars);
#endif
#ifdef INSN_OPCODE_2a00
extern void arm64_coder__132(void** vars);
extern void arm64_coder__133(void** vars);
extern void arm64_coder__134(void** vars);
extern void arm64_coder__135(void** vars);
extern void arm64_coder__136(void** vars);
extern void arm64_coder__137(void** vars);
extern void arm64_coder__138(void** vars);
extern void arm64_coder__139(void** vars);
extern void arm64_coder__140(void** vars);
extern void arm64_coder__141(void** vars);
extern void arm64_coder__142(void** vars);
extern void arm64_coder__143(void** vars);
extern void arm64_coder__144(void** vars);
extern void arm64_coder__145(void** vars);
extern void arm64_coder__146(void** vars);
extern void arm64_coder__147(void** vars);
extern void arm64_coder__148(void** vars);
extern void arm64_coder__149(void** vars);
extern void arm64_coder__150(void** vars);
extern void arm64_coder__151(void** vars);
extern void arm64_coder__152(void** vars);
extern void arm64_coder__153(void** vars);
extern void arm64_coder__154(void** vars);
extern void arm64_coder__155(void** vars);
extern void arm64_coder__156(void** vars);
extern void arm64_coder__157(void** vars);
extern void arm64_coder__158(void** vars);
extern void arm64_coder__159(void** vars);
extern void arm64_coder__160(void** vars);
extern void arm64_coder__161(void** vars);
extern void arm64_coder__162(void** vars);
extern void arm64_coder__163(void** vars);
extern void arm64_coder__164(void** vars);
extern void arm64_coder__165(void** vars);
extern void arm64_coder__166(void** vars);
extern void arm64_coder__167(void** vars);
extern void arm64_coder__168(void** vars);
extern void arm64_coder__169(void** vars);
extern void arm64_coder__170(void** vars);
extern void arm64_coder__171(void** vars);
extern void arm64_coder__172(void** vars);
extern void arm64_coder__173(void** vars);
extern void arm64_coder__174(void** vars);
extern void arm64_coder__175(void** vars);
extern void arm64_coder__176(void** vars);
extern void arm64_coder__177(void** vars);
extern void arm64_coder__178(void** vars);
extern void arm64_coder__179(void** vars);
extern void arm64_coder__180(void** vars);
extern void arm64_coder__181(void** vars);
extern void arm64_coder__182(void** vars);
extern void arm64_coder__183(void** vars);
extern void arm64_coder__184(void** vars);
extern void arm64_coder__185(void** vars);
extern void arm64_coder__186(void** vars);
extern void arm64_coder__187(void** vars);
extern void arm64_coder__188(void** vars);
extern void arm64_coder__189(void** vars);
extern void arm64_coder__190(void** vars);
extern void arm64_coder__191(void** vars);
extern void arm64_coder__192(void** vars);
extern void arm64_coder__193(void** vars);
extern void arm64_coder__194(void** vars);
extern void arm64_coder__195(void** vars);
extern void arm64_coder__196(void** vars);
extern void arm64_coder__197(void** vars);
extern void arm64_coder__198(void** vars);
extern void arm64_coder__199(void** vars);
extern void arm64_coder__200(void** vars);
extern void arm64_coder__201(void** vars);
extern void arm64_coder__202(void** vars);
extern void arm64_coder__203(void** vars);
extern void arm64_coder__204(void** vars);
extern void arm64_coder__205(void** vars);
extern void arm64_coder__206(void** vars);
extern void arm64_coder__207(void** vars);
extern void arm64_coder__208(void** vars);
extern void arm64_coder__209(void** vars);
extern void arm64_coder__210(void** vars);
extern void arm64_coder__211(void** vars);
extern void arm64_coder__212(void** vars);
extern void arm64_coder__213(void** vars);
extern void arm64_coder__214(void** vars);
extern void arm64_coder__215(void** vars);
extern void arm64_coder__216(void** vars);
extern void arm64_coder__217(void** vars);
extern void arm64_coder__218(void** vars);
extern void arm64_coder__219(void** vars);
extern void arm64_coder__220(void** vars);
extern void arm64_coder__221(void** vars);
extern void arm64_coder__222(void** vars);
extern void arm64_coder__223(void** vars);
extern void arm64_coder__224(void** vars);
extern void arm64_coder__225(void** vars);
extern void arm64_coder__226(void** vars);
extern void arm64_coder__227(void** vars);
extern void arm64_coder__228(void** vars);
extern void arm64_coder__229(void** vars);
extern void arm64_coder__230(void** vars);
extern void arm64_coder__231(void** vars);
extern void arm64_coder__232(void** vars);
extern void arm64_coder__233(void** vars);
extern void arm64_coder__234(void** vars);
extern void arm64_coder__235(void** vars);
extern void arm64_coder__236(void** vars);
extern void arm64_coder__237(void** vars);
extern void arm64_coder__238(void** vars);
extern void arm64_coder__239(void** vars);
extern void arm64_coder__240(void** vars);
extern void arm64_coder__241(void** vars);
extern void arm64_coder__242(void** vars);
extern void arm64_coder__243(void** vars);
extern void arm64_coder__244(void** vars);
extern void arm64_coder__245(void** vars);
extern void arm64_coder__246(void** vars);
extern void arm64_coder__247(void** vars);
extern void arm64_coder__248(void** vars);
extern void arm64_coder__249(void** vars);
extern void arm64_coder__250(void** vars);
extern void arm64_coder__251(void** vars);
extern void arm64_coder__252(void** vars);
extern void arm64_coder__253(void** vars);
extern void arm64_coder__254(void** vars);
extern void arm64_coder__255(void** vars);
extern void arm64_coder__256(void** vars);
extern void arm64_coder__257(void** vars);
extern void arm64_coder__258(void** vars);
extern void arm64_coder__259(void** vars);
extern void arm64_coder__260(void** vars);
extern void arm64_coder__261(void** vars);
extern void arm64_coder__262(void** vars);
extern void arm64_coder__263(void** vars);
extern void arm64_coder__264(void** vars);
extern void arm64_coder__265(void** vars);
extern void arm64_coder__266(void** vars);
extern void arm64_coder__267(void** vars);
extern void arm64_coder__268(void** vars);
extern void arm64_coder__269(void** vars);
extern void arm64_coder__270(void** vars);
extern void arm64_coder__271(void** vars);
extern void arm64_coder__272(void** vars);
extern void arm64_coder__273(void** vars);
extern void arm64_coder__274(void** vars);
extern void arm64_coder__275(void** vars);
extern void arm64_coder__276(void** vars);
extern void arm64_coder__277(void** vars);
extern void arm64_coder__278(void** vars);
extern void arm64_coder__279(void** vars);
extern void arm64_coder__280(void** vars);
extern void arm64_coder__281(void** vars);
extern void arm64_coder__282(void** vars);
extern void arm64_coder__283(void** vars);
extern void arm64_coder__284(void** vars);
extern void arm64_coder__285(void** vars);
extern void arm64_coder__286(void** vars);
extern void arm64_coder__287(void** vars);
extern void arm64_coder__288(void** vars);
extern void arm64_coder__289(void** vars);
extern void arm64_coder__290(void** vars);
extern void arm64_coder__291(void** vars);
extern void arm64_coder__292(void** vars);
extern void arm64_coder__293(void** vars);
extern void arm64_coder__294(void** vars);
extern void arm64_coder__295(void** vars);
extern void arm64_coder__296(void** vars);
extern void arm64_coder__297(void** vars);
extern void arm64_coder__298(void** vars);
extern void arm64_coder__299(void** vars);
extern void arm64_coder__300(void** vars);
extern void arm64_coder__301(void** vars);
extern void arm64_coder__302(void** vars);
extern void arm64_coder__303(void** vars);
extern void arm64_coder__304(void** vars);
extern void arm64_coder__305(void** vars);
extern void arm64_coder__306(void** vars);
extern void arm64_coder__307(void** vars);
extern void arm64_coder__308(void** vars);
extern void arm64_coder__309(void** vars);
extern void arm64_coder__310(void** vars);
extern void arm64_coder__311(void** vars);
extern void arm64_coder__312(void** vars);
extern void arm64_coder__313(void** vars);
extern void arm64_coder__314(void** vars);
extern void arm64_coder__315(void** vars);
extern void arm64_coder__316(void** vars);
extern void arm64_coder__317(void** vars);
extern void arm64_coder__318(void** vars);
extern void arm64_coder__319(void** vars);
extern void arm64_coder__320(void** vars);
extern void arm64_coder__321(void** vars);
extern void arm64_coder__322(void** vars);
extern void arm64_coder__323(void** vars);
extern void arm64_coder__324(void** vars);
extern void arm64_coder__325(void** vars);
extern void arm64_coder__326(void** vars);
extern void arm64_coder__327(void** vars);
extern void arm64_coder__328(void** vars);
extern void arm64_coder__329(void** vars);
extern void arm64_coder__330(void** vars);
extern void arm64_coder__331(void** vars);
extern void arm64_coder__332(void** vars);
extern void arm64_coder__333(void** vars);
extern void arm64_coder__334(void** vars);
extern void arm64_coder__335(void** vars);
extern void arm64_coder__336(void** vars);
extern void arm64_coder__337(void** vars);
extern void arm64_coder__338(void** vars);
extern void arm64_coder__339(void** vars);
extern void arm64_coder__340(void** vars);
extern void arm64_coder__341(void** vars);
extern void arm64_coder__342(void** vars);
extern void arm64_coder__343(void** vars);
extern void arm64_coder__344(void** vars);
extern void arm64_coder__345(void** vars);
extern void arm64_coder__346(void** vars);
extern void arm64_coder__347(void** vars);
extern void arm64_coder__348(void** vars);
extern void arm64_coder__349(void** vars);
extern void arm64_coder__350(void** vars);
extern void arm64_coder__351(void** vars);
extern void arm64_coder__352(void** vars);
extern void arm64_coder__353(void** vars);
extern void arm64_coder__354(void** vars);
extern void arm64_coder__355(void** vars);
extern void arm64_coder__356(void** vars);
extern void arm64_coder__357(void** vars);
extern void arm64_coder__358(void** vars);
extern void arm64_coder__359(void** vars);
extern void arm64_coder__360(void** vars);
extern void arm64_coder__361(void** vars);
extern void arm64_coder__362(void** vars);
extern void arm64_coder__363(void** vars);
extern void arm64_coder__364(void** vars);
extern void arm64_coder__365(void** vars);
extern void arm64_coder__366(void** vars);
extern void arm64_coder__367(void** vars);
extern void arm64_coder__368(void** vars);
extern void arm64_coder__369(void** vars);
extern void arm64_coder__370(void** vars);
extern void arm64_coder__371(void** vars);
extern void arm64_coder__372(void** vars);
extern void arm64_coder__373(void** vars);
extern void arm64_coder__374(void** vars);
extern void arm64_coder__375(void** vars);
extern void arm64_coder__376(void** vars);
extern void arm64_coder__377(void** vars);
extern void arm64_coder__378(void** vars);
extern void arm64_coder__379(void** vars);
extern void arm64_coder__380(void** vars);
extern void arm64_coder__381(void** vars);
extern void arm64_coder__382(void** vars);
extern void arm64_coder__383(void** vars);
extern void arm64_coder__384(void** vars);
extern void arm64_coder__385(void** vars);
extern void arm64_coder__386(void** vars);
extern void arm64_coder__387(void** vars);
extern void arm64_coder__388(void** vars);
extern void arm64_coder__389(void** vars);
extern void arm64_coder__390(void** vars);
extern void arm64_coder__391(void** vars);
extern void arm64_coder__392(void** vars);
extern void arm64_coder__393(void** vars);
extern void arm64_coder__394(void** vars);
extern void arm64_coder__395(void** vars);
extern void arm64_coder__396(void** vars);
extern void arm64_coder__397(void** vars);
extern void arm64_coder__398(void** vars);
extern void arm64_coder__399(void** vars);
extern void arm64_coder__400(void** vars);
extern void arm64_coder__401(void** vars);
extern void arm64_coder__402(void** vars);
extern void arm64_coder__403(void** vars);
extern void arm64_coder__404(void** vars);
extern void arm64_coder__405(void** vars);
extern void arm64_coder__406(void** vars);
extern void arm64_coder__407(void** vars);
extern void arm64_coder__408(void** vars);
extern void arm64_coder__409(void** vars);
extern void arm64_coder__410(void** vars);
extern void arm64_coder__411(void** vars);
extern void arm64_coder__412(void** vars);
extern void arm64_coder__413(void** vars);
extern void arm64_coder__414(void** vars);
extern void arm64_coder__415(void** vars);
extern void arm64_coder__416(void** vars);
extern void arm64_coder__417(void** vars);
extern void arm64_coder__418(void** vars);
extern void arm64_coder__419(void** vars);
extern void arm64_coder__420(void** vars);
extern void arm64_coder__421(void** vars);
extern void arm64_coder__422(void** vars);
extern void arm64_coder__423(void** vars);
extern void arm64_coder__424(void** vars);
extern void arm64_coder__425(void** vars);
extern void arm64_coder__426(void** vars);
extern void arm64_coder__427(void** vars);
extern void arm64_coder__428(void** vars);
extern void arm64_coder__429(void** vars);
extern void arm64_coder__430(void** vars);
extern void arm64_coder__431(void** vars);
extern void arm64_coder__432(void** vars);
extern void arm64_coder__433(void** vars);
extern void arm64_coder__434(void** vars);
extern void arm64_coder__435(void** vars);
extern void arm64_coder__436(void** vars);
extern void arm64_coder__437(void** vars);
extern void arm64_coder__438(void** vars);
extern void arm64_coder__439(void** vars);
extern void arm64_coder__440(void** vars);
extern void arm64_coder__441(void** vars);
extern void arm64_coder__442(void** vars);
extern void arm64_coder__443(void** vars);
extern void arm64_coder__444(void** vars);
extern void arm64_coder__445(void** vars);
extern void arm64_coder__446(void** vars);
extern void arm64_coder__447(void** vars);
extern void arm64_coder__448(void** vars);
extern void arm64_coder__449(void** vars);
extern void arm64_coder__450(void** vars);
extern void arm64_coder__451(void** vars);
extern void arm64_coder__452(void** vars);
extern void arm64_coder__453(void** vars);
extern void arm64_coder__454(void** vars);
extern void arm64_coder__455(void** vars);
extern void arm64_coder__456(void** vars);
extern void arm64_coder__457(void** vars);
extern void arm64_coder__458(void** vars);
extern void arm64_coder__459(void** vars);
extern void arm64_coder__460(void** vars);
extern void arm64_coder__461(void** vars);
extern void arm64_coder__462(void** vars);
extern void arm64_coder__463(void** vars);
extern void arm64_coder__464(void** vars);
extern void arm64_coder__465(void** vars);
extern void arm64_coder__466(void** vars);
extern void arm64_coder__467(void** vars);
extern void arm64_coder__468(void** vars);
extern void arm64_coder__469(void** vars);
extern void arm64_coder__470(void** vars);
extern void arm64_coder__471(void** vars);
extern void arm64_coder__472(void** vars);
extern void arm64_coder__473(void** vars);
extern void arm64_coder__474(void** vars);
extern void arm64_coder__475(void** vars);
extern void arm64_coder__476(void** vars);
extern void arm64_coder__477(void** vars);
extern void arm64_coder__478(void** vars);
extern void arm64_coder__479(void** vars);
extern void arm64_coder__480(void** vars);
extern void arm64_coder__481(void** vars);
extern void arm64_coder__482(void** vars);
extern void arm64_coder__483(void** vars);
extern void arm64_coder__484(void** vars);
extern void arm64_coder__485(void** vars);
extern void arm64_coder__486(void** vars);
extern void arm64_coder__487(void** vars);
extern void arm64_coder__488(void** vars);
extern void arm64_coder__489(void** vars);
extern void arm64_coder__490(void** vars);
extern void arm64_coder__491(void** vars);
extern void arm64_coder__492(void** vars);
extern void arm64_coder__493(void** vars);
extern void arm64_coder__494(void** vars);
extern void arm64_coder__495(void** vars);
extern void arm64_coder__496(void** vars);
extern void arm64_coder__497(void** vars);
extern void arm64_coder__498(void** vars);
extern void arm64_coder__499(void** vars);
extern void arm64_coder__500(void** vars);
extern void arm64_coder__501(void** vars);
extern void arm64_coder__502(void** vars);
extern void arm64_coder__503(void** vars);
extern void arm64_coder__504(void** vars);
extern void arm64_coder__505(void** vars);
extern void arm64_coder__506(void** vars);
extern void arm64_coder__507(void** vars);
extern void arm64_coder__508(void** vars);
extern void arm64_coder__509(void** vars);
extern void arm64_coder__510(void** vars);
extern void arm64_coder__511(void** vars);
extern void arm64_coder__512(void** vars);
extern void arm64_coder__513(void** vars);
extern void arm64_coder__514(void** vars);
extern void arm64_coder__515(void** vars);
extern void arm64_coder__516(void** vars);
extern void arm64_coder__517(void** vars);
extern void arm64_coder__518(void** vars);
extern void arm64_coder__519(void** vars);
extern void arm64_coder__520(void** vars);
extern void arm64_coder__521(void** vars);
extern void arm64_coder__522(void** vars);
extern void arm64_coder__523(void** vars);
extern void arm64_coder__524(void** vars);
extern void arm64_coder__525(void** vars);
extern void arm64_coder__526(void** vars);
extern void arm64_coder__527(void** vars);
extern void arm64_coder__528(void** vars);
extern void arm64_coder__529(void** vars);
#endif
#ifdef INSN_OPCODE_2b00
extern void arm64_coder__530(void** vars);
extern void arm64_coder__531(void** vars);
extern void arm64_coder__532(void** vars);
extern void arm64_coder__533(void** vars);
extern void arm64_coder__534(void** vars);
extern void arm64_coder__535(void** vars);
extern void arm64_coder__536(void** vars);
extern void arm64_coder__537(void** vars);
extern void arm64_coder__538(void** vars);
extern void arm64_coder__539(void** vars);
extern void arm64_coder__540(void** vars);
extern void arm64_coder__541(void** vars);
extern void arm64_coder__542(void** vars);
extern void arm64_coder__543(void** vars);
extern void arm64_coder__544(void** vars);
extern void arm64_coder__545(void** vars);
extern void arm64_coder__546(void** vars);
extern void arm64_coder__547(void** vars);
extern void arm64_coder__548(void** vars);
extern void arm64_coder__549(void** vars);
extern void arm64_coder__550(void** vars);
extern void arm64_coder__551(void** vars);
extern void arm64_coder__552(void** vars);
extern void arm64_coder__553(void** vars);
extern void arm64_coder__554(void** vars);
extern void arm64_coder__555(void** vars);
extern void arm64_coder__556(void** vars);
extern void arm64_coder__557(void** vars);
extern void arm64_coder__558(void** vars);
extern void arm64_coder__559(void** vars);
extern void arm64_coder__560(void** vars);
extern void arm64_coder__561(void** vars);
extern void arm64_coder__562(void** vars);
extern void arm64_coder__563(void** vars);
extern void arm64_coder__564(void** vars);
extern void arm64_coder__565(void** vars);
extern void arm64_coder__566(void** vars);
extern void arm64_coder__567(void** vars);
extern void arm64_coder__568(void** vars);
extern void arm64_coder__569(void** vars);
extern void arm64_coder__570(void** vars);
extern void arm64_coder__571(void** vars);
extern void arm64_coder__572(void** vars);
extern void arm64_coder__573(void** vars);
extern void arm64_coder__574(void** vars);
extern void arm64_coder__575(void** vars);
extern void arm64_coder__576(void** vars);
extern void arm64_coder__577(void** vars);
extern void arm64_coder__578(void** vars);
extern void arm64_coder__579(void** vars);
extern void arm64_coder__580(void** vars);
extern void arm64_coder__581(void** vars);
extern void arm64_coder__582(void** vars);
extern void arm64_coder__583(void** vars);
extern void arm64_coder__584(void** vars);
extern void arm64_coder__585(void** vars);
extern void arm64_coder__586(void** vars);
extern void arm64_coder__587(void** vars);
extern void arm64_coder__588(void** vars);
extern void arm64_coder__589(void** vars);
extern void arm64_coder__590(void** vars);
extern void arm64_coder__591(void** vars);
extern void arm64_coder__592(void** vars);
extern void arm64_coder__593(void** vars);
extern void arm64_coder__594(void** vars);
extern void arm64_coder__595(void** vars);
extern void arm64_coder__596(void** vars);
extern void arm64_coder__597(void** vars);
extern void arm64_coder__598(void** vars);
extern void arm64_coder__599(void** vars);
extern void arm64_coder__600(void** vars);
extern void arm64_coder__601(void** vars);
extern void arm64_coder__602(void** vars);
extern void arm64_coder__603(void** vars);
extern void arm64_coder__604(void** vars);
extern void arm64_coder__605(void** vars);
extern void arm64_coder__606(void** vars);
extern void arm64_coder__607(void** vars);
extern void arm64_coder__608(void** vars);
extern void arm64_coder__609(void** vars);
#endif
#ifdef INSN_OPCODE_2b01
extern void arm64_coder__610(void** vars);
extern void arm64_coder__611(void** vars);
extern void arm64_coder__612(void** vars);
extern void arm64_coder__613(void** vars);
extern void arm64_coder__614(void** vars);
extern void arm64_coder__615(void** vars);
extern void arm64_coder__616(void** vars);
extern void arm64_coder__617(void** vars);
extern void arm64_coder__618(void** vars);
extern void arm64_coder__619(void** vars);
extern void arm64_coder__620(void** vars);
extern void arm64_coder__621(void** vars);
extern void arm64_coder__622(void** vars);
extern void arm64_coder__623(void** vars);
extern void arm64_coder__624(void** vars);
extern void arm64_coder__625(void** vars);
extern void arm64_coder__626(void** vars);
extern void arm64_coder__627(void** vars);
extern void arm64_coder__628(void** vars);
extern void arm64_coder__629(void** vars);
extern void arm64_coder__630(void** vars);
extern void arm64_coder__631(void** vars);
extern void arm64_coder__632(void** vars);
extern void arm64_coder__633(void** vars);
extern void arm64_coder__634(void** vars);
extern void arm64_coder__635(void** vars);
extern void arm64_coder__636(void** vars);
extern void arm64_coder__637(void** vars);
extern void arm64_coder__638(void** vars);
extern void arm64_coder__639(void** vars);
extern void arm64_coder__640(void** vars);
extern void arm64_coder__641(void** vars);
extern void arm64_coder__642(void** vars);
extern void arm64_coder__643(void** vars);
extern void arm64_coder__644(void** vars);
extern void arm64_coder__645(void** vars);
extern void arm64_coder__646(void** vars);
extern void arm64_coder__647(void** vars);
extern void arm64_coder__648(void** vars);
extern void arm64_coder__649(void** vars);
extern void arm64_coder__650(void** vars);
extern void arm64_coder__651(void** vars);
extern void arm64_coder__652(void** vars);
extern void arm64_coder__653(void** vars);
extern void arm64_coder__654(void** vars);
extern void arm64_coder__655(void** vars);
extern void arm64_coder__656(void** vars);
extern void arm64_coder__657(void** vars);
extern void arm64_coder__658(void** vars);
extern void arm64_coder__659(void** vars);
extern void arm64_coder__660(void** vars);
extern void arm64_coder__661(void** vars);
extern void arm64_coder__662(void** vars);
extern void arm64_coder__663(void** vars);
extern void arm64_coder__664(void** vars);
extern void arm64_coder__665(void** vars);
extern void arm64_coder__666(void** vars);
extern void arm64_coder__667(void** vars);
extern void arm64_coder__668(void** vars);
extern void arm64_coder__669(void** vars);
extern void arm64_coder__670(void** vars);
#endif
#ifdef INSN_OPCODE_2b11
extern void arm64_coder__671(void** vars);
extern void arm64_coder__672(void** vars);
extern void arm64_coder__673(void** vars);
extern void arm64_coder__674(void** vars);
extern void arm64_coder__675(void** vars);
extern void arm64_coder__676(void** vars);
extern void arm64_coder__677(void** vars);
extern void arm64_coder__678(void** vars);
extern void arm64_coder__679(void** vars);
#endif
#ifdef INSN_OPCODE_2c00
extern void arm64_coder__680(void** vars);
extern void arm64_coder__681(void** vars);
extern void arm64_coder__682(void** vars);
extern void arm64_coder__683(void** vars);
extern void arm64_coder__684(void** vars);
extern void arm64_coder__685(void** vars);
extern void arm64_coder__686(void** vars);
extern void arm64_coder__687(void** vars);
extern void arm64_coder__688(void** vars);
extern void arm64_coder__689(void** vars);
extern void arm64_coder__690(void** vars);
extern void arm64_coder__691(void** vars);
extern void arm64_coder__692(void** vars);
extern void arm64_coder__693(void** vars);
extern void arm64_coder__694(void** vars);
extern void arm64_coder__695(void** vars);
extern void arm64_coder__696(void** vars);
extern void arm64_coder__697(void** vars);
extern void arm64_coder__698(void** vars);
extern void arm64_coder__699(void** vars);
extern void arm64_coder__700(void** vars);
extern void arm64_coder__701(void** vars);
extern void arm64_coder__702(void** vars);
extern void arm64_coder__703(void** vars);
extern void arm64_coder__704(void** vars);
extern void arm64_coder__705(void** vars);
extern void arm64_coder__706(void** vars);
extern void arm64_coder__707(void** vars);
extern void arm64_coder__708(void** vars);
extern void arm64_coder__709(void** vars);
extern void arm64_coder__710(void** vars);
#endif
#ifdef INSN_OPCODE_2c01
extern void arm64_coder__711(void** vars);
extern void arm64_coder__712(void** vars);
extern void arm64_coder__713(void** vars);
extern void arm64_coder__714(void** vars);
extern void arm64_coder__715(void** vars);
extern void arm64_coder__716(void** vars);
extern void arm64_coder__717(void** vars);
#endif
#ifdef INSN_OPCODE_2c11
extern void arm64_coder__718(void** vars);
extern void arm64_coder__719(void** vars);
extern void arm64_coder__720(void** vars);
extern void arm64_coder__721(void** vars);
#endif
#ifdef INSN_OPCODE_3a00
extern void arm64_coder__722(void** vars);
extern void arm64_coder__723(void** vars);
extern void arm64_coder__724(void** vars);
extern void arm64_coder__725(void** vars);
extern void arm64_coder__726(void** vars);
extern void arm64_coder__727(void** vars);
extern void arm64_coder__728(void** vars);
extern void arm64_coder__729(void** vars);
extern void arm64_coder__730(void** vars);
extern void arm64_coder__731(void** vars);
extern void arm64_coder__732(void** vars);
extern void arm64_coder__733(void** vars);
extern void arm64_coder__734(void** vars);
extern void arm64_coder__735(void** vars);
extern void arm64_coder__736(void** vars);
extern void arm64_coder__737(void** vars);
extern void arm64_coder__738(void** vars);
extern void arm64_coder__739(void** vars);
extern void arm64_coder__740(void** vars);
extern void arm64_coder__741(void** vars);
extern void arm64_coder__742(void** vars);
extern void arm64_coder__743(void** vars);
extern void arm64_coder__744(void** vars);
extern void arm64_coder__745(void** vars);
extern void arm64_coder__746(void** vars);
extern void arm64_coder__747(void** vars);
extern void arm64_coder__748(void** vars);
extern void arm64_coder__749(void** vars);
extern void arm64_coder__750(void** vars);
extern void arm64_coder__751(void** vars);
extern void arm64_coder__752(void** vars);
extern void arm64_coder__753(void** vars);
extern void arm64_coder__754(void** vars);
extern void arm64_coder__755(void** vars);
extern void arm64_coder__756(void** vars);
extern void arm64_coder__757(void** vars);
extern void arm64_coder__758(void** vars);
extern void arm64_coder__759(void** vars);
extern void arm64_coder__760(void** vars);
extern void arm64_coder__761(void** vars);
extern void arm64_coder__762(void** vars);
extern void arm64_coder__763(void** vars);
extern void arm64_coder__764(void** vars);
extern void arm64_coder__765(void** vars);
extern void arm64_coder__766(void** vars);
extern void arm64_coder__767(void** vars);
extern void arm64_coder__768(void** vars);
extern void arm64_coder__769(void** vars);
extern void arm64_coder__770(void** vars);
extern void arm64_coder__771(void** vars);
extern void arm64_coder__772(void** vars);
extern void arm64_coder__773(void** vars);
extern void arm64_coder__774(void** vars);
extern void arm64_coder__775(void** vars);
extern void arm64_coder__776(void** vars);
extern void arm64_coder__777(void** vars);
extern void arm64_coder__778(void** vars);
extern void arm64_coder__779(void** vars);
extern void arm64_coder__780(void** vars);
extern void arm64_coder__781(void** vars);
extern void arm64_coder__782(void** vars);
extern void arm64_coder__783(void** vars);
extern void arm64_coder__784(void** vars);
extern void arm64_coder__785(void** vars);
extern void arm64_coder__786(void** vars);
extern void arm64_coder__787(void** vars);
extern void arm64_coder__788(void** vars);
extern void arm64_coder__789(void** vars);
extern void arm64_coder__790(void** vars);
extern void arm64_coder__791(void** vars);
extern void arm64_coder__792(void** vars);
extern void arm64_coder__793(void** vars);
extern void arm64_coder__794(void** vars);
extern void arm64_coder__795(void** vars);
extern void arm64_coder__796(void** vars);
extern void arm64_coder__797(void** vars);
extern void arm64_coder__798(void** vars);
extern void arm64_coder__799(void** vars);
extern void arm64_coder__800(void** vars);
extern void arm64_coder__801(void** vars);
extern void arm64_coder__802(void** vars);
extern void arm64_coder__803(void** vars);
extern void arm64_coder__804(void** vars);
extern void arm64_coder__805(void** vars);
extern void arm64_coder__806(void** vars);
extern void arm64_coder__807(void** vars);
extern void arm64_coder__808(void** vars);
extern void arm64_coder__809(void** vars);
extern void arm64_coder__810(void** vars);
extern void arm64_coder__811(void** vars);
extern void arm64_coder__812(void** vars);
extern void arm64_coder__813(void** vars);
extern void arm64_coder__814(void** vars);
extern void arm64_coder__815(void** vars);
extern void arm64_coder__816(void** vars);
extern void arm64_coder__817(void** vars);
extern void arm64_coder__818(void** vars);
extern void arm64_coder__819(void** vars);
extern void arm64_coder__820(void** vars);
extern void arm64_coder__821(void** vars);
extern void arm64_coder__822(void** vars);
extern void arm64_coder__823(void** vars);
extern void arm64_coder__824(void** vars);
extern void arm64_coder__825(void** vars);
extern void arm64_coder__826(void** vars);
extern void arm64_coder__827(void** vars);
extern void arm64_coder__828(void** vars);
extern void arm64_coder__829(void** vars);
extern void arm64_coder__830(void** vars);
extern void arm64_coder__831(void** vars);
extern void arm64_coder__832(void** vars);
extern void arm64_coder__833(void** vars);
extern void arm64_coder__834(void** vars);
extern void arm64_coder__835(void** vars);
extern void arm64_coder__836(void** vars);
extern void arm64_coder__837(void** vars);
extern void arm64_coder__838(void** vars);
extern void arm64_coder__839(void** vars);
extern void arm64_coder__840(void** vars);
extern void arm64_coder__841(void** vars);
extern void arm64_coder__842(void** vars);
extern void arm64_coder__843(void** vars);
extern void arm64_coder__844(void** vars);
extern void arm64_coder__845(void** vars);
extern void arm64_coder__846(void** vars);
extern void arm64_coder__847(void** vars);
extern void arm64_coder__848(void** vars);
extern void arm64_coder__849(void** vars);
extern void arm64_coder__850(void** vars);
extern void arm64_coder__851(void** vars);
extern void arm64_coder__852(void** vars);
extern void arm64_coder__853(void** vars);
extern void arm64_coder__854(void** vars);
extern void arm64_coder__855(void** vars);
extern void arm64_coder__856(void** vars);
extern void arm64_coder__857(void** vars);
extern void arm64_coder__858(void** vars);
extern void arm64_coder__859(void** vars);
extern void arm64_coder__860(void** vars);
extern void arm64_coder__861(void** vars);
extern void arm64_coder__862(void** vars);
extern void arm64_coder__863(void** vars);
extern void arm64_coder__864(void** vars);
extern void arm64_coder__865(void** vars);
extern void arm64_coder__866(void** vars);
extern void arm64_coder__867(void** vars);
extern void arm64_coder__868(void** vars);
extern void arm64_coder__869(void** vars);
extern void arm64_coder__870(void** vars);
extern void arm64_coder__871(void** vars);
extern void arm64_coder__872(void** vars);
extern void arm64_coder__873(void** vars);
extern void arm64_coder__874(void** vars);
extern void arm64_coder__875(void** vars);
extern void arm64_coder__876(void** vars);
extern void arm64_coder__877(void** vars);
extern void arm64_coder__878(void** vars);
extern void arm64_coder__879(void** vars);
extern void arm64_coder__880(void** vars);
extern void arm64_coder__881(void** vars);
extern void arm64_coder__882(void** vars);
extern void arm64_coder__883(void** vars);
extern void arm64_coder__884(void** vars);
extern void arm64_coder__885(void** vars);
extern void arm64_coder__886(void** vars);
extern void arm64_coder__887(void** vars);
extern void arm64_coder__888(void** vars);
extern void arm64_coder__889(void** vars);
extern void arm64_coder__890(void** vars);
extern void arm64_coder__891(void** vars);
extern void arm64_coder__892(void** vars);
extern void arm64_coder__893(void** vars);
extern void arm64_coder__894(void** vars);
extern void arm64_coder__895(void** vars);
extern void arm64_coder__896(void** vars);
extern void arm64_coder__897(void** vars);
extern void arm64_coder__898(void** vars);
extern void arm64_coder__899(void** vars);
extern void arm64_coder__900(void** vars);
extern void arm64_coder__901(void** vars);
extern void arm64_coder__902(void** vars);
extern void arm64_coder__903(void** vars);
extern void arm64_coder__904(void** vars);
extern void arm64_coder__905(void** vars);
extern void arm64_coder__906(void** vars);
extern void arm64_coder__907(void** vars);
extern void arm64_coder__908(void** vars);
extern void arm64_coder__909(void** vars);
extern void arm64_coder__910(void** vars);
extern void arm64_coder__911(void** vars);
extern void arm64_coder__912(void** vars);
extern void arm64_coder__913(void** vars);
extern void arm64_coder__914(void** vars);
extern void arm64_coder__915(void** vars);
extern void arm64_coder__916(void** vars);
extern void arm64_coder__917(void** vars);
extern void arm64_coder__918(void** vars);
extern void arm64_coder__919(void** vars);
extern void arm64_coder__920(void** vars);
extern void arm64_coder__921(void** vars);
extern void arm64_coder__922(void** vars);
extern void arm64_coder__923(void** vars);
extern void arm64_coder__924(void** vars);
extern void arm64_coder__925(void** vars);
extern void arm64_coder__926(void** vars);
extern void arm64_coder__927(void** vars);
extern void arm64_coder__928(void** vars);
extern void arm64_coder__929(void** vars);
extern void arm64_coder__930(void** vars);
extern void arm64_coder__931(void** vars);
extern void arm64_coder__932(void** vars);
extern void arm64_coder__933(void** vars);
extern void arm64_coder__934(void** vars);
extern void arm64_coder__935(void** vars);
extern void arm64_coder__936(void** vars);
extern void arm64_coder__937(void** vars);
extern void arm64_coder__938(void** vars);
extern void arm64_coder__939(void** vars);
extern void arm64_coder__940(void** vars);
extern void arm64_coder__941(void** vars);
extern void arm64_coder__942(void** vars);
extern void arm64_coder__943(void** vars);
extern void arm64_coder__944(void** vars);
extern void arm64_coder__945(void** vars);
extern void arm64_coder__946(void** vars);
extern void arm64_coder__947(void** vars);
extern void arm64_coder__948(void** vars);
extern void arm64_coder__949(void** vars);
extern void arm64_coder__950(void** vars);
extern void arm64_coder__951(void** vars);
extern void arm64_coder__952(void** vars);
extern void arm64_coder__953(void** vars);
extern void arm64_coder__954(void** vars);
extern void arm64_coder__955(void** vars);
extern void arm64_coder__956(void** vars);
extern void arm64_coder__957(void** vars);
extern void arm64_coder__958(void** vars);
extern void arm64_coder__959(void** vars);
extern void arm64_coder__960(void** vars);
extern void arm64_coder__961(void** vars);
extern void arm64_coder__962(void** vars);
extern void arm64_coder__963(void** vars);
extern void arm64_coder__964(void** vars);
extern void arm64_coder__965(void** vars);
extern void arm64_coder__966(void** vars);
extern void arm64_coder__967(void** vars);
extern void arm64_coder__968(void** vars);
extern void arm64_coder__969(void** vars);
extern void arm64_coder__970(void** vars);
extern void arm64_coder__971(void** vars);
extern void arm64_coder__972(void** vars);
extern void arm64_coder__973(void** vars);
extern void arm64_coder__974(void** vars);
extern void arm64_coder__975(void** vars);
extern void arm64_coder__976(void** vars);
extern void arm64_coder__977(void** vars);
extern void arm64_coder__978(void** vars);
extern void arm64_coder__979(void** vars);
extern void arm64_coder__980(void** vars);
extern void arm64_coder__981(void** vars);
extern void arm64_coder__982(void** vars);
extern void arm64_coder__983(void** vars);
extern void arm64_coder__984(void** vars);
extern void arm64_coder__985(void** vars);
extern void arm64_coder__986(void** vars);
extern void arm64_coder__987(void** vars);
extern void arm64_coder__988(void** vars);
extern void arm64_coder__989(void** vars);
extern void arm64_coder__990(void** vars);
extern void arm64_coder__991(void** vars);
extern void arm64_coder__992(void** vars);
extern void arm64_coder__993(void** vars);
extern void arm64_coder__994(void** vars);
extern void arm64_coder__995(void** vars);
extern void arm64_coder__996(void** vars);
extern void arm64_coder__997(void** vars);
extern void arm64_coder__998(void** vars);
extern void arm64_coder__999(void** vars);
extern void arm64_coder__1000(void** vars);
extern void arm64_coder__1001(void** vars);
extern void arm64_coder__1002(void** vars);
extern void arm64_coder__1003(void** vars);
extern void arm64_coder__1004(void** vars);
extern void arm64_coder__1005(void** vars);
extern void arm64_coder__1006(void** vars);
extern void arm64_coder__1007(void** vars);
extern void arm64_coder__1008(void** vars);
extern void arm64_coder__1009(void** vars);
extern void arm64_coder__1010(void** vars);
extern void arm64_coder__1011(void** vars);
extern void arm64_coder__1012(void** vars);
extern void arm64_coder__1013(void** vars);
extern void arm64_coder__1014(void** vars);
extern void arm64_coder__1015(void** vars);
extern void arm64_coder__1016(void** vars);
extern void arm64_coder__1017(void** vars);
extern void arm64_coder__1018(void** vars);
extern void arm64_coder__1019(void** vars);
extern void arm64_coder__1020(void** vars);
extern void arm64_coder__1021(void** vars);
extern void arm64_coder__1022(void** vars);
extern void arm64_coder__1023(void** vars);
extern void arm64_coder__1024(void** vars);
extern void arm64_coder__1025(void** vars);
extern void arm64_coder__1026(void** vars);
extern void arm64_coder__1027(void** vars);
extern void arm64_coder__1028(void** vars);
extern void arm64_coder__1029(void** vars);
extern void arm64_coder__1030(void** vars);
extern void arm64_coder__1031(void** vars);
extern void arm64_coder__1032(void** vars);
extern void arm64_coder__1033(void** vars);
extern void arm64_coder__1034(void** vars);
extern void arm64_coder__1035(void** vars);
extern void arm64_coder__1036(void** vars);
extern void arm64_coder__1037(void** vars);
extern void arm64_coder__1038(void** vars);
extern void arm64_coder__1039(void** vars);
extern void arm64_coder__1040(void** vars);
#endif
#ifdef INSN_OPCODE_3b00
extern void arm64_coder__1041(void** vars);
extern void arm64_coder__1042(void** vars);
extern void arm64_coder__1043(void** vars);
extern void arm64_coder__1044(void** vars);
extern void arm64_coder__1045(void** vars);
extern void arm64_coder__1046(void** vars);
extern void arm64_coder__1047(void** vars);
extern void arm64_coder__1048(void** vars);
extern void arm64_coder__1049(void** vars);
extern void arm64_coder__1050(void** vars);
extern void arm64_coder__1051(void** vars);
extern void arm64_coder__1052(void** vars);
extern void arm64_coder__1053(void** vars);
extern void arm64_coder__1054(void** vars);
extern void arm64_coder__1055(void** vars);
extern void arm64_coder__1056(void** vars);
extern void arm64_coder__1057(void** vars);
extern void arm64_coder__1058(void** vars);
extern void arm64_coder__1059(void** vars);
extern void arm64_coder__1060(void** vars);
extern void arm64_coder__1061(void** vars);
extern void arm64_coder__1062(void** vars);
extern void arm64_coder__1063(void** vars);
extern void arm64_coder__1064(void** vars);
extern void arm64_coder__1065(void** vars);
extern void arm64_coder__1066(void** vars);
extern void arm64_coder__1067(void** vars);
extern void arm64_coder__1068(void** vars);
extern void arm64_coder__1069(void** vars);
extern void arm64_coder__1070(void** vars);
extern void arm64_coder__1071(void** vars);
extern void arm64_coder__1072(void** vars);
extern void arm64_coder__1073(void** vars);
extern void arm64_coder__1074(void** vars);
extern void arm64_coder__1075(void** vars);
extern void arm64_coder__1076(void** vars);
extern void arm64_coder__1077(void** vars);
extern void arm64_coder__1078(void** vars);
extern void arm64_coder__1079(void** vars);
extern void arm64_coder__1080(void** vars);
extern void arm64_coder__1081(void** vars);
extern void arm64_coder__1082(void** vars);
extern void arm64_coder__1083(void** vars);
extern void arm64_coder__1084(void** vars);
extern void arm64_coder__1085(void** vars);
extern void arm64_coder__1086(void** vars);
extern void arm64_coder__1087(void** vars);
extern void arm64_coder__1088(void** vars);
extern void arm64_coder__1089(void** vars);
extern void arm64_coder__1090(void** vars);
extern void arm64_coder__1091(void** vars);
extern void arm64_coder__1092(void** vars);
extern void arm64_coder__1093(void** vars);
extern void arm64_coder__1094(void** vars);
extern void arm64_coder__1095(void** vars);
extern void arm64_coder__1096(void** vars);
extern void arm64_coder__1097(void** vars);
extern void arm64_coder__1098(void** vars);
extern void arm64_coder__1099(void** vars);
extern void arm64_coder__1100(void** vars);
extern void arm64_coder__1101(void** vars);
extern void arm64_coder__1102(void** vars);
extern void arm64_coder__1103(void** vars);
extern void arm64_coder__1104(void** vars);
extern void arm64_coder__1105(void** vars);
extern void arm64_coder__1106(void** vars);
extern void arm64_coder__1107(void** vars);
extern void arm64_coder__1108(void** vars);
extern void arm64_coder__1109(void** vars);
extern void arm64_coder__1110(void** vars);
extern void arm64_coder__1111(void** vars);
extern void arm64_coder__1112(void** vars);
extern void arm64_coder__1113(void** vars);
extern void arm64_coder__1114(void** vars);
extern void arm64_coder__1115(void** vars);
extern void arm64_coder__1116(void** vars);
extern void arm64_coder__1117(void** vars);
extern void arm64_coder__1118(void** vars);
extern void arm64_coder__1119(void** vars);
extern void arm64_coder__1120(void** vars);
extern void arm64_coder__1121(void** vars);
extern void arm64_coder__1122(void** vars);
extern void arm64_coder__1123(void** vars);
extern void arm64_coder__1124(void** vars);
extern void arm64_coder__1125(void** vars);
extern void arm64_coder__1126(void** vars);
extern void arm64_coder__1127(void** vars);
extern void arm64_coder__1128(void** vars);
extern void arm64_coder__1129(void** vars);
extern void arm64_coder__1130(void** vars);
extern void arm64_coder__1131(void** vars);
extern void arm64_coder__1132(void** vars);
extern void arm64_coder__1133(void** vars);
extern void arm64_coder__1134(void** vars);
extern void arm64_coder__1135(void** vars);
extern void arm64_coder__1136(void** vars);
extern void arm64_coder__1137(void** vars);
extern void arm64_coder__1138(void** vars);
extern void arm64_coder__1139(void** vars);
extern void arm64_coder__1140(void** vars);
extern void arm64_coder__1141(void** vars);
extern void arm64_coder__1142(void** vars);
extern void arm64_coder__1143(void** vars);
extern void arm64_coder__1144(void** vars);
extern void arm64_coder__1145(void** vars);
extern void arm64_coder__1146(void** vars);
extern void arm64_coder__1147(void** vars);
extern void arm64_coder__1148(void** vars);
extern void arm64_coder__1149(void** vars);
extern void arm64_coder__1150(void** vars);
extern void arm64_coder__1151(void** vars);
extern void arm64_coder__1152(void** vars);
#endif
#ifdef INSN_OPCODE_3b01
extern void arm64_coder__1153(void** vars);
extern void arm64_coder__1154(void** vars);
extern void arm64_coder__1155(void** vars);
extern void arm64_coder__1156(void** vars);
extern void arm64_coder__1157(void** vars);
extern void arm64_coder__1158(void** vars);
extern void arm64_coder__1159(void** vars);
extern void arm64_coder__1160(void** vars);
extern void arm64_coder__1161(void** vars);
extern void arm64_coder__1162(void** vars);
extern void arm64_coder__1163(void** vars);
extern void arm64_coder__1164(void** vars);
extern void arm64_coder__1165(void** vars);
extern void arm64_coder__1166(void** vars);
extern void arm64_coder__1167(void** vars);
extern void arm64_coder__1168(void** vars);
extern void arm64_coder__1169(void** vars);
extern void arm64_coder__1170(void** vars);
extern void arm64_coder__1171(void** vars);
extern void arm64_coder__1172(void** vars);
extern void arm64_coder__1173(void** vars);
extern void arm64_coder__1174(void** vars);
extern void arm64_coder__1175(void** vars);
extern void arm64_coder__1176(void** vars);
extern void arm64_coder__1177(void** vars);
extern void arm64_coder__1178(void** vars);
extern void arm64_coder__1179(void** vars);
extern void arm64_coder__1180(void** vars);
extern void arm64_coder__1181(void** vars);
extern void arm64_coder__1182(void** vars);
extern void arm64_coder__1183(void** vars);
extern void arm64_coder__1184(void** vars);
extern void arm64_coder__1185(void** vars);
extern void arm64_coder__1186(void** vars);
extern void arm64_coder__1187(void** vars);
extern void arm64_coder__1188(void** vars);
extern void arm64_coder__1189(void** vars);
extern void arm64_coder__1190(void** vars);
extern void arm64_coder__1191(void** vars);
extern void arm64_coder__1192(void** vars);
extern void arm64_coder__1193(void** vars);
extern void arm64_coder__1194(void** vars);
extern void arm64_coder__1195(void** vars);
extern void arm64_coder__1196(void** vars);
extern void arm64_coder__1197(void** vars);
extern void arm64_coder__1198(void** vars);
extern void arm64_coder__1199(void** vars);
extern void arm64_coder__1200(void** vars);
extern void arm64_coder__1201(void** vars);
extern void arm64_coder__1202(void** vars);
extern void arm64_coder__1203(void** vars);
extern void arm64_coder__1204(void** vars);
extern void arm64_coder__1205(void** vars);
extern void arm64_coder__1206(void** vars);
extern void arm64_coder__1207(void** vars);
extern void arm64_coder__1208(void** vars);
extern void arm64_coder__1209(void** vars);
extern void arm64_coder__1210(void** vars);
extern void arm64_coder__1211(void** vars);
extern void arm64_coder__1212(void** vars);
extern void arm64_coder__1213(void** vars);
extern void arm64_coder__1214(void** vars);
extern void arm64_coder__1215(void** vars);
extern void arm64_coder__1216(void** vars);
extern void arm64_coder__1217(void** vars);
extern void arm64_coder__1218(void** vars);
extern void arm64_coder__1219(void** vars);
extern void arm64_coder__1220(void** vars);
extern void arm64_coder__1221(void** vars);
extern void arm64_coder__1222(void** vars);
extern void arm64_coder__1223(void** vars);
extern void arm64_coder__1224(void** vars);
extern void arm64_coder__1225(void** vars);
extern void arm64_coder__1226(void** vars);
extern void arm64_coder__1227(void** vars);
extern void arm64_coder__1228(void** vars);
extern void arm64_coder__1229(void** vars);
extern void arm64_coder__1230(void** vars);
extern void arm64_coder__1231(void** vars);
extern void arm64_coder__1232(void** vars);
extern void arm64_coder__1233(void** vars);
extern void arm64_coder__1234(void** vars);
extern void arm64_coder__1235(void** vars);
extern void arm64_coder__1236(void** vars);
extern void arm64_coder__1237(void** vars);
extern void arm64_coder__1238(void** vars);
extern void arm64_coder__1239(void** vars);
extern void arm64_coder__1240(void** vars);
extern void arm64_coder__1241(void** vars);
extern void arm64_coder__1242(void** vars);
extern void arm64_coder__1243(void** vars);
#endif
#ifdef INSN_OPCODE_3b11
extern void arm64_coder__1244(void** vars);
extern void arm64_coder__1245(void** vars);
extern void arm64_coder__1246(void** vars);
extern void arm64_coder__1247(void** vars);
extern void arm64_coder__1248(void** vars);
extern void arm64_coder__1249(void** vars);
extern void arm64_coder__1250(void** vars);
extern void arm64_coder__1251(void** vars);
extern void arm64_coder__1252(void** vars);
extern void arm64_coder__1253(void** vars);
extern void arm64_coder__1254(void** vars);
extern void arm64_coder__1255(void** vars);
extern void arm64_coder__1256(void** vars);
extern void arm64_coder__1257(void** vars);
extern void arm64_coder__1258(void** vars);
extern void arm64_coder__1259(void** vars);
extern void arm64_coder__1260(void** vars);
extern void arm64_coder__1261(void** vars);
extern void arm64_coder__1262(void** vars);
extern void arm64_coder__1263(void** vars);
extern void arm64_coder__1264(void** vars);
extern void arm64_coder__1265(void** vars);
extern void arm64_coder__1266(void** vars);
extern void arm64_coder__1267(void** vars);
extern void arm64_coder__1268(void** vars);
extern void arm64_coder__1269(void** vars);
extern void arm64_coder__1270(void** vars);
extern void arm64_coder__1271(void** vars);
extern void arm64_coder__1272(void** vars);
extern void arm64_coder__1273(void** vars);
extern void arm64_coder__1274(void** vars);
extern void arm64_coder__1275(void** vars);
extern void arm64_coder__1276(void** vars);
extern void arm64_coder__1277(void** vars);
extern void arm64_coder__1278(void** vars);
extern void arm64_coder__1279(void** vars);
extern void arm64_coder__1280(void** vars);
extern void arm64_coder__1281(void** vars);
extern void arm64_coder__1282(void** vars);
extern void arm64_coder__1283(void** vars);
extern void arm64_coder__1284(void** vars);
extern void arm64_coder__1285(void** vars);
extern void arm64_coder__1286(void** vars);
extern void arm64_coder__1287(void** vars);
extern void arm64_coder__1288(void** vars);
extern void arm64_coder__1289(void** vars);
extern void arm64_coder__1290(void** vars);
extern void arm64_coder__1291(void** vars);
extern void arm64_coder__1292(void** vars);
extern void arm64_coder__1293(void** vars);
extern void arm64_coder__1294(void** vars);
extern void arm64_coder__1295(void** vars);
#endif
#ifdef INSN_OPCODE_3c00
extern void arm64_coder__1296(void** vars);
extern void arm64_coder__1297(void** vars);
extern void arm64_coder__1298(void** vars);
extern void arm64_coder__1299(void** vars);
extern void arm64_coder__1300(void** vars);
extern void arm64_coder__1301(void** vars);
extern void arm64_coder__1302(void** vars);
extern void arm64_coder__1303(void** vars);
extern void arm64_coder__1304(void** vars);
extern void arm64_coder__1305(void** vars);
extern void arm64_coder__1306(void** vars);
extern void arm64_coder__1307(void** vars);
extern void arm64_coder__1308(void** vars);
extern void arm64_coder__1309(void** vars);
extern void arm64_coder__1310(void** vars);
extern void arm64_coder__1311(void** vars);
extern void arm64_coder__1312(void** vars);
extern void arm64_coder__1313(void** vars);
extern void arm64_coder__1314(void** vars);
extern void arm64_coder__1315(void** vars);
extern void arm64_coder__1316(void** vars);
extern void arm64_coder__1317(void** vars);
extern void arm64_coder__1318(void** vars);
extern void arm64_coder__1319(void** vars);
extern void arm64_coder__1320(void** vars);
extern void arm64_coder__1321(void** vars);
extern void arm64_coder__1322(void** vars);
extern void arm64_coder__1323(void** vars);
extern void arm64_coder__1324(void** vars);
extern void arm64_coder__1325(void** vars);
extern void arm64_coder__1326(void** vars);
extern void arm64_coder__1327(void** vars);
extern void arm64_coder__1328(void** vars);
extern void arm64_coder__1329(void** vars);
extern void arm64_coder__1330(void** vars);
extern void arm64_coder__1331(void** vars);
extern void arm64_coder__1332(void** vars);
extern void arm64_coder__1333(void** vars);
extern void arm64_coder__1334(void** vars);
extern void arm64_coder__1335(void** vars);
extern void arm64_coder__1336(void** vars);
extern void arm64_coder__1337(void** vars);
extern void arm64_coder__1338(void** vars);
extern void arm64_coder__1339(void** vars);
extern void arm64_coder__1340(void** vars);
extern void arm64_coder__1341(void** vars);
extern void arm64_coder__1342(void** vars);
extern void arm64_coder__1343(void** vars);
extern void arm64_coder__1344(void** vars);
extern void arm64_coder__1345(void** vars);
extern void arm64_coder__1346(void** vars);
extern void arm64_coder__1347(void** vars);
extern void arm64_coder__1348(void** vars);
extern void arm64_coder__1349(void** vars);
extern void arm64_coder__1350(void** vars);
extern void arm64_coder__1351(void** vars);
extern void arm64_coder__1352(void** vars);
extern void arm64_coder__1353(void** vars);
extern void arm64_coder__1354(void** vars);
extern void arm64_coder__1355(void** vars);
extern void arm64_coder__1356(void** vars);
extern void arm64_coder__1357(void** vars);
extern void arm64_coder__1358(void** vars);
extern void arm64_coder__1359(void** vars);
extern void arm64_coder__1360(void** vars);
extern void arm64_coder__1361(void** vars);
extern void arm64_coder__1362(void** vars);
extern void arm64_coder__1363(void** vars);
extern void arm64_coder__1364(void** vars);
extern void arm64_coder__1365(void** vars);
extern void arm64_coder__1366(void** vars);
extern void arm64_coder__1367(void** vars);
extern void arm64_coder__1368(void** vars);
extern void arm64_coder__1369(void** vars);
extern void arm64_coder__1370(void** vars);
extern void arm64_coder__1371(void** vars);
extern void arm64_coder__1372(void** vars);
extern void arm64_coder__1373(void** vars);
extern void arm64_coder__1374(void** vars);
extern void arm64_coder__1375(void** vars);
extern void arm64_coder__1376(void** vars);
extern void arm64_coder__1377(void** vars);
extern void arm64_coder__1378(void** vars);
extern void arm64_coder__1379(void** vars);
extern void arm64_coder__1380(void** vars);
extern void arm64_coder__1381(void** vars);
extern void arm64_coder__1382(void** vars);
extern void arm64_coder__1383(void** vars);
extern void arm64_coder__1384(void** vars);
extern void arm64_coder__1385(void** vars);
extern void arm64_coder__1386(void** vars);
extern void arm64_coder__1387(void** vars);
extern void arm64_coder__1388(void** vars);
extern void arm64_coder__1389(void** vars);
extern void arm64_coder__1390(void** vars);
extern void arm64_coder__1391(void** vars);
extern void arm64_coder__1392(void** vars);
extern void arm64_coder__1393(void** vars);
extern void arm64_coder__1394(void** vars);
extern void arm64_coder__1395(void** vars);
extern void arm64_coder__1396(void** vars);
extern void arm64_coder__1397(void** vars);
extern void arm64_coder__1398(void** vars);
extern void arm64_coder__1399(void** vars);
extern void arm64_coder__1400(void** vars);
extern void arm64_coder__1401(void** vars);
extern void arm64_coder__1402(void** vars);
extern void arm64_coder__1403(void** vars);
extern void arm64_coder__1404(void** vars);
extern void arm64_coder__1405(void** vars);
extern void arm64_coder__1406(void** vars);
extern void arm64_coder__1407(void** vars);
extern void arm64_coder__1408(void** vars);
extern void arm64_coder__1409(void** vars);
extern void arm64_coder__1410(void** vars);
extern void arm64_coder__1411(void** vars);
extern void arm64_coder__1412(void** vars);
extern void arm64_coder__1413(void** vars);
extern void arm64_coder__1414(void** vars);
extern void arm64_coder__1415(void** vars);
extern void arm64_coder__1416(void** vars);
extern void arm64_coder__1417(void** vars);
extern void arm64_coder__1418(void** vars);
extern void arm64_coder__1419(void** vars);
extern void arm64_coder__1420(void** vars);
extern void arm64_coder__1421(void** vars);
extern void arm64_coder__1422(void** vars);
extern void arm64_coder__1423(void** vars);
extern void arm64_coder__1424(void** vars);
extern void arm64_coder__1425(void** vars);
extern void arm64_coder__1426(void** vars);
extern void arm64_coder__1427(void** vars);
extern void arm64_coder__1428(void** vars);
extern void arm64_coder__1429(void** vars);
extern void arm64_coder__1430(void** vars);
extern void arm64_coder__1431(void** vars);
extern void arm64_coder__1432(void** vars);
extern void arm64_coder__1433(void** vars);
extern void arm64_coder__1434(void** vars);
extern void arm64_coder__1435(void** vars);
extern void arm64_coder__1436(void** vars);
extern void arm64_coder__1437(void** vars);
extern void arm64_coder__1438(void** vars);
extern void arm64_coder__1439(void** vars);
extern void arm64_coder__1440(void** vars);
extern void arm64_coder__1441(void** vars);
extern void arm64_coder__1442(void** vars);
extern void arm64_coder__1443(void** vars);
extern void arm64_coder__1444(void** vars);
extern void arm64_coder__1445(void** vars);
extern void arm64_coder__1446(void** vars);
extern void arm64_coder__1447(void** vars);
extern void arm64_coder__1448(void** vars);
extern void arm64_coder__1449(void** vars);
extern void arm64_coder__1450(void** vars);
extern void arm64_coder__1451(void** vars);
extern void arm64_coder__1452(void** vars);
extern void arm64_coder__1453(void** vars);
extern void arm64_coder__1454(void** vars);
extern void arm64_coder__1455(void** vars);
extern void arm64_coder__1456(void** vars);
extern void arm64_coder__1457(void** vars);
extern void arm64_coder__1458(void** vars);
extern void arm64_coder__1459(void** vars);
extern void arm64_coder__1460(void** vars);
extern void arm64_coder__1461(void** vars);
extern void arm64_coder__1462(void** vars);
extern void arm64_coder__1463(void** vars);
extern void arm64_coder__1464(void** vars);
extern void arm64_coder__1465(void** vars);
extern void arm64_coder__1466(void** vars);
extern void arm64_coder__1467(void** vars);
extern void arm64_coder__1468(void** vars);
extern void arm64_coder__1469(void** vars);
extern void arm64_coder__1470(void** vars);
extern void arm64_coder__1471(void** vars);
extern void arm64_coder__1472(void** vars);
extern void arm64_coder__1473(void** vars);
extern void arm64_coder__1474(void** vars);
extern void arm64_coder__1475(void** vars);
extern void arm64_coder__1476(void** vars);
extern void arm64_coder__1477(void** vars);
extern void arm64_coder__1478(void** vars);
extern void arm64_coder__1479(void** vars);
extern void arm64_coder__1480(void** vars);
extern void arm64_coder__1481(void** vars);
extern void arm64_coder__1482(void** vars);
extern void arm64_coder__1483(void** vars);
extern void arm64_coder__1484(void** vars);
extern void arm64_coder__1485(void** vars);
extern void arm64_coder__1486(void** vars);
extern void arm64_coder__1487(void** vars);
extern void arm64_coder__1488(void** vars);
extern void arm64_coder__1489(void** vars);
#endif
#ifdef INSN_OPCODE_3c01
extern void arm64_coder__1490(void** vars);
extern void arm64_coder__1491(void** vars);
extern void arm64_coder__1492(void** vars);
extern void arm64_coder__1493(void** vars);
extern void arm64_coder__1494(void** vars);
extern void arm64_coder__1495(void** vars);
extern void arm64_coder__1496(void** vars);
extern void arm64_coder__1497(void** vars);
extern void arm64_coder__1498(void** vars);
extern void arm64_coder__1499(void** vars);
#endif
#ifdef INSN_OPCODE_3c10
extern void arm64_coder__1500(void** vars);
extern void arm64_coder__1501(void** vars);
#endif
#ifdef INSN_OPCODE_3d00
extern void arm64_coder__1502(void** vars);
extern void arm64_coder__1503(void** vars);
extern void arm64_coder__1504(void** vars);
extern void arm64_coder__1505(void** vars);
extern void arm64_coder__1506(void** vars);
extern void arm64_coder__1507(void** vars);
extern void arm64_coder__1508(void** vars);
extern void arm64_coder__1509(void** vars);
extern void arm64_coder__1510(void** vars);
extern void arm64_coder__1511(void** vars);
extern void arm64_coder__1512(void** vars);
extern void arm64_coder__1513(void** vars);
extern void arm64_coder__1514(void** vars);
extern void arm64_coder__1515(void** vars);
extern void arm64_coder__1516(void** vars);
extern void arm64_coder__1517(void** vars);
extern void arm64_coder__1518(void** vars);
extern void arm64_coder__1519(void** vars);
extern void arm64_coder__1520(void** vars);
extern void arm64_coder__1521(void** vars);
extern void arm64_coder__1522(void** vars);
extern void arm64_coder__1523(void** vars);
extern void arm64_coder__1524(void** vars);
extern void arm64_coder__1525(void** vars);
extern void arm64_coder__1526(void** vars);
extern void arm64_coder__1527(void** vars);
extern void arm64_coder__1528(void** vars);
extern void arm64_coder__1529(void** vars);
extern void arm64_coder__1530(void** vars);
extern void arm64_coder__1531(void** vars);
extern void arm64_coder__1532(void** vars);
extern void arm64_coder__1533(void** vars);
extern void arm64_coder__1534(void** vars);
extern void arm64_coder__1535(void** vars);
extern void arm64_coder__1536(void** vars);
extern void arm64_coder__1537(void** vars);
extern void arm64_coder__1538(void** vars);
extern void arm64_coder__1539(void** vars);
extern void arm64_coder__1540(void** vars);
extern void arm64_coder__1541(void** vars);
extern void arm64_coder__1542(void** vars);
extern void arm64_coder__1543(void** vars);
extern void arm64_coder__1544(void** vars);
extern void arm64_coder__1545(void** vars);
extern void arm64_coder__1546(void** vars);
extern void arm64_coder__1547(void** vars);
extern void arm64_coder__1548(void** vars);
extern void arm64_coder__1549(void** vars);
extern void arm64_coder__1550(void** vars);
extern void arm64_coder__1551(void** vars);
extern void arm64_coder__1552(void** vars);
extern void arm64_coder__1553(void** vars);
extern void arm64_coder__1554(void** vars);
extern void arm64_coder__1555(void** vars);
extern void arm64_coder__1556(void** vars);
extern void arm64_coder__1557(void** vars);
extern void arm64_coder__1558(void** vars);
extern void arm64_coder__1559(void** vars);
extern void arm64_coder__1560(void** vars);
extern void arm64_coder__1561(void** vars);
extern void arm64_coder__1562(void** vars);
extern void arm64_coder__1563(void** vars);
extern void arm64_coder__1564(void** vars);
extern void arm64_coder__1565(void** vars);
extern void arm64_coder__1566(void** vars);
extern void arm64_coder__1567(void** vars);
extern void arm64_coder__1568(void** vars);
extern void arm64_coder__1569(void** vars);
extern void arm64_coder__1570(void** vars);
extern void arm64_coder__1571(void** vars);
#endif
#ifdef INSN_OPCODE_4a00
extern void arm64_coder__1572(void** vars);
extern void arm64_coder__1573(void** vars);
extern void arm64_coder__1574(void** vars);
extern void arm64_coder__1575(void** vars);
extern void arm64_coder__1576(void** vars);
extern void arm64_coder__1577(void** vars);
extern void arm64_coder__1578(void** vars);
extern void arm64_coder__1579(void** vars);
extern void arm64_coder__1580(void** vars);
extern void arm64_coder__1581(void** vars);
extern void arm64_coder__1582(void** vars);
extern void arm64_coder__1583(void** vars);
extern void arm64_coder__1584(void** vars);
extern void arm64_coder__1585(void** vars);
extern void arm64_coder__1586(void** vars);
extern void arm64_coder__1587(void** vars);
extern void arm64_coder__1588(void** vars);
extern void arm64_coder__1589(void** vars);
extern void arm64_coder__1590(void** vars);
extern void arm64_coder__1591(void** vars);
extern void arm64_coder__1592(void** vars);
extern void arm64_coder__1593(void** vars);
extern void arm64_coder__1594(void** vars);
extern void arm64_coder__1595(void** vars);
extern void arm64_coder__1596(void** vars);
extern void arm64_coder__1597(void** vars);
extern void arm64_coder__1598(void** vars);
extern void arm64_coder__1599(void** vars);
extern void arm64_coder__1600(void** vars);
extern void arm64_coder__1601(void** vars);
extern void arm64_coder__1602(void** vars);
extern void arm64_coder__1603(void** vars);
extern void arm64_coder__1604(void** vars);
extern void arm64_coder__1605(void** vars);
extern void arm64_coder__1606(void** vars);
extern void arm64_coder__1607(void** vars);
extern void arm64_coder__1608(void** vars);
extern void arm64_coder__1609(void** vars);
extern void arm64_coder__1610(void** vars);
extern void arm64_coder__1611(void** vars);
extern void arm64_coder__1612(void** vars);
extern void arm64_coder__1613(void** vars);
extern void arm64_coder__1614(void** vars);
extern void arm64_coder__1615(void** vars);
extern void arm64_coder__1616(void** vars);
extern void arm64_coder__1617(void** vars);
extern void arm64_coder__1618(void** vars);
extern void arm64_coder__1619(void** vars);
extern void arm64_coder__1620(void** vars);
extern void arm64_coder__1621(void** vars);
extern void arm64_coder__1622(void** vars);
#endif
#ifdef INSN_OPCODE_4b00
extern void arm64_coder__1623(void** vars);
extern void arm64_coder__1624(void** vars);
#endif
#ifdef INSN_OPCODE_5a00
extern void arm64_coder__1625(void** vars);
extern void arm64_coder__1626(void** vars);
#endif
#ifdef INSN_OPCODE_LIST_FIRST_2b00
extern void arm64_coder__1627(void** vars);
extern void arm64_coder__1628(void** vars);
extern void arm64_coder__1629(void** vars);
extern void arm64_coder__1630(void** vars);
extern void arm64_coder__1631(void** vars);
extern void arm64_coder__1632(void** vars);
extern void arm64_coder__1633(void** vars);
extern void arm64_coder__1634(void** vars);
extern void arm64_coder__1635(void** vars);
extern void arm64_coder__1636(void** vars);
extern void arm64_coder__1637(void** vars);
extern void arm64_coder__1638(void** vars);
extern void arm64_coder__1639(void** vars);
extern void arm64_coder__1640(void** vars);
extern void arm64_coder__1641(void** vars);
extern void arm64_coder__1642(void** vars);
extern void arm64_coder__1643(void** vars);
extern void arm64_coder__1644(void** vars);
extern void arm64_coder__1645(void** vars);
extern void arm64_coder__1646(void** vars);
extern void arm64_coder__1647(void** vars);
extern void arm64_coder__1648(void** vars);
extern void arm64_coder__1649(void** vars);
extern void arm64_coder__1650(void** vars);
extern void arm64_coder__1651(void** vars);
extern void arm64_coder__1652(void** vars);
extern void arm64_coder__1653(void** vars);
extern void arm64_coder__1654(void** vars);
extern void arm64_coder__1655(void** vars);
extern void arm64_coder__1656(void** vars);
extern void arm64_coder__1657(void** vars);
extern void arm64_coder__1658(void** vars);
extern void arm64_coder__1659(void** vars);
extern void arm64_coder__1660(void** vars);
extern void arm64_coder__1661(void** vars);
extern void arm64_coder__1662(void** vars);
extern void arm64_coder__1663(void** vars);
extern void arm64_coder__1664(void** vars);
extern void arm64_coder__1665(void** vars);
extern void arm64_coder__1666(void** vars);
extern void arm64_coder__1667(void** vars);
extern void arm64_coder__1668(void** vars);
extern void arm64_coder__1669(void** vars);
extern void arm64_coder__1670(void** vars);
extern void arm64_coder__1671(void** vars);
extern void arm64_coder__1672(void** vars);
extern void arm64_coder__1673(void** vars);
extern void arm64_coder__1674(void** vars);
extern void arm64_coder__1675(void** vars);
extern void arm64_coder__1676(void** vars);
extern void arm64_coder__1677(void** vars);
extern void arm64_coder__1678(void** vars);
extern void arm64_coder__1679(void** vars);
extern void arm64_coder__1680(void** vars);
extern void arm64_coder__1681(void** vars);
extern void arm64_coder__1682(void** vars);
extern void arm64_coder__1683(void** vars);
extern void arm64_coder__1684(void** vars);
extern void arm64_coder__1685(void** vars);
extern void arm64_coder__1686(void** vars);
extern void arm64_coder__1687(void** vars);
extern void arm64_coder__1688(void** vars);
extern void arm64_coder__1689(void** vars);
extern void arm64_coder__1690(void** vars);
extern void arm64_coder__1691(void** vars);
extern void arm64_coder__1692(void** vars);
extern void arm64_coder__1693(void** vars);
extern void arm64_coder__1694(void** vars);
extern void arm64_coder__1695(void** vars);
extern void arm64_coder__1696(void** vars);
extern void arm64_coder__1697(void** vars);
extern void arm64_coder__1698(void** vars);
extern void arm64_coder__1699(void** vars);
extern void arm64_coder__1700(void** vars);
extern void arm64_coder__1701(void** vars);
extern void arm64_coder__1702(void** vars);
extern void arm64_coder__1703(void** vars);
extern void arm64_coder__1704(void** vars);
extern void arm64_coder__1705(void** vars);
extern void arm64_coder__1706(void** vars);
extern void arm64_coder__1707(void** vars);
extern void arm64_coder__1708(void** vars);
extern void arm64_coder__1709(void** vars);
extern void arm64_coder__1710(void** vars);
extern void arm64_coder__1711(void** vars);
extern void arm64_coder__1712(void** vars);
extern void arm64_coder__1713(void** vars);
extern void arm64_coder__1714(void** vars);
extern void arm64_coder__1715(void** vars);
extern void arm64_coder__1716(void** vars);
extern void arm64_coder__1717(void** vars);
extern void arm64_coder__1718(void** vars);
extern void arm64_coder__1719(void** vars);
extern void arm64_coder__1720(void** vars);
extern void arm64_coder__1721(void** vars);
extern void arm64_coder__1722(void** vars);
extern void arm64_coder__1723(void** vars);
extern void arm64_coder__1724(void** vars);
extern void arm64_coder__1725(void** vars);
extern void arm64_coder__1726(void** vars);
extern void arm64_coder__1727(void** vars);
extern void arm64_coder__1728(void** vars);
extern void arm64_coder__1729(void** vars);
extern void arm64_coder__1730(void** vars);
extern void arm64_coder__1731(void** vars);
extern void arm64_coder__1732(void** vars);
extern void arm64_coder__1733(void** vars);
extern void arm64_coder__1734(void** vars);
extern void arm64_coder__1735(void** vars);
extern void arm64_coder__1736(void** vars);
extern void arm64_coder__1737(void** vars);
extern void arm64_coder__1738(void** vars);
extern void arm64_coder__1739(void** vars);
extern void arm64_coder__1740(void** vars);
#endif
#ifdef INSN_OPCODE_LIST_FIRST_2b01
extern void arm64_coder__1741(void** vars);
extern void arm64_coder__1742(void** vars);
extern void arm64_coder__1743(void** vars);
extern void arm64_coder__1744(void** vars);
extern void arm64_coder__1745(void** vars);
extern void arm64_coder__1746(void** vars);
extern void arm64_coder__1747(void** vars);
extern void arm64_coder__1748(void** vars);
extern void arm64_coder__1749(void** vars);
extern void arm64_coder__1750(void** vars);
extern void arm64_coder__1751(void** vars);
extern void arm64_coder__1752(void** vars);
extern void arm64_coder__1753(void** vars);
extern void arm64_coder__1754(void** vars);
extern void arm64_coder__1755(void** vars);
extern void arm64_coder__1756(void** vars);
extern void arm64_coder__1757(void** vars);
extern void arm64_coder__1758(void** vars);
extern void arm64_coder__1759(void** vars);
extern void arm64_coder__1760(void** vars);
extern void arm64_coder__1761(void** vars);
extern void arm64_coder__1762(void** vars);
extern void arm64_coder__1763(void** vars);
extern void arm64_coder__1764(void** vars);
extern void arm64_coder__1765(void** vars);
extern void arm64_coder__1766(void** vars);
extern void arm64_coder__1767(void** vars);
extern void arm64_coder__1768(void** vars);
extern void arm64_coder__1769(void** vars);
extern void arm64_coder__1770(void** vars);
extern void arm64_coder__1771(void** vars);
extern void arm64_coder__1772(void** vars);
extern void arm64_coder__1773(void** vars);
extern void arm64_coder__1774(void** vars);
extern void arm64_coder__1775(void** vars);
extern void arm64_coder__1776(void** vars);
extern void arm64_coder__1777(void** vars);
extern void arm64_coder__1778(void** vars);
extern void arm64_coder__1779(void** vars);
extern void arm64_coder__1780(void** vars);
extern void arm64_coder__1781(void** vars);
extern void arm64_coder__1782(void** vars);
extern void arm64_coder__1783(void** vars);
#endif
#ifdef INSN_OPCODE_LIST_FIRST_2b02
extern void arm64_coder__1784(void** vars);
extern void arm64_coder__1785(void** vars);
extern void arm64_coder__1786(void** vars);
extern void arm64_coder__1787(void** vars);
extern void arm64_coder__1788(void** vars);
extern void arm64_coder__1789(void** vars);
extern void arm64_coder__1790(void** vars);
extern void arm64_coder__1791(void** vars);
extern void arm64_coder__1792(void** vars);
extern void arm64_coder__1793(void** vars);
extern void arm64_coder__1794(void** vars);
extern void arm64_coder__1795(void** vars);
extern void arm64_coder__1796(void** vars);
extern void arm64_coder__1797(void** vars);
extern void arm64_coder__1798(void** vars);
extern void arm64_coder__1799(void** vars);
extern void arm64_coder__1800(void** vars);
extern void arm64_coder__1801(void** vars);
extern void arm64_coder__1802(void** vars);
extern void arm64_coder__1803(void** vars);
extern void arm64_coder__1804(void** vars);
extern void arm64_coder__1805(void** vars);
extern void arm64_coder__1806(void** vars);
extern void arm64_coder__1807(void** vars);
extern void arm64_coder__1808(void** vars);
extern void arm64_coder__1809(void** vars);
extern void arm64_coder__1810(void** vars);
extern void arm64_coder__1811(void** vars);
extern void arm64_coder__1812(void** vars);
extern void arm64_coder__1813(void** vars);
extern void arm64_coder__1814(void** vars);
extern void arm64_coder__1815(void** vars);
#endif
#ifdef INSN_OPCODE_LIST_FIRST_2b11
extern void arm64_coder__1816(void** vars);
extern void arm64_coder__1817(void** vars);
extern void arm64_coder__1818(void** vars);
extern void arm64_coder__1819(void** vars);
extern void arm64_coder__1820(void** vars);
extern void arm64_coder__1821(void** vars);
extern void arm64_coder__1822(void** vars);
extern void arm64_coder__1823(void** vars);
extern void arm64_coder__1824(void** vars);
#endif
#ifdef OPRN_IMMEDIATE_0201
void *arm64_coder__1825(void** vars,int var0);
void *arm64_coder__1826(void** vars,int var0);
void *arm64_coder__1827(void** vars,int var0);
void *arm64_coder__1828(void** vars,int var0);
void *arm64_coder__1829(void** vars,int var0);
void *arm64_coder__1830(void** vars,int var0);
void *arm64_coder__1831(void** vars,int var0);
void *arm64_coder__1832(void** vars,int var0);
void *arm64_coder__1833(void** vars,int var0);
void *arm64_coder__1834(void** vars,int var0);
void *arm64_coder__1835(void** vars,int var0);
void *arm64_coder__1836(void** vars,int var0);
void *arm64_coder__1837(void** vars,int var0);
#endif
#ifdef OPRN_IMMEDIATE_0300
void *arm64_coder__1838();
void *arm64_coder__1839();
void *arm64_coder__1840();
void *arm64_coder__1841();
#endif
#ifdef OPRN_IMMEDIATE_1200
void *arm64_coder__1842(void** vars);
void *arm64_coder__1843(void** vars);
void *arm64_coder__1844(void** vars);
void *arm64_coder__1845(void** vars);
void *arm64_coder__1846(void** vars);
void *arm64_coder__1847(void** vars);
void *arm64_coder__1848(void** vars);
void *arm64_coder__1849(void** vars);
void *arm64_coder__1850(void** vars);
void *arm64_coder__1851(void** vars);
void *arm64_coder__1852(void** vars);
void *arm64_coder__1853(void** vars);
void *arm64_coder__1854(void** vars);
#endif
#ifdef OPRN_IMMEDIATE_1201
void *arm64_coder__1855(void** vars,int var0);
void *arm64_coder__1856(void** vars,int var0);
void *arm64_coder__1857(void** vars,int var0);
void *arm64_coder__1858(void** vars,int var0);
#endif
#ifdef OPRN_IMMEDIATE_2200
void *arm64_coder__1859(void** vars);
void *arm64_coder__1860(void** vars);
void *arm64_coder__1861(void** vars);
void *arm64_coder__1862(void** vars);
void *arm64_coder__1863(void** vars);
#endif
#ifdef OPRN_IMMEDIATE_SYSTEM_0201
void *arm64_coder__1864(void** vars,int var0);
void *arm64_coder__1865(void** vars,int var0);
#endif
#ifdef OPRN_MEMORY_0201
void *arm64_coder__1866(void** vars,int var0);
void *arm64_coder__1867(void** vars,int var0);
#endif
#ifdef OPRN_MEMORY_DWORD_REGISTER_INDEX_0202
void *arm64_coder__1868(void** vars,int var0,int var1);
#endif
#ifdef OPRN_MEMORY_DWORD_REGISTER_INDEX_1202
void *arm64_coder__1869(void** vars,int var0,int var1);
void *arm64_coder__1870(void** vars,int var0,int var1);
void *arm64_coder__1871(void** vars,int var0,int var1);
void *arm64_coder__1872(void** vars,int var0,int var1);
void *arm64_coder__1873(void** vars,int var0,int var1);
void *arm64_coder__1874(void** vars,int var0,int var1);
void *arm64_coder__1875(void** vars,int var0,int var1);
void *arm64_coder__1876(void** vars,int var0,int var1);
void *arm64_coder__1877(void** vars,int var0,int var1);
void *arm64_coder__1878(void** vars,int var0,int var1);
void *arm64_coder__1879(void** vars,int var0,int var1);
void *arm64_coder__1880(void** vars,int var0,int var1);
void *arm64_coder__1881(void** vars,int var0,int var1);
void *arm64_coder__1882(void** vars,int var0,int var1);
void *arm64_coder__1883(void** vars,int var0,int var1);
void *arm64_coder__1884(void** vars,int var0,int var1);
void *arm64_coder__1885(void** vars,int var0,int var1);
void *arm64_coder__1886(void** vars,int var0,int var1);
void *arm64_coder__1887(void** vars,int var0,int var1);
void *arm64_coder__1888(void** vars,int var0,int var1);
#endif
#ifdef OPRN_MEMORY_DWORD_REGISTER_POST_INDEX_0211
void *arm64_coder__1889(void** vars,int var0,int var1);
void *arm64_coder__1890(void** vars,int var0,int var1);
#endif
#ifdef OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202
void *arm64_coder__1891(void** vars,int var0,int var1);
void *arm64_coder__1892(void** vars,int var0,int var1);
#endif
#ifdef OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_1201
void *arm64_coder__1893(void** vars,int var0);
void *arm64_coder__1894(void** vars,int var0);
void *arm64_coder__1895(void** vars,int var0);
void *arm64_coder__1896(void** vars,int var0);
void *arm64_coder__1897(void** vars,int var0);
void *arm64_coder__1898(void** vars,int var0);
#endif
#ifdef OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_WRITEBACK_0202
void *arm64_coder__1899(void** vars,int var0,int var1);
void *arm64_coder__1900(void** vars,int var0,int var1);
#endif
#ifdef OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_WRITEBACK_1201
void *arm64_coder__1901(void** vars,int var0);
void *arm64_coder__1902(void** vars,int var0);
void *arm64_coder__1903(void** vars,int var0);
void *arm64_coder__1904(void** vars,int var0);
void *arm64_coder__1905(void** vars,int var0);
void *arm64_coder__1906(void** vars,int var0);
#endif
#ifdef OPRN_MEMORY_SIGNED_IMMEDIATE_POST_INDEX_0202
void *arm64_coder__1907(void** vars,int var0,int var1);
void *arm64_coder__1908(void** vars,int var0,int var1);
#endif
#ifdef OPRN_MEMORY_SIGNED_IMMEDIATE_POST_INDEX_1201
void *arm64_coder__1909(void** vars,int var0);
void *arm64_coder__1910(void** vars,int var0);
void *arm64_coder__1911(void** vars,int var0);
void *arm64_coder__1912(void** vars,int var0);
void *arm64_coder__1913(void** vars,int var0);
void *arm64_coder__1914(void** vars,int var0);
#endif
#ifdef OPRN_MEMORY_SWORD_REGISTER_INDEX_1202
void *arm64_coder__1915(void** vars,int var0,int var1);
void *arm64_coder__1916(void** vars,int var0,int var1);
void *arm64_coder__1917(void** vars,int var0,int var1);
void *arm64_coder__1918(void** vars,int var0,int var1);
void *arm64_coder__1919(void** vars,int var0,int var1);
void *arm64_coder__1920(void** vars,int var0,int var1);
void *arm64_coder__1921(void** vars,int var0,int var1);
void *arm64_coder__1922(void** vars,int var0,int var1);
void *arm64_coder__1923(void** vars,int var0,int var1);
void *arm64_coder__1924(void** vars,int var0,int var1);
#endif
#ifdef OPRN_MEMORY_UNSIGNED_IMMEDIATE_INDEX_0202
void *arm64_coder__1925(void** vars,int var0,int var1);
void *arm64_coder__1926(void** vars,int var0,int var1);
#endif
#ifdef OPRN_MEMORY_UNSIGNED_IMMEDIATE_INDEX_1201
void *arm64_coder__1927(void** vars,int var0);
void *arm64_coder__1928(void** vars,int var0);
void *arm64_coder__1929(void** vars,int var0);
void *arm64_coder__1930(void** vars,int var0);
void *arm64_coder__1931(void** vars,int var0);
void *arm64_coder__1932(void** vars,int var0);
void *arm64_coder__1933(void** vars,int var0);
void *arm64_coder__1934(void** vars,int var0);
#endif
#ifdef OPRN_MEMORY_UNSIGNED_IMMEDIATE_POST_INDEX_0301
void *arm64_coder__1935(void** vars,int var0);
void *arm64_coder__1936(void** vars,int var0);
void *arm64_coder__1937(void** vars,int var0);
void *arm64_coder__1938(void** vars,int var0);
void *arm64_coder__1939(void** vars,int var0);
void *arm64_coder__1940(void** vars,int var0);
void *arm64_coder__1941(void** vars,int var0);
void *arm64_coder__1942(void** vars,int var0);
void *arm64_coder__1943(void** vars,int var0);
void *arm64_coder__1944(void** vars,int var0);
void *arm64_coder__1945(void** vars,int var0);
void *arm64_coder__1946(void** vars,int var0);
void *arm64_coder__1947(void** vars,int var0);
void *arm64_coder__1948(void** vars,int var0);
void *arm64_coder__1949(void** vars,int var0);
void *arm64_coder__1950(void** vars,int var0);
void *arm64_coder__1951(void** vars,int var0);
void *arm64_coder__1952(void** vars,int var0);
void *arm64_coder__1953(void** vars,int var0);
void *arm64_coder__1954(void** vars,int var0);
void *arm64_coder__1955(void** vars,int var0);
void *arm64_coder__1956(void** vars,int var0);
#endif
#ifdef OPRN_MEMORY_UNSIGNED_IMMEDIATE_POST_INDEX_1201
void *arm64_coder__1957(void** vars,int var0);
void *arm64_coder__1958(void** vars,int var0);
void *arm64_coder__1959(void** vars,int var0);
void *arm64_coder__1960(void** vars,int var0);
void *arm64_coder__1961(void** vars,int var0);
void *arm64_coder__1962(void** vars,int var0);
void *arm64_coder__1963(void** vars,int var0);
void *arm64_coder__1964(void** vars,int var0);
#endif
#ifdef OPRN_POINTER_1200
void *arm64_coder__1965(void** vars);
void *arm64_coder__1966(void** vars);
void *arm64_coder__1967(void** vars);
void *arm64_coder__1968(void** vars);
void *arm64_coder__1969(void** vars);
void *arm64_coder__1970(void** vars);
void *arm64_coder__1971(void** vars);
#endif
#ifdef OPRN_REGISTER_DWORD_OR_STACK_0201
void *arm64_coder__1972(void** vars,int var0);
void *arm64_coder__1973(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_DWORD_OR_ZERO_0201
void *arm64_coder__1974(void** vars,int var0);
void *arm64_coder__1975(void** vars,int var0);
void *arm64_coder__1976(void** vars,int var0);
void *arm64_coder__1977(void** vars,int var0);
void *arm64_coder__1978(void** vars,int var0);
void *arm64_coder__1979(void** vars,int var0);
void *arm64_coder__1980(void** vars,int var0);
void *arm64_coder__1981(void** vars,int var0);
void *arm64_coder__1982(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_DWORD_OR_ZERO_0210
void *arm64_coder__1983(void** vars,int var0);
void *arm64_coder__1984(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_DWORD_OR_ZERO_1201
void *arm64_coder__1985(void** vars,int var0);
void *arm64_coder__1986(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202
void *arm64_coder__1987(void** vars,int var0,int var1);
void *arm64_coder__1988(void** vars,int var0,int var1);
void *arm64_coder__1989(void** vars,int var0,int var1);
void *arm64_coder__1990(void** vars,int var0,int var1);
void *arm64_coder__1991(void** vars,int var0,int var1);
void *arm64_coder__1992(void** vars,int var0,int var1);
void *arm64_coder__1993(void** vars,int var0,int var1);
void *arm64_coder__1994(void** vars,int var0,int var1);
void *arm64_coder__1995(void** vars,int var0,int var1);
void *arm64_coder__1996(void** vars,int var0,int var1);
void *arm64_coder__1997(void** vars,int var0,int var1);
void *arm64_coder__1998(void** vars,int var0,int var1);
void *arm64_coder__1999(void** vars,int var0,int var1);
#endif
#ifdef OPRN_REGISTER_INDEXED_SIMD_VECTOR_0301
void *arm64_coder__2000(void** vars,int var0);
void *arm64_coder__2001(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_INDEXED_SIMD_VECTOR_1201
void *arm64_coder__2002(void** vars,int var0);
void *arm64_coder__2003(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_LIST_FOUR_INDEXED_VECTOR_0202
void *arm64_coder__2004(void** vars,int var0,int var1);
void *arm64_coder__2005(void** vars,int var0,int var1);
#endif
#ifdef OPRN_REGISTER_LIST_FOUR_INDEXED_VECTOR_1201
void *arm64_coder__2006(void** vars,int var0);
void *arm64_coder__2007(void** vars,int var0);
void *arm64_coder__2008(void** vars,int var0);
void *arm64_coder__2009(void** vars,int var0);
void *arm64_coder__2010(void** vars,int var0);
void *arm64_coder__2011(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_LIST_FOUR_VECTOR_0201
void *arm64_coder__2012(void** vars,int var0);
void *arm64_coder__2013(void** vars,int var0);
void *arm64_coder__2014(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_LIST_ONE_INDEXED_VECTOR_0202
void *arm64_coder__2015(void** vars,int var0,int var1);
void *arm64_coder__2016(void** vars,int var0,int var1);
#endif
#ifdef OPRN_REGISTER_LIST_ONE_INDEXED_VECTOR_1201
void *arm64_coder__2017(void** vars,int var0);
void *arm64_coder__2018(void** vars,int var0);
void *arm64_coder__2019(void** vars,int var0);
void *arm64_coder__2020(void** vars,int var0);
void *arm64_coder__2021(void** vars,int var0);
void *arm64_coder__2022(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_LIST_ONE_VECTOR_0201
void *arm64_coder__2023(void** vars,int var0);
void *arm64_coder__2024(void** vars,int var0);
void *arm64_coder__2025(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_LIST_THREE_INDEXED_VECTOR_0202
void *arm64_coder__2026(void** vars,int var0,int var1);
void *arm64_coder__2027(void** vars,int var0,int var1);
#endif
#ifdef OPRN_REGISTER_LIST_THREE_INDEXED_VECTOR_1201
void *arm64_coder__2028(void** vars,int var0);
void *arm64_coder__2029(void** vars,int var0);
void *arm64_coder__2030(void** vars,int var0);
void *arm64_coder__2031(void** vars,int var0);
void *arm64_coder__2032(void** vars,int var0);
void *arm64_coder__2033(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_LIST_THREE_VECTOR_0201
void *arm64_coder__2034(void** vars,int var0);
void *arm64_coder__2035(void** vars,int var0);
void *arm64_coder__2036(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_LIST_TWO_INDEXED_VECTOR_0202
void *arm64_coder__2037(void** vars,int var0,int var1);
void *arm64_coder__2038(void** vars,int var0,int var1);
#endif
#ifdef OPRN_REGISTER_LIST_TWO_INDEXED_VECTOR_1201
void *arm64_coder__2039(void** vars,int var0);
void *arm64_coder__2040(void** vars,int var0);
void *arm64_coder__2041(void** vars,int var0);
void *arm64_coder__2042(void** vars,int var0);
void *arm64_coder__2043(void** vars,int var0);
void *arm64_coder__2044(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_LIST_TWO_VECTOR_0201
void *arm64_coder__2045(void** vars,int var0);
void *arm64_coder__2046(void** vars,int var0);
void *arm64_coder__2047(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_SIMD_SCALAR_BYTE_0201
void *arm64_coder__2048(void** vars,int var0);
void *arm64_coder__2049(void** vars,int var0);
void *arm64_coder__2050(void** vars,int var0);
void *arm64_coder__2051(void** vars,int var0);
void *arm64_coder__2052(void** vars,int var0);
void *arm64_coder__2053(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_SIMD_SCALAR_DWORD_0201
void *arm64_coder__2054(void** vars,int var0);
void *arm64_coder__2055(void** vars,int var0);
void *arm64_coder__2056(void** vars,int var0);
void *arm64_coder__2057(void** vars,int var0);
void *arm64_coder__2058(void** vars,int var0);
void *arm64_coder__2059(void** vars,int var0);
void *arm64_coder__2060(void** vars,int var0);
void *arm64_coder__2061(void** vars,int var0);
void *arm64_coder__2062(void** vars,int var0);
void *arm64_coder__2063(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_SIMD_SCALAR_HWORD_0201
void *arm64_coder__2064(void** vars,int var0);
void *arm64_coder__2065(void** vars,int var0);
void *arm64_coder__2066(void** vars,int var0);
void *arm64_coder__2067(void** vars,int var0);
void *arm64_coder__2068(void** vars,int var0);
void *arm64_coder__2069(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_SIMD_SCALAR_QWORD_0201
void *arm64_coder__2070(void** vars,int var0);
void *arm64_coder__2071(void** vars,int var0);
void *arm64_coder__2072(void** vars,int var0);
void *arm64_coder__2073(void** vars,int var0);
void *arm64_coder__2074(void** vars,int var0);
void *arm64_coder__2075(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_SIMD_SCALAR_SWORD_0201
void *arm64_coder__2076(void** vars,int var0);
void *arm64_coder__2077(void** vars,int var0);
void *arm64_coder__2078(void** vars,int var0);
void *arm64_coder__2079(void** vars,int var0);
void *arm64_coder__2080(void** vars,int var0);
void *arm64_coder__2081(void** vars,int var0);
void *arm64_coder__2082(void** vars,int var0);
void *arm64_coder__2083(void** vars,int var0);
void *arm64_coder__2084(void** vars,int var0);
void *arm64_coder__2085(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_SIMD_VECTOR_0201
void *arm64_coder__2086(void** vars,int var0);
void *arm64_coder__2087(void** vars,int var0);
void *arm64_coder__2088(void** vars,int var0);
void *arm64_coder__2089(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_SWORD_OR_STACK_0201
void *arm64_coder__2090(void** vars,int var0);
void *arm64_coder__2091(void** vars,int var0);
void *arm64_coder__2092(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_SWORD_OR_ZERO_0201
void *arm64_coder__2093(void** vars,int var0);
void *arm64_coder__2094(void** vars,int var0);
void *arm64_coder__2095(void** vars,int var0);
void *arm64_coder__2096(void** vars,int var0);
void *arm64_coder__2097(void** vars,int var0);
void *arm64_coder__2098(void** vars,int var0);
void *arm64_coder__2099(void** vars,int var0);
void *arm64_coder__2100(void** vars,int var0);
void *arm64_coder__2101(void** vars,int var0);
void *arm64_coder__2102(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_SWORD_OR_ZERO_1201
void *arm64_coder__2103(void** vars,int var0);
void *arm64_coder__2104(void** vars,int var0);
void *arm64_coder__2105(void** vars,int var0);
#endif
#ifdef OPRN_REGISTER_SYSTEM_0300
void *arm64_coder__2106();
void *arm64_coder__2107();
void *arm64_coder__2108();
#endif
#ifdef OPRN_REGISTER_SYSTEM_1200
void *arm64_coder__2109(void** vars);
void *arm64_coder__2110(void** vars);
#endif
#endif /*ARM64_FCT_H_*/
