/*
   Copyright (C) 2004 - 2018 Université de Versailles Saint-Quentin-en-Yvelines (UVSQ)

   This file is part of MAQAO.

  MAQAO is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public License
   as published by the Free Software Foundation; either version 3
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */


/**
* \file arm64_revfct_5.c
* \brief This file contains the bodies of functions for reversing the semantic actions
* \warning This file has been automatically generated by MINJAG from file arm64_6bf96bbfcca0afd1af78d50ba75869a8.bdf and should not be modified
* */
#include <stdlib.h>
#include "arm64_arch.h"
#include "arm64_sym.h"
#include "asmblutils.h"
#include "arm64_revmacros.h"
#include "arm64_revfct.h"
#ifdef INSN_OPCODE_2b00
int arm64_encoder_23c(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0110111001100001100010 RN RD  => INSN_OPCODE(I_FRINTA ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_64b DATASZ_64b DATASZ_128b RW2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_827, I_FRINTA, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_64b, DATASZ_64b, DATASZ_128b, RW2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_23d(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0110111011100001100110 RN RD  => INSN_OPCODE(I_FRINTI ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_64b DATASZ_64b DATASZ_128b RW2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_827, I_FRINTI, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_64b, DATASZ_64b, DATASZ_128b, RW2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_23e(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0100111001100001100110 RN RD  => INSN_OPCODE(I_FRINTM ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_64b DATASZ_64b DATASZ_128b RW2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_827, I_FRINTM, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_64b, DATASZ_64b, DATASZ_128b, RW2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_23f(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0100111001100001100010 RN RD  => INSN_OPCODE(I_FRINTN ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_64b DATASZ_64b DATASZ_128b RW2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_827, I_FRINTN, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_64b, DATASZ_64b, DATASZ_128b, RW2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_240(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0100111011100001100010 RN RD  => INSN_OPCODE(I_FRINTP ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_64b DATASZ_64b DATASZ_128b RW2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_827, I_FRINTP, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_64b, DATASZ_64b, DATASZ_128b, RW2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_241(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0110111001100001100110 RN RD  => INSN_OPCODE(I_FRINTX ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_64b DATASZ_64b DATASZ_128b RW2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_827, I_FRINTX, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_64b, DATASZ_64b, DATASZ_128b, RW2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_242(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0100111011100001100110 RN RD  => INSN_OPCODE(I_FRINTZ ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_64b DATASZ_64b DATASZ_128b RW2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_827, I_FRINTZ, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_64b, DATASZ_64b, DATASZ_128b, RW2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_243(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0110111011100001110110 RN RD  => INSN_OPCODE(I_FRSQRTE ISET_ARM64 FM_SQRT A_NA S_SIMD T_FP T_FP DATASZ_64b DATASZ_64b DATASZ_128b RW2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_827, I_FRSQRTE, ISET_ARM64, FM_SQRT, A_NA, S_SIMD, T_FP, T_FP, DATASZ_64b, DATASZ_64b, DATASZ_128b, RW2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_244(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0110111011100001111110 RN RD  => INSN_OPCODE(I_FSQRT ISET_ARM64 FM_SQRT A_NA S_SIMD T_FP T_FP DATASZ_64b DATASZ_64b DATASZ_128b RW2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_827, I_FSQRT, ISET_ARM64, FM_SQRT, A_NA, S_SIMD, T_FP, T_FP, DATASZ_64b, DATASZ_64b, DATASZ_128b, RW2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_245(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_802 = NULL,*mcr_7c3 = NULL;
	/*template:	01011110000 IMM4 1000001 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b RB )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_802, mcr_7c3, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b, RB);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_802, DATASZ_BYTE, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c3, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM4 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_246(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_812 = NULL,*mcr_7c4 = NULL;
	/*template:	01011110000 IMM3 10000001 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b RH )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_812, mcr_7c4, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b, RH);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_812, DATASZ_HWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c4, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM3 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_247(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81e = NULL,*mcr_7c5 = NULL;
	/*template:	01011110000 IMM2 100000001 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b RS )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_81e, mcr_7c5, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b, RS);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81e, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c5, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM2 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_248(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_808 = NULL,*mcr_7c6 = NULL;
	/*template:	01011110000 IMM1 1000000001 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b RD )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_808, mcr_7c6, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b, RD);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_808, DATASZ_DWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c6, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM1 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_249(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7c8 = NULL,*mcr_7c9 = NULL;
	/*template:	01101110000 IMM4 10 IMM4_2 1 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b RWB )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_7c8, mcr_7c9, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b, RWB);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c8, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER], vals[BDFVar__IMM4 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c9, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM4_2 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_24a(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7ca = NULL,*mcr_7cb = NULL;
	/*template:	01101110000 IMM3 100 IMM3_2 01 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b RWH )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_7ca, mcr_7cb, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b, RWH);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7ca, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER], vals[BDFVar__IMM3 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7cb, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM3_2 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_24b(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7cc = NULL,*mcr_7cd = NULL;
	/*template:	01101110000 IMM2 1000 IMM2_2 001 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b RWS )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_7cc, mcr_7cd, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b, RWS);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7cc, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER], vals[BDFVar__IMM2 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7cd, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM2_2 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_24c(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7ce = NULL,*mcr_7cf = NULL;
	/*template:	01101110000 IMM1 10000 IMM1_2 0001 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b RWD )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_7ce, mcr_7cf, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b, RWD);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7ce, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER], vals[BDFVar__IMM1 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7cf, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM1_2 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_24d(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7c8 = NULL,*mcr_82b = NULL;
	/*template:	01001110000 IMM4 1000111 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b RWB )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_7c8, mcr_82b, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b, RWB);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c8, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER], vals[BDFVar__IMM4 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_STACK_0201(found, mcr_82b, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_24e(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7ca = NULL,*mcr_82b = NULL;
	/*template:	01001110000 IMM3 10000111 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b RWH )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_7ca, mcr_82b, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b, RWH);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7ca, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER], vals[BDFVar__IMM3 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_STACK_0201(found, mcr_82b, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_24f(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7cc = NULL,*mcr_82b = NULL;
	/*template:	01001110000 IMM2 100000111 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b RWS )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_7cc, mcr_82b, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b, RWS);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7cc, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER], vals[BDFVar__IMM2 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_STACK_0201(found, mcr_82b, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_250(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7ce = NULL,*mcr_7b5 = NULL;
	/*template:	01001110000 IMM1 1000000111 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b RWD )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_7ce, mcr_7b5, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b, RWD);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7ce, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER], vals[BDFVar__IMM1 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_STACK_0201(found, mcr_7b5, DATASZ_DWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_251(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_82a = NULL,*mcr_7c5 = NULL;
	/*template:	00001110000 IMM2 100001111 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SIMD T_UINT T_UINT DATASZ_32b DATASZ_32b DATASZ_32b RS )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_82a, mcr_7c5, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UINT, T_UINT, DATASZ_32b, DATASZ_32b, DATASZ_32b, RS);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_STACK_0201(found, mcr_82a, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c5, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM2 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_252(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7b4 = NULL,*mcr_7c6 = NULL;
	/*template:	01001110000 IMM1 1000001111 RN RD  => INSN_OPCODE(I_MOV ISET_ARM64 FM_MOV A_NA S_SIMD T_UINT T_UINT DATASZ_64b DATASZ_64b DATASZ_64b RD )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_7b4, mcr_7c6, I_MOV, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UINT, T_UINT, DATASZ_64b, DATASZ_64b, DATASZ_64b, RD);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_STACK_0201(found, mcr_7b4, DATASZ_DWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c6, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM1 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_253(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_73c = NULL,*mcr_ffffffef = NULL,*mcr_ffffffc6 = NULL,*mcr_ffffffc9 = NULL,*mcr_ffffffc5 = NULL,*mcr_ffffffc4 = NULL,*mcr_ffffffc3 = NULL,*mcr_ffffffc2 = NULL,*mcr_ffffffc1 = NULL;
	/*template:	0110111100000 A B C 111001 D E F G H RD  => INSN_OPCODE(I_MOVI ISET_ARM64 FM_MOV A_NA S_SIMD T_INT T_INT DATASZ_64b DATASZ_64b DATASZ_64b W2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_73c, I_MOVI, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_INT, T_INT, DATASZ_64b, DATASZ_64b, DATASZ_64b, W2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_IMMEDIATE_1200(found, mcr_73c, mcr_ffffffef, DATASZ_64b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_7101(found, mcr_ffffffef, mcr_ffffffc6, mcr_ffffffc9, mcr_ffffffc5, mcr_ffffffc4, mcr_ffffffc3, mcr_ffffffc2, mcr_ffffffc1, DATASZ_UNDEF, vals[BDFVar__H - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffc6, DATASZ_UNDEF, SEVEN, vals[BDFVar__A - BDFVar__VARNUMBER]);}
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffc9, DATASZ_UNDEF, SEVEN, vals[BDFVar__B - BDFVar__VARNUMBER]);}
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffc5, DATASZ_UNDEF, SEVEN, vals[BDFVar__C - BDFVar__VARNUMBER]);}
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffc4, DATASZ_UNDEF, SEVEN, vals[BDFVar__D - BDFVar__VARNUMBER]);}
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffc3, DATASZ_UNDEF, SEVEN, vals[BDFVar__E - BDFVar__VARNUMBER]);}
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffc2, DATASZ_UNDEF, SEVEN, vals[BDFVar__F - BDFVar__VARNUMBER]);}
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffc1, DATASZ_UNDEF, SEVEN, vals[BDFVar__G - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_254(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0010111011100000101110 RN RD  => INSN_OPCODE(I_NEG ISET_ARM64 FM_NEG A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_128b RW2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_827, I_NEG, ISET_ARM64, FM_NEG, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_128b, RW2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_255(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_808 = NULL,*mcr_827 = NULL;
	/*template:	0100111010110000001110 RN RD  => INSN_OPCODE(I_SADDLV ISET_ARM64 FM_ADD A_NA S_SIMD T_SINT T_SINT DATASZ_64b DATASZ_32b DATASZ_128b R4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_808, mcr_827, I_SADDLV, ISET_ARM64, FM_ADD, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_64b, DATASZ_32b, DATASZ_128b, R4S);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_808, DATASZ_DWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_256(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0100111001100001110110 RN RD  => INSN_OPCODE(I_SCVTF ISET_ARM64 FM_CVT A_NA S_SIMD T_FP T_SINT DATASZ_64b DATASZ_64b DATASZ_128b RW2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_827, I_SCVTF, ISET_ARM64, FM_CVT, A_NA, S_SIMD, T_FP, T_SINT, DATASZ_64b, DATASZ_64b, DATASZ_128b, RW2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_257(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_829 = NULL,*mcr_827 = NULL;
	/*template:	0101111000101000000110 RN RD  => INSN_OPCODE(I_SHA1SU1 ISET_ARM64 FM_CRYPTO A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_128b RW4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_829, mcr_827, I_SHA1SU1, ISET_ARM64, FM_CRYPTO, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_128b, RW4S);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_829, DATASZ_QWORD, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_258(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_829 = NULL,*mcr_827 = NULL;
	/*template:	0101111000101000001010 RN RD  => INSN_OPCODE(I_SHA256SU0 ISET_ARM64 FM_CRYPTO A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_128b RW4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_829, mcr_827, I_SHA256SU0, ISET_ARM64, FM_CRYPTO, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_128b, RW4S);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_829, DATASZ_QWORD, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_259(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81e = NULL,*mcr_827 = NULL;
	/*template:	0100111010110000101010 RN RD  => INSN_OPCODE(I_SMAXV ISET_ARM64 FM_MAX A_NA S_SIMD T_SINT T_SINT DATASZ_32b DATASZ_32b DATASZ_128b R4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_81e, mcr_827, I_SMAXV, ISET_ARM64, FM_MAX, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_32b, DATASZ_32b, DATASZ_128b, R4S);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81e, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_25a(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81e = NULL,*mcr_827 = NULL;
	/*template:	0100111010110001101010 RN RD  => INSN_OPCODE(I_SMINV ISET_ARM64 FM_MIN A_NA S_SIMD T_SINT T_SINT DATASZ_32b DATASZ_32b DATASZ_128b R4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_81e, mcr_827, I_SMINV, ISET_ARM64, FM_MIN, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_32b, DATASZ_32b, DATASZ_128b, R4S);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81e, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_25b(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_82a = NULL,*mcr_7c3 = NULL;
	/*template:	00001110000 IMM4 1001011 RN RD  => INSN_OPCODE(I_SMOV ISET_ARM64 FM_MOV A_NA S_SCALAR T_SINT T_SINT DATASZ_32b DATASZ_8b DATASZ_8b RB )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_82a, mcr_7c3, I_SMOV, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_SINT, T_SINT, DATASZ_32b, DATASZ_8b, DATASZ_8b, RB);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_STACK_0201(found, mcr_82a, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c3, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM4 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_25c(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_82a = NULL,*mcr_7c4 = NULL;
	/*template:	00001110000 IMM3 10001011 RN RD  => INSN_OPCODE(I_SMOV ISET_ARM64 FM_MOV A_NA S_SCALAR T_SINT T_SINT DATASZ_32b DATASZ_16b DATASZ_16b RH )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_82a, mcr_7c4, I_SMOV, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_SINT, T_SINT, DATASZ_32b, DATASZ_16b, DATASZ_16b, RH);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_STACK_0201(found, mcr_82a, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c4, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM3 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_25d(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7b4 = NULL,*mcr_7c3 = NULL;
	/*template:	01001110000 IMM4 1001011 RN RD  => INSN_OPCODE(I_SMOV ISET_ARM64 FM_MOV A_NA S_SCALAR T_SINT T_SINT DATASZ_64b DATASZ_8b DATASZ_8b RB )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_7b4, mcr_7c3, I_SMOV, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_SINT, T_SINT, DATASZ_64b, DATASZ_8b, DATASZ_8b, RB);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_STACK_0201(found, mcr_7b4, DATASZ_DWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c3, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM4 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_25e(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7b4 = NULL,*mcr_7c4 = NULL;
	/*template:	01001110000 IMM3 10001011 RN RD  => INSN_OPCODE(I_SMOV ISET_ARM64 FM_MOV A_NA S_SCALAR T_SINT T_SINT DATASZ_64b DATASZ_16b DATASZ_16b RH )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_7b4, mcr_7c4, I_SMOV, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_SINT, T_SINT, DATASZ_64b, DATASZ_16b, DATASZ_16b, RH);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_STACK_0201(found, mcr_7b4, DATASZ_DWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c4, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM3 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_25f(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7b4 = NULL,*mcr_7c5 = NULL;
	/*template:	01001110000 IMM2 100001011 RN RD  => INSN_OPCODE(I_SMOV ISET_ARM64 FM_MOV A_NA S_SCALAR T_SINT T_SINT DATASZ_64b DATASZ_32b DATASZ_32b RS )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_7b4, mcr_7c5, I_SMOV, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_SINT, T_SINT, DATASZ_64b, DATASZ_32b, DATASZ_32b, RS);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_STACK_0201(found, mcr_7b4, DATASZ_DWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_INDEXED_SIMD_VECTOR_0202(found, mcr_7c5, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM2 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_260(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0100111011100000011110 RN RD  => INSN_OPCODE(I_SQABS ISET_ARM64 FM_ABS A_NA S_SIMD T_SINT T_SINT DATASZ_64b DATASZ_64b DATASZ_128b RW2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_827, I_SQABS, ISET_ARM64, FM_ABS, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_64b, DATASZ_64b, DATASZ_128b, RW2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_261(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0110111011100000011110 RN RD  => INSN_OPCODE(I_SQNEG ISET_ARM64 FM_NEG A_NA S_SIMD T_SINT T_SINT DATASZ_64b DATASZ_64b DATASZ_128b RW2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b00(found, input, mcr_826, mcr_827, I_SQNEG, ISET_ARM64, FM_NEG, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_64b, DATASZ_64b, DATASZ_128b, RW2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
#endif
#ifdef INSN_OPCODE_2b01
int arm64_encoder_262(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111010100001110010 RN RD  => INSN_OPCODE(I_URSQRTE ISET_ARM64 FM_RCP A_NA S_SIMD T_UINT T_UINT DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_URSQRTE, ISET_ARM64, FM_RCP, A_NA, S_SIMD, T_UINT, T_UINT, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_263(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111010100001110010 RN RD  => INSN_OPCODE(I_URECPE ISET_ARM64 FM_RCP A_NA S_SIMD T_UINT T_UINT DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_URECPE, ISET_ARM64, FM_RCP, A_NA, S_SIMD, T_UINT, T_UINT, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_264(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81e = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111001110001101010 RN RD  => INSN_OPCODE(I_UMINV ISET_ARM64 FM_MIN A_NA S_SIMD T_UINT T_UINT DATASZ_16b DATASZ_16b DATASZ_VAR R4Hto8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_81e, mcr_827, I_UMINV, ISET_ARM64, FM_MIN, A_NA, S_SIMD, T_UINT, T_UINT, DATASZ_16b, DATASZ_16b, DATASZ_VAR, R4Hto8H, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81e, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_265(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_812 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111000110001101010 RN RD  => INSN_OPCODE(I_UMINV ISET_ARM64 FM_MIN A_NA S_SIMD T_UINT T_UINT DATASZ_8b DATASZ_8b DATASZ_VAR R8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_812, mcr_827, I_UMINV, ISET_ARM64, FM_MIN, A_NA, S_SIMD, T_UINT, T_UINT, DATASZ_8b, DATASZ_8b, DATASZ_VAR, R8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_812, DATASZ_HWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_266(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81e = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111001110000101010 RN RD  => INSN_OPCODE(I_UMAXV ISET_ARM64 FM_MAX A_NA S_SIMD T_UINT T_UINT DATASZ_16b DATASZ_16b DATASZ_VAR R4Hto8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_81e, mcr_827, I_UMAXV, ISET_ARM64, FM_MAX, A_NA, S_SIMD, T_UINT, T_UINT, DATASZ_16b, DATASZ_16b, DATASZ_VAR, R4Hto8H, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81e, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_267(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_812 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111000110000101010 RN RD  => INSN_OPCODE(I_UMAXV ISET_ARM64 FM_MAX A_NA S_SIMD T_UINT T_UINT DATASZ_8b DATASZ_8b DATASZ_VAR R8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_812, mcr_827, I_UMAXV, ISET_ARM64, FM_MAX, A_NA, S_SIMD, T_UINT, T_UINT, DATASZ_8b, DATASZ_8b, DATASZ_VAR, R8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_812, DATASZ_HWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_268(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111000100001110110 RN RD  => INSN_OPCODE(I_UCVTF ISET_ARM64 FM_CVT A_NA S_SIMD T_FP T_UINT DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_UCVTF, ISET_ARM64, FM_CVT, A_NA, S_SIMD, T_FP, T_UINT, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_269(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81e = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111001110000001110 RN RD  => INSN_OPCODE(I_UADDLV ISET_ARM64 FM_ADD A_NA S_SIMD T_UINT T_UINT DATASZ_32b DATASZ_16b DATASZ_VAR R4Hto8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_81e, mcr_827, I_UADDLV, ISET_ARM64, FM_ADD, A_NA, S_SIMD, T_UINT, T_UINT, DATASZ_32b, DATASZ_16b, DATASZ_VAR, R4Hto8H, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81e, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_26a(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_812 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111000110000001110 RN RD  => INSN_OPCODE(I_UADDLV ISET_ARM64 FM_ADD A_NA S_SIMD T_UINT T_UINT DATASZ_16b DATASZ_8b DATASZ_VAR R8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_812, mcr_827, I_UADDLV, ISET_ARM64, FM_ADD, A_NA, S_SIMD, T_UINT, T_UINT, DATASZ_16b, DATASZ_8b, DATASZ_VAR, R8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_812, DATASZ_HWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_26b(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_802 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111000110001101110 RN RD  => INSN_OPCODE(I_ADDV ISET_ARM64 FM_ADD A_NA S_SIMD T_SINT T_SINT DATASZ_8b DATASZ_8b DATASZ_VAR R8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_802, mcr_827, I_ADDV, ISET_ARM64, FM_ADD, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_8b, DATASZ_8b, DATASZ_VAR, R8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_802, DATASZ_BYTE, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_26c(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_812 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111001110001101110 RN RD  => INSN_OPCODE(I_ADDV ISET_ARM64 FM_ADD A_NA S_SIMD T_SINT T_SINT DATASZ_16b DATASZ_16b DATASZ_VAR R4Hto8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_812, mcr_827, I_ADDV, ISET_ARM64, FM_ADD, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_16b, DATASZ_16b, DATASZ_VAR, R4Hto8H, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_812, DATASZ_HWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_26d(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_829 = NULL,*mcr_743 = NULL,*mcr_fffffff8 = NULL,*mcr_ffffff9d = NULL,*mcr_ffffffbf = NULL;
	/*template:	0 Q 10111100000 IMM3 10 SHFT1 101 IMM5 RD  => INSN_OPCODE(I_BIC ISET_ARM64 FM_CLR A_NA S_SIMD T_BIT T_BIT DATASZ_16b DATASZ_16b DATASZ_VAR W4Hto8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_829, mcr_743, I_BIC, ISET_ARM64, FM_CLR, A_NA, S_SIMD, T_BIT, T_BIT, DATASZ_16b, DATASZ_16b, DATASZ_VAR, W4Hto8H, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_829, DATASZ_QWORD, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_IMMEDIATE_2200(found, mcr_743, mcr_fffffff8, mcr_ffffff9d, DATASZ_8b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_0102(found, mcr_fffffff8, DATASZ_UNDEF, vals[BDFVar__IMM3 - BDFVar__VARNUMBER], vals[BDFVar__IMM5 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {SHIFT_1200(found, mcr_ffffff9d, mcr_ffffffbf, DATASZ_UNDEF, LSL);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffbf, DATASZ_UNDEF, THREE, vals[BDFVar__SHFT1 - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_26e(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_829 = NULL,*mcr_744 = NULL,*mcr_fffffff8 = NULL,*mcr_ffffff9c = NULL,*mcr_ffffffbe = NULL;
	/*template:	0 Q 10111100000 IMM3 0 SHFT2 101 IMM5 RD  => INSN_OPCODE(I_BIC ISET_ARM64 FM_CLR A_NA S_SIMD T_BIT T_BIT DATASZ_32b DATASZ_32b DATASZ_VAR W2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_829, mcr_744, I_BIC, ISET_ARM64, FM_CLR, A_NA, S_SIMD, T_BIT, T_BIT, DATASZ_32b, DATASZ_32b, DATASZ_VAR, W2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_829, DATASZ_QWORD, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_IMMEDIATE_2200(found, mcr_744, mcr_fffffff8, mcr_ffffff9c, DATASZ_8b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_0102(found, mcr_fffffff8, DATASZ_UNDEF, vals[BDFVar__IMM3 - BDFVar__VARNUMBER], vals[BDFVar__IMM5 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {SHIFT_1200(found, mcr_ffffff9c, mcr_ffffffbe, DATASZ_UNDEF, LSL);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffbe, DATASZ_UNDEF, THREE, vals[BDFVar__SHFT2 - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_26f(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111000100000010110 RN RD  => INSN_OPCODE(I_CNT ISET_ARM64 FM_CNT A_NA S_SIMD T_INT T_SINT DATASZ_8b DATASZ_8b DATASZ_VAR RW8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_CNT, ISET_ARM64, FM_CNT, A_NA, S_SIMD, T_INT, T_SINT, DATASZ_8b, DATASZ_8b, DATASZ_VAR, RW8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_270(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_830 = NULL;
	/*template:	0 Q 00111000000001000011 RN RD  => INSN_OPCODE(I_DUP ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b W8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_830, I_DUP, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b, W8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_830, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_271(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_830 = NULL;
	/*template:	0 Q 00111000000010000011 RN RD  => INSN_OPCODE(I_DUP ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b W4Hto8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_830, I_DUP, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b, W4Hto8H, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_830, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_272(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_830 = NULL;
	/*template:	0 Q 00111000000100000011 RN RD  => INSN_OPCODE(I_DUP ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b W2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_830, I_DUP, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b, W2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_830, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_273(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111010100000111110 RN RD  => INSN_OPCODE(I_FABS ISET_ARM64 FM_ABS A_NA S_SIMD T_FP T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FABS, ISET_ARM64, FM_ABS, A_NA, S_SIMD, T_FP, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_274(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111000100001110010 RN RD  => INSN_OPCODE(I_FCVTAS ISET_ARM64 FM_CVT A_NA S_SIMD T_SINT T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FCVTAS, ISET_ARM64, FM_CVT, A_NA, S_SIMD, T_SINT, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_275(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111000100001110010 RN RD  => INSN_OPCODE(I_FCVTAU ISET_ARM64 FM_CVT A_NA S_SIMD T_UINT T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FCVTAU, ISET_ARM64, FM_CVT, A_NA, S_SIMD, T_UINT, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_276(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111000100001101110 RN RD  => INSN_OPCODE(I_FCVTMS ISET_ARM64 FM_CVT A_NA S_SIMD T_SINT T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FCVTMS, ISET_ARM64, FM_CVT, A_NA, S_SIMD, T_SINT, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_277(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111000100001101110 RN RD  => INSN_OPCODE(I_FCVTMU ISET_ARM64 FM_CVT A_NA S_SIMD T_UINT T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FCVTMU, ISET_ARM64, FM_CVT, A_NA, S_SIMD, T_UINT, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_278(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111000100001101010 RN RD  => INSN_OPCODE(I_FCVTNS ISET_ARM64 FM_CVT A_NA S_SIMD T_SINT T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FCVTNS, ISET_ARM64, FM_CVT, A_NA, S_SIMD, T_SINT, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_279(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111000100001101010 RN RD  => INSN_OPCODE(I_FCVTNU ISET_ARM64 FM_CVT A_NA S_SIMD T_UINT T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FCVTNU, ISET_ARM64, FM_CVT, A_NA, S_SIMD, T_UINT, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_27a(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111010100001101010 RN RD  => INSN_OPCODE(I_FCVTPS ISET_ARM64 FM_CVT A_NA S_SIMD T_SINT T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FCVTPS, ISET_ARM64, FM_CVT, A_NA, S_SIMD, T_SINT, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_27b(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111010100001101010 RN RD  => INSN_OPCODE(I_FCVTPU ISET_ARM64 FM_CVT A_NA S_SIMD T_UINT T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FCVTPU, ISET_ARM64, FM_CVT, A_NA, S_SIMD, T_UINT, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_27c(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111010100001101110 RN RD  => INSN_OPCODE(I_FCVTZS ISET_ARM64 FM_CVT A_NA S_SIMD T_SINT T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FCVTZS, ISET_ARM64, FM_CVT, A_NA, S_SIMD, T_SINT, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_27d(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111010100001101110 RN RD  => INSN_OPCODE(I_FCVTZU ISET_ARM64 FM_CVT A_NA S_SIMD T_UINT T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FCVTZU, ISET_ARM64, FM_CVT, A_NA, S_SIMD, T_UINT, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_27e(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_737 = NULL,*mcr_ffffffd0 = NULL,*mcr_ffffffaa = NULL,*mcr_ffffffeb = NULL,*mcr_ffffffa5 = NULL,*mcr_ffffffca = NULL;
	/*template:	0 Q 00111100000 A B IMM1 111101 IMM5 RD  => INSN_OPCODE(I_FMOV ISET_ARM64 FM_MOV A_NA S_SIMD T_FP T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_737, I_FMOV, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_FP, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_IMMEDIATE_1200(found, mcr_737, mcr_ffffffd0, DATASZ_8b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {FLOAT_CAST_SWORD_1100(found, mcr_ffffffd0, mcr_ffffffaa, DATASZ_UNDEF);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_1200(found, mcr_ffffffaa, mcr_ffffffeb, DATASZ_UNDEF, NINETEEN);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_SWORD_FLOAT_2103(found, mcr_ffffffeb, mcr_ffffffa5, mcr_ffffffca, DATASZ_UNDEF, vals[BDFVar__A - BDFVar__VARNUMBER], vals[BDFVar__IMM1 - BDFVar__VARNUMBER], vals[BDFVar__IMM5 - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {NOT_0101(found, mcr_ffffffa5, DATASZ_UNDEF, vals[BDFVar__B - BDFVar__VARNUMBER]);}
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffca, DATASZ_UNDEF, FOUR, vals[BDFVar__B - BDFVar__VARNUMBER]);}
	}
	}
	}
	}
	}
	return found;
}
int arm64_encoder_27f(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111010100000111110 RN RD  => INSN_OPCODE(I_FNEG ISET_ARM64 FM_NEG A_NA S_SIMD T_FP T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FNEG, ISET_ARM64, FM_NEG, A_NA, S_SIMD, T_FP, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_280(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111010100001110110 RN RD  => INSN_OPCODE(I_FRECPE ISET_ARM64 FM_RCP A_NA S_SIMD T_FP T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FRECPE, ISET_ARM64, FM_RCP, A_NA, S_SIMD, T_FP, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_281(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111000100001100010 RN RD  => INSN_OPCODE(I_FRINTA ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FRINTA, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_282(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111010100001100110 RN RD  => INSN_OPCODE(I_FRINTI ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FRINTI, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_283(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111000100001100110 RN RD  => INSN_OPCODE(I_FRINTM ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FRINTM, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_284(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111000100001100010 RN RD  => INSN_OPCODE(I_FRINTN ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FRINTN, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_285(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111010100001100010 RN RD  => INSN_OPCODE(I_FRINTP ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FRINTP, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_286(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111000100001100110 RN RD  => INSN_OPCODE(I_FRINTX ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FRINTX, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_287(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111010100001100110 RN RD  => INSN_OPCODE(I_FRINTZ ISET_ARM64 FM_RND A_NA S_SIMD T_FP T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FRINTZ, ISET_ARM64, FM_RND, A_NA, S_SIMD, T_FP, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_288(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111010100001110110 RN RD  => INSN_OPCODE(I_FRSQRTE ISET_ARM64 FM_SQRT A_NA S_SIMD T_FP T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FRSQRTE, ISET_ARM64, FM_SQRT, A_NA, S_SIMD, T_FP, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_289(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111010100001111110 RN RD  => INSN_OPCODE(I_FSQRT ISET_ARM64 FM_SQRT A_NA S_SIMD T_FP T_FP DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_FSQRT, ISET_ARM64, FM_SQRT, A_NA, S_SIMD, T_FP, T_FP, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_28a(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_73b = NULL,*mcr_fffffff8 = NULL;
	/*template:	0 Q 00111100000 IMM3 111001 IMM5 RD  => INSN_OPCODE(I_MOVI ISET_ARM64 FM_MOV A_NA S_SIMD T_INT T_INT DATASZ_8b DATASZ_8b DATASZ_VAR W8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_73b, I_MOVI, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_INT, T_INT, DATASZ_8b, DATASZ_8b, DATASZ_VAR, W8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_IMMEDIATE_1200(found, mcr_73b, mcr_fffffff8, DATASZ_8b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_0102(found, mcr_fffffff8, DATASZ_UNDEF, vals[BDFVar__IMM3 - BDFVar__VARNUMBER], vals[BDFVar__IMM5 - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_28b(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_745 = NULL,*mcr_fffffff8 = NULL,*mcr_ffffffd7 = NULL,*mcr_ffffffaf = NULL;
	/*template:	0 Q 00111100000 IMM3 10 IMM1 001 IMM5 RD  => INSN_OPCODE(I_MOVI ISET_ARM64 FM_MOV A_NA S_SIMD T_INT T_INT DATASZ_16b DATASZ_16b DATASZ_VAR W4Hto8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_745, I_MOVI, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_INT, T_INT, DATASZ_16b, DATASZ_16b, DATASZ_VAR, W4Hto8H, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_IMMEDIATE_2200(found, mcr_745, mcr_fffffff8, mcr_ffffffd7, DATASZ_8b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_0102(found, mcr_fffffff8, DATASZ_UNDEF, vals[BDFVar__IMM3 - BDFVar__VARNUMBER], vals[BDFVar__IMM5 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffd7, mcr_ffffffaf, DATASZ_UNDEF, LSL);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffaf, DATASZ_UNDEF, THREE, vals[BDFVar__IMM1 - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_28c(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_746 = NULL,*mcr_fffffff8 = NULL,*mcr_ffffffd6 = NULL,*mcr_ffffffae = NULL;
	/*template:	0 Q 00111100000 IMM3 0 IMM2 001 IMM5 RD  => INSN_OPCODE(I_MOVI ISET_ARM64 FM_MOV A_NA S_SIMD T_INT T_INT DATASZ_32b DATASZ_32b DATASZ_VAR W2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_746, I_MOVI, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_INT, T_INT, DATASZ_32b, DATASZ_32b, DATASZ_VAR, W2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_IMMEDIATE_2200(found, mcr_746, mcr_fffffff8, mcr_ffffffd6, DATASZ_8b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_0102(found, mcr_fffffff8, DATASZ_UNDEF, vals[BDFVar__IMM3 - BDFVar__VARNUMBER], vals[BDFVar__IMM5 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffd6, mcr_ffffffae, DATASZ_UNDEF, LSL);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffae, DATASZ_UNDEF, THREE, vals[BDFVar__IMM2 - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_28d(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_747 = NULL,*mcr_fffffff8 = NULL,*mcr_ffffffd5 = NULL,*mcr_fffffffb = NULL,*mcr_ffffffaf = NULL;
	/*template:	0 Q 00111100000 IMM3 110 IMM1 01 IMM5 RD  => INSN_OPCODE(I_MOVI ISET_ARM64 FM_MOV A_NA S_SIMD T_INT T_INT DATASZ_32b DATASZ_32b DATASZ_VAR W2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_747, I_MOVI, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_INT, T_INT, DATASZ_32b, DATASZ_32b, DATASZ_VAR, W2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_IMMEDIATE_2200(found, mcr_747, mcr_fffffff8, mcr_ffffffd5, DATASZ_8b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_0102(found, mcr_fffffff8, DATASZ_UNDEF, vals[BDFVar__IMM3 - BDFVar__VARNUMBER], vals[BDFVar__IMM5 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffd5, mcr_fffffffb, DATASZ_UNDEF, MSL);}
	if (found == TRUE) {
		if (found == TRUE) {ADDITION_1200(found, mcr_fffffffb, mcr_ffffffaf, DATASZ_UNDEF, CI8);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffaf, DATASZ_UNDEF, THREE, vals[BDFVar__IMM1 - BDFVar__VARNUMBER]);}
	}
	}
	}
	}
	return found;
}
int arm64_encoder_28e(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111000100000010110 RN RD  => INSN_OPCODE(I_MVN ISET_ARM64 FM_NOT A_NA S_SIMD T_BIT T_BIT DATASZ_8b DATASZ_8b DATASZ_VAR RW8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_MVN, ISET_ARM64, FM_NOT, A_NA, S_SIMD, T_BIT, T_BIT, DATASZ_8b, DATASZ_8b, DATASZ_VAR, RW8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_28f(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_745 = NULL,*mcr_fffffff8 = NULL,*mcr_ffffffd7 = NULL,*mcr_ffffffaf = NULL;
	/*template:	0 Q 10111100000 IMM3 10 IMM1 0 IMM5 RD  => INSN_OPCODE(I_MVNI ISET_ARM64 FM_MOV A_NA S_SIMD T_INT T_INT DATASZ_16b DATASZ_16b DATASZ_VAR W4Hto8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_745, I_MVNI, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_INT, T_INT, DATASZ_16b, DATASZ_16b, DATASZ_VAR, W4Hto8H, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_IMMEDIATE_2200(found, mcr_745, mcr_fffffff8, mcr_ffffffd7, DATASZ_8b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_0102(found, mcr_fffffff8, DATASZ_UNDEF, vals[BDFVar__IMM3 - BDFVar__VARNUMBER], vals[BDFVar__IMM5 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffd7, mcr_ffffffaf, DATASZ_UNDEF, LSL);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffaf, DATASZ_UNDEF, THREE, vals[BDFVar__IMM1 - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_290(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_746 = NULL,*mcr_fffffff8 = NULL,*mcr_ffffffd6 = NULL,*mcr_ffffffae = NULL;
	/*template:	0 Q 10111100000 IMM3 0 IMM2 0 IMM5 RD  => INSN_OPCODE(I_MVNI ISET_ARM64 FM_MOV A_NA S_SIMD T_INT T_INT DATASZ_32b DATASZ_32b DATASZ_VAR W2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_746, I_MVNI, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_INT, T_INT, DATASZ_32b, DATASZ_32b, DATASZ_VAR, W2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_IMMEDIATE_2200(found, mcr_746, mcr_fffffff8, mcr_ffffffd6, DATASZ_8b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_0102(found, mcr_fffffff8, DATASZ_UNDEF, vals[BDFVar__IMM3 - BDFVar__VARNUMBER], vals[BDFVar__IMM5 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffd6, mcr_ffffffae, DATASZ_UNDEF, LSL);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffae, DATASZ_UNDEF, THREE, vals[BDFVar__IMM2 - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_291(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_747 = NULL,*mcr_fffffff8 = NULL,*mcr_ffffffd5 = NULL,*mcr_fffffffb = NULL,*mcr_ffffffaf = NULL;
	/*template:	0 Q 10111100000 IMM3 110 IMM1 IMM5 RD  => INSN_OPCODE(I_MVNI ISET_ARM64 FM_MOV A_NA S_SIMD T_INT T_INT DATASZ_64b DATASZ_64b DATASZ_VAR W2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_747, I_MVNI, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_INT, T_INT, DATASZ_64b, DATASZ_64b, DATASZ_VAR, W2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_IMMEDIATE_2200(found, mcr_747, mcr_fffffff8, mcr_ffffffd5, DATASZ_8b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_0102(found, mcr_fffffff8, DATASZ_UNDEF, vals[BDFVar__IMM3 - BDFVar__VARNUMBER], vals[BDFVar__IMM5 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffd5, mcr_fffffffb, DATASZ_UNDEF, MSL);}
	if (found == TRUE) {
		if (found == TRUE) {ADDITION_1200(found, mcr_fffffffb, mcr_ffffffaf, DATASZ_UNDEF, CI8);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffaf, DATASZ_UNDEF, THREE, vals[BDFVar__IMM1 - BDFVar__VARNUMBER]);}
	}
	}
	}
	}
	return found;
}
int arm64_encoder_292(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_745 = NULL,*mcr_fffffff8 = NULL,*mcr_ffffffd7 = NULL,*mcr_ffffffaf = NULL;
	/*template:	0 Q 00111100000 IMM3 10 IMM1 101 IMM5 RD  => INSN_OPCODE(I_ORR ISET_ARM64 FM_OR A_NA S_SIMD T_BIT T_BIT DATASZ_16b DATASZ_16b DATASZ_VAR W4Hto8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_745, I_ORR, ISET_ARM64, FM_OR, A_NA, S_SIMD, T_BIT, T_BIT, DATASZ_16b, DATASZ_16b, DATASZ_VAR, W4Hto8H, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_IMMEDIATE_2200(found, mcr_745, mcr_fffffff8, mcr_ffffffd7, DATASZ_8b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_0102(found, mcr_fffffff8, DATASZ_UNDEF, vals[BDFVar__IMM3 - BDFVar__VARNUMBER], vals[BDFVar__IMM5 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffd7, mcr_ffffffaf, DATASZ_UNDEF, LSL);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffaf, DATASZ_UNDEF, THREE, vals[BDFVar__IMM1 - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_293(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_746 = NULL,*mcr_fffffff8 = NULL,*mcr_ffffffd6 = NULL,*mcr_ffffffae = NULL;
	/*template:	0 Q 00111100000 IMM3 0 IMM2 101 IMM5 RD  => INSN_OPCODE(I_ORR ISET_ARM64 FM_OR A_NA S_SIMD T_BIT T_BIT DATASZ_32b DATASZ_32b DATASZ_VAR W2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_746, I_ORR, ISET_ARM64, FM_OR, A_NA, S_SIMD, T_BIT, T_BIT, DATASZ_32b, DATASZ_32b, DATASZ_VAR, W2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_IMMEDIATE_2200(found, mcr_746, mcr_fffffff8, mcr_ffffffd6, DATASZ_8b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_0102(found, mcr_fffffff8, DATASZ_UNDEF, vals[BDFVar__IMM3 - BDFVar__VARNUMBER], vals[BDFVar__IMM5 - BDFVar__VARNUMBER]);}
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffd6, mcr_ffffffae, DATASZ_UNDEF, LSL);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffae, DATASZ_UNDEF, THREE, vals[BDFVar__IMM2 - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_294(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111001100000010110 RN RD  => INSN_OPCODE(I_RBIT ISET_ARM64 FM_UNDEF A_NA S_SIMD T_BIT T_BIT DATASZ_8b DATASZ_8b DATASZ_VAR RW8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_RBIT, ISET_ARM64, FM_UNDEF, A_NA, S_SIMD, T_BIT, T_BIT, DATASZ_8b, DATASZ_8b, DATASZ_VAR, RW8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_295(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111000100000000110 RN RD  => INSN_OPCODE(I_REV16 ISET_ARM64 FM_BSWAP A_NA S_SIMD T_BIT T_BIT DATASZ_8b DATASZ_8b DATASZ_VAR RW8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_REV16, ISET_ARM64, FM_BSWAP, A_NA, S_SIMD, T_BIT, T_BIT, DATASZ_8b, DATASZ_8b, DATASZ_VAR, RW8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_296(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111000100000000010 RN RD  => INSN_OPCODE(I_REV32 ISET_ARM64 FM_BSWAP A_NA S_SIMD T_BIT T_BIT DATASZ_8b DATASZ_8b DATASZ_VAR RW8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_REV32, ISET_ARM64, FM_BSWAP, A_NA, S_SIMD, T_BIT, T_BIT, DATASZ_8b, DATASZ_8b, DATASZ_VAR, RW8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_297(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 10111001100000000010 RN RD  => INSN_OPCODE(I_REV32 ISET_ARM64 FM_BSWAP A_NA S_SIMD T_BIT T_BIT DATASZ_16b DATASZ_16b DATASZ_VAR RW4Hto8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_REV32, ISET_ARM64, FM_BSWAP, A_NA, S_SIMD, T_BIT, T_BIT, DATASZ_16b, DATASZ_16b, DATASZ_VAR, RW4Hto8H, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_298(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_812 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111000110000001110 RN RD  => INSN_OPCODE(I_SADDLV ISET_ARM64 FM_ADD A_NA S_SIMD T_SINT T_SINT DATASZ_16b DATASZ_8b DATASZ_VAR R8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_812, mcr_827, I_SADDLV, ISET_ARM64, FM_ADD, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_16b, DATASZ_8b, DATASZ_VAR, R8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_812, DATASZ_HWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_299(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81e = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111001110000001110 RN RD  => INSN_OPCODE(I_SADDLV ISET_ARM64 FM_ADD A_NA S_SIMD T_SINT T_SINT DATASZ_32b DATASZ_16b DATASZ_VAR R4Hto8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_81e, mcr_827, I_SADDLV, ISET_ARM64, FM_ADD, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_32b, DATASZ_16b, DATASZ_VAR, R4Hto8H, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81e, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_29a(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111000100001110110 RN RD  => INSN_OPCODE(I_SCVTF ISET_ARM64 FM_CVT A_NA S_SIMD T_FP T_SINT DATASZ_32b DATASZ_32b DATASZ_VAR RW2Sto4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_826, mcr_827, I_SCVTF, ISET_ARM64, FM_CVT, A_NA, S_SIMD, T_FP, T_SINT, DATASZ_32b, DATASZ_32b, DATASZ_VAR, RW2Sto4S, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_29b(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_802 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111000110000101010 RN RD  => INSN_OPCODE(I_SMAXV ISET_ARM64 FM_MAX A_NA S_SIMD T_SINT T_SINT DATASZ_8b DATASZ_8b DATASZ_VAR R8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_802, mcr_827, I_SMAXV, ISET_ARM64, FM_MAX, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_8b, DATASZ_8b, DATASZ_VAR, R8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_802, DATASZ_BYTE, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_29c(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_812 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111001110000101010 RN RD  => INSN_OPCODE(I_SMAXV ISET_ARM64 FM_MAX A_NA S_SIMD T_SINT T_SINT DATASZ_16b DATASZ_16b DATASZ_VAR R4Hto8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_812, mcr_827, I_SMAXV, ISET_ARM64, FM_MAX, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_16b, DATASZ_16b, DATASZ_VAR, R4Hto8H, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_812, DATASZ_HWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_29d(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_802 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111000110001101010 RN RD  => INSN_OPCODE(I_SMINV ISET_ARM64 FM_MIN A_NA S_SIMD T_SINT T_SINT DATASZ_8b DATASZ_8b DATASZ_VAR R8Bto16B )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_802, mcr_827, I_SMINV, ISET_ARM64, FM_MIN, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_8b, DATASZ_8b, DATASZ_VAR, R8Bto16B, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_802, DATASZ_BYTE, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_29e(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_812 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 00111001110001101010 RN RD  => INSN_OPCODE(I_SMINV ISET_ARM64 FM_MIN A_NA S_SIMD T_SINT T_SINT DATASZ_16b DATASZ_16b DATASZ_VAR R4Hto8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2b01(found, input, mcr_812, mcr_827, I_SMINV, ISET_ARM64, FM_MIN, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_16b, DATASZ_16b, DATASZ_VAR, R4Hto8H, vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_812, DATASZ_HWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
#endif
#ifdef INSN_OPCODE_2b11
int arm64_encoder_29f(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_829 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 101110 AS 100000001110 RN RD  => INSN_OPCODE(I_USQADD ISET_ARM64 FM_ADD A_NA S_SIMD T_UINT T_SINT DATASZ_VAR DATASZ_VAR DATASZ_VAR RW8Bto4S )*/
	int found = TRUE;
	INSN_OPCODE_2b11(found, input, mcr_829, mcr_827, I_USQADD, ISET_ARM64, FM_ADD, A_NA, S_SIMD, T_UINT, T_SINT, DATASZ_VAR, DATASZ_VAR, DATASZ_VAR, RW8Bto4S, vars[BDFVar__AS], vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_829, DATASZ_QWORD, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_2a0(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_829 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 001110 AS 100000001110 RN RD  => INSN_OPCODE(I_SUQADD ISET_ARM64 FM_ADD A_NA S_SIMD T_UINT T_UINT DATASZ_VAR DATASZ_VAR DATASZ_VAR RW8Bto4S )*/
	int found = TRUE;
	INSN_OPCODE_2b11(found, input, mcr_829, mcr_827, I_SUQADD, ISET_ARM64, FM_ADD, A_NA, S_SIMD, T_UINT, T_UINT, DATASZ_VAR, DATASZ_VAR, DATASZ_VAR, RW8Bto4S, vars[BDFVar__AS], vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_829, DATASZ_QWORD, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_2a1(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 001110 AS 100000101110 RN RD  => INSN_OPCODE(I_ABS ISET_ARM64 FM_ABS A_NA S_SIMD T_INT T_SINT DATASZ_VAR DATASZ_VAR DATASZ_VAR RW8Bto4S )*/
	int found = TRUE;
	INSN_OPCODE_2b11(found, input, mcr_826, mcr_827, I_ABS, ISET_ARM64, FM_ABS, A_NA, S_SIMD, T_INT, T_SINT, DATASZ_VAR, DATASZ_VAR, DATASZ_VAR, RW8Bto4S, vars[BDFVar__AS], vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_2a2(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 001110 AS 100000010010 RN RD  => INSN_OPCODE(I_CLS ISET_ARM64 FM_CNT A_NA S_SIMD T_INT T_INT DATASZ_VAR DATASZ_VAR DATASZ_VAR RW8Bto4S )*/
	int found = TRUE;
	INSN_OPCODE_2b11(found, input, mcr_826, mcr_827, I_CLS, ISET_ARM64, FM_CNT, A_NA, S_SIMD, T_INT, T_INT, DATASZ_VAR, DATASZ_VAR, DATASZ_VAR, RW8Bto4S, vars[BDFVar__AS], vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_2a3(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 101110 AS 100000010010 RN RD  => INSN_OPCODE(I_CLZ ISET_ARM64 FM_CNT A_NA S_SIMD T_INT T_INT DATASZ_VAR DATASZ_VAR DATASZ_VAR RW8Bto4S )*/
	int found = TRUE;
	INSN_OPCODE_2b11(found, input, mcr_826, mcr_827, I_CLZ, ISET_ARM64, FM_CNT, A_NA, S_SIMD, T_INT, T_INT, DATASZ_VAR, DATASZ_VAR, DATASZ_VAR, RW8Bto4S, vars[BDFVar__AS], vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_2a4(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 101110 AS 100000101110 RN RD  => INSN_OPCODE(I_NEG ISET_ARM64 FM_NEG A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_VAR DATASZ_VAR DATASZ_VAR RW8Bto4S )*/
	int found = TRUE;
	INSN_OPCODE_2b11(found, input, mcr_826, mcr_827, I_NEG, ISET_ARM64, FM_NEG, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_VAR, DATASZ_VAR, DATASZ_VAR, RW8Bto4S, vars[BDFVar__AS], vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_2a5(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 001110 AS 100000000010 RN RD  => INSN_OPCODE(I_REV64 ISET_ARM64 FM_BSWAP A_NA S_SIMD T_BIT T_BIT DATASZ_VAR DATASZ_VAR DATASZ_VAR RW8Bto4S )*/
	int found = TRUE;
	INSN_OPCODE_2b11(found, input, mcr_826, mcr_827, I_REV64, ISET_ARM64, FM_BSWAP, A_NA, S_SIMD, T_BIT, T_BIT, DATASZ_VAR, DATASZ_VAR, DATASZ_VAR, RW8Bto4S, vars[BDFVar__AS], vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_2a6(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 001110 AS 100000011110 RN RD  => INSN_OPCODE(I_SQABS ISET_ARM64 FM_ABS A_NA S_SIMD T_SINT T_SINT DATASZ_VAR DATASZ_VAR DATASZ_VAR RW8Bto4S )*/
	int found = TRUE;
	INSN_OPCODE_2b11(found, input, mcr_826, mcr_827, I_SQABS, ISET_ARM64, FM_ABS, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_VAR, DATASZ_VAR, DATASZ_VAR, RW8Bto4S, vars[BDFVar__AS], vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_2a7(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0 Q 101110 AS 100000011110 RN RD  => INSN_OPCODE(I_SQNEG ISET_ARM64 FM_NEG A_NA S_SIMD T_SINT T_SINT DATASZ_VAR DATASZ_VAR DATASZ_VAR RW8Bto4S )*/
	int found = TRUE;
	INSN_OPCODE_2b11(found, input, mcr_826, mcr_827, I_SQNEG, ISET_ARM64, FM_NEG, A_NA, S_SIMD, T_SINT, T_SINT, DATASZ_VAR, DATASZ_VAR, DATASZ_VAR, RW8Bto4S, vars[BDFVar__AS], vals[BDFVar__Q - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
#endif
#ifdef INSN_OPCODE_2c00
int arm64_encoder_2a8(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0100111010100001001010 RN RD  => INSN_OPCODE(I_XTN2 ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_64b DATASZ_128b W4S R2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2c00(found, input, mcr_826, mcr_827, I_XTN2, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_64b, DATASZ_128b, W4S, R2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_2a9(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0100111001100001001010 RN RD  => INSN_OPCODE(I_XTN2 ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_16b DATASZ_32b DATASZ_128b W8H R4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2c00(found, input, mcr_826, mcr_827, I_XTN2, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_32b, DATASZ_128b, W8H, R4S);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_2aa(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0100111000100001001010 RN RD  => INSN_OPCODE(I_XTN2 ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_8b DATASZ_16b DATASZ_128b W16B R8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2c00(found, input, mcr_826, mcr_827, I_XTN2, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_16b, DATASZ_128b, W16B, R8H);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_2ab(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0000111010100001001010 RN RD  => INSN_OPCODE(I_XTN ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_64b DATASZ_128b W2S R2D )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2c00(found, input, mcr_826, mcr_827, I_XTN, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_64b, DATASZ_128b, W2S, R2D);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_2ac(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0000111001100001001010 RN RD  => INSN_OPCODE(I_XTN ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_16b DATASZ_32b DATASZ_128b W4H R4S )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2c00(found, input, mcr_826, mcr_827, I_XTN, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_32b, DATASZ_128b, W4H, R4S);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_2ad(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_826 = NULL,*mcr_827 = NULL;
	/*template:	0000111000100001001010 RN RD  => INSN_OPCODE(I_XTN ISET_ARM64 FM_MOV A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_8b DATASZ_16b DATASZ_128b W8B R8H )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2c00(found, input, mcr_826, mcr_827, I_XTN, ISET_ARM64, FM_MOV, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_16b, DATASZ_128b, W8B, R8H);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_826, DATASZ_QWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_VECTOR_0201(found, mcr_827, DATASZ_QWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
#endif
