/*
   Copyright (C) 2004 - 2018 Université de Versailles Saint-Quentin-en-Yvelines (UVSQ)

   This file is part of MAQAO.

  MAQAO is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public License
   as published by the Free Software Foundation; either version 3
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */


/**
* \file arm64_revfct_1.c
* \brief This file contains the bodies of functions for reversing the semantic actions
* \warning This file has been automatically generated by MINJAG from file arm64_6bf96bbfcca0afd1af78d50ba75869a8.bdf and should not be modified
* */
#include <stdlib.h>
#include "arm64_arch.h"
#include "arm64_sym.h"
#include "asmblutils.h"
#include "arm64_revmacros.h"
#include "arm64_revfct.h"
#ifdef INSN_OPCODE_1a00
int arm64_encoder_74(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7b8 = NULL;
	/*template:	1101011000111111000000 RN 00000  => INSN_OPCODE(I_BLR ISET_ARM64 FM_CALL A_CALL S_SCALAR T_UNDEF T_SINT DATASZ_UNDEF DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_7b8, I_BLR, ISET_ARM64, FM_CALL, A_CALL, S_SCALAR, T_UNDEF, T_SINT, DATASZ_UNDEF, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0201(found, mcr_7b8, DATASZ_DWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_75(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7b8 = NULL;
	/*template:	1101011000011111000000 RN 00000  => INSN_OPCODE(I_BR ISET_ARM64 FM_JUMP A_NA S_SCALAR T_UNDEF T_SINT DATASZ_UNDEF DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_7b8, I_BR, ISET_ARM64, FM_JUMP, A_NA, S_SCALAR, T_UNDEF, T_SINT, DATASZ_UNDEF, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0201(found, mcr_7b8, DATASZ_DWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_76(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_727 = NULL;
	/*template:	11010100001 IMM16 00000  => INSN_OPCODE(I_BRK ISET_ARM64 FM_SYNC A_NA S_SCALAR T_UNDEF T_INT DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_727, I_BRK, ISET_ARM64, FM_SYNC, A_NA, S_SCALAR, T_UNDEF, T_INT, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_IMMEDIATE_0201(found, mcr_727, DATASZ_16b, READ, vals[BDFVar__IMM16 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_77(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_728 = NULL;
	/*template:	11010101000000110011 IMM4 01011111  => INSN_OPCODE(I_CLREX ISET_ARM64 FM_SYNC A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_728, I_CLREX, ISET_ARM64, FM_SYNC, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_IMMEDIATE_0201(found, mcr_728, DATASZ_4b, READ, vals[BDFVar__IMM4 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_78(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_727 = NULL;
	/*template:	11010100101 IMM16 00001  => INSN_OPCODE(I_DCPS1 ISET_ARM64 FM_HW A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_727, I_DCPS1, ISET_ARM64, FM_HW, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_IMMEDIATE_0201(found, mcr_727, DATASZ_16b, READ, vals[BDFVar__IMM16 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_79(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_727 = NULL;
	/*template:	11010100101 IMM16 00010  => INSN_OPCODE(I_DCPS2 ISET_ARM64 FM_HW A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_727, I_DCPS2, ISET_ARM64, FM_HW, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_IMMEDIATE_0201(found, mcr_727, DATASZ_16b, READ, vals[BDFVar__IMM16 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_7a(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_727 = NULL;
	/*template:	11010100101 IMM16 00011  => INSN_OPCODE(I_DCPS3 ISET_ARM64 FM_HW A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_727, I_DCPS3, ISET_ARM64, FM_HW, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_IMMEDIATE_0201(found, mcr_727, DATASZ_16b, READ, vals[BDFVar__IMM16 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_7b(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_728 = NULL;
	/*template:	11010101000000110011 IMM4 10111111  => INSN_OPCODE(I_DMB ISET_ARM64 FM_SYNC A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_728, I_DMB, ISET_ARM64, FM_SYNC, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_IMMEDIATE_0201(found, mcr_728, DATASZ_4b, READ, vals[BDFVar__IMM4 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_7c(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_728 = NULL;
	/*template:	11010101000000110011 IMM4 10011111  => INSN_OPCODE(I_DSB ISET_ARM64 FM_SYNC A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_728, I_DSB, ISET_ARM64, FM_SYNC, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_IMMEDIATE_0201(found, mcr_728, DATASZ_4b, READ, vals[BDFVar__IMM4 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_7d(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_72a = NULL;
	/*template:	11010101000000110010 IMM7 11111  => INSN_OPCODE(I_HINT ISET_ARM64 FM_SYNC A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_72a, I_HINT, ISET_ARM64, FM_SYNC, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_IMMEDIATE_0201(found, mcr_72a, DATASZ_7b, READ, vals[BDFVar__IMM7 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_7e(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_727 = NULL;
	/*template:	11010100010 IMM16 00000  => INSN_OPCODE(I_HLT ISET_ARM64 FM_OS A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_727, I_HLT, ISET_ARM64, FM_OS, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_IMMEDIATE_0201(found, mcr_727, DATASZ_16b, READ, vals[BDFVar__IMM16 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_7f(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_727 = NULL;
	/*template:	11010100000 IMM16 00010  => INSN_OPCODE(I_HVC ISET_ARM64 FM_HW A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_727, I_HVC, ISET_ARM64, FM_HW, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_IMMEDIATE_0201(found, mcr_727, DATASZ_16b, READ, vals[BDFVar__IMM16 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_80(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_728 = NULL;
	/*template:	11010101000000110011 IMM4 11011111  => INSN_OPCODE(I_ISB ISET_ARM64 FM_SYNC A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_728, I_ISB, ISET_ARM64, FM_SYNC, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_IMMEDIATE_0201(found, mcr_728, DATASZ_4b, READ, vals[BDFVar__IMM4 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_81(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7c0 = NULL;
	/*template:	1101011001011111000000 RNn2l 00000  => INSN_OPCODE(I_RET ISET_ARM64 FM_RET A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_64b DATASZ_64b )*/
	(void)vals;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_7c0, I_RET, ISET_ARM64, FM_RET, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0210(found, mcr_7c0, DATASZ_DWORD, READ, vars[BDFVar__RNn2l]);}
	}
	return found;
}
int arm64_encoder_82(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_727 = NULL;
	/*template:	11010100000 IMM16 00011  => INSN_OPCODE(I_SMC ISET_ARM64 FM_OS A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_727, I_SMC, ISET_ARM64, FM_OS, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_IMMEDIATE_0201(found, mcr_727, DATASZ_16b, READ, vals[BDFVar__IMM16 - BDFVar__VARNUMBER]);}
	}
	return found;
}
#endif
#ifdef INSN_OPCODE_1a01
int arm64_encoder_83(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7b0 = NULL,*mcr_ffffff9b = NULL;
	/*template:	01010100 IMM19 0 CND  => INSN_OPCODE(I_B ISET_ARM64 FM_JUMP A_JUMP S_SCALAR T_UNDEF T_SINT DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a01(found, input, mcr_7b0, I_B, ISET_ARM64, FM_JUMP, A_JUMP, S_SCALAR, T_UNDEF, T_SINT, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, vals[BDFVar__CND - BDFVar__VARNUMBER]);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_POINTER_1200(found, mcr_7b0, mcr_ffffff9b, DATASZ_21b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {SIGNED_LEFT_SHIFT_0201(found, mcr_ffffff9b, DATASZ_UNDEF, TWO, vals[BDFVar__IMM19 - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
#endif
#ifdef INSN_OPCODE_2a00
int arm64_encoder_84(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_80d = NULL,*mcr_809 = NULL;
	/*template:	0111111011100000001110 RN RD  => INSN_OPCODE(I_USQADD ISET_ARM64 FM_ADD A_NA S_SCALAR T_UINT T_SINT DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_80d, mcr_809, I_USQADD, ISET_ARM64, FM_ADD, A_NA, S_SCALAR, T_UINT, T_SINT, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_80d, DATASZ_DWORD, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_809, DATASZ_DWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_85(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_823 = NULL,*mcr_81f = NULL;
	/*template:	0111111010100000001110 RN RD  => INSN_OPCODE(I_USQADD ISET_ARM64 FM_ADD A_NA S_SCALAR T_UINT T_SINT DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_823, mcr_81f, I_USQADD, ISET_ARM64, FM_ADD, A_NA, S_SCALAR, T_UINT, T_SINT, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_823, DATASZ_SWORD, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81f, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_86(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_810 = NULL,*mcr_813 = NULL;
	/*template:	0111111001100000001110 RN RD  => INSN_OPCODE(I_USQADD ISET_ARM64 FM_ADD A_NA S_SCALAR T_UINT T_SINT DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_810, mcr_813, I_USQADD, ISET_ARM64, FM_ADD, A_NA, S_SCALAR, T_UINT, T_SINT, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_810, DATASZ_HWORD, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_813, DATASZ_HWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_87(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_800 = NULL,*mcr_804 = NULL;
	/*template:	0111111000100000001110 RN RD  => INSN_OPCODE(I_USQADD ISET_ARM64 FM_ADD A_NA S_SCALAR T_UINT T_SINT DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_800, mcr_804, I_USQADD, ISET_ARM64, FM_ADD, A_NA, S_SCALAR, T_UINT, T_SINT, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_800, DATASZ_BYTE, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_804, DATASZ_BYTE, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_88(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81e = NULL,*mcr_809 = NULL;
	/*template:	0111111010100001010010 RN RD  => INSN_OPCODE(I_UQXTN ISET_ARM64 FM_MOV A_NA S_SCALAR T_UINT T_UINT DATASZ_32b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_81e, mcr_809, I_UQXTN, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_UINT, T_UINT, DATASZ_32b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81e, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_809, DATASZ_DWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_89(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_812 = NULL,*mcr_81f = NULL;
	/*template:	0111111001100001010010 RN RD  => INSN_OPCODE(I_UQXTN ISET_ARM64 FM_MOV A_NA S_SCALAR T_UINT T_UINT DATASZ_16b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_812, mcr_81f, I_UQXTN, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_UINT, T_UINT, DATASZ_16b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_812, DATASZ_HWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81f, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_8a(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_802 = NULL,*mcr_813 = NULL;
	/*template:	0111111000100001010010 RN RD  => INSN_OPCODE(I_UQXTN ISET_ARM64 FM_MOV A_NA S_SCALAR T_UINT T_UINT DATASZ_8b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_802, mcr_813, I_UQXTN, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_UINT, T_UINT, DATASZ_8b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_802, DATASZ_BYTE, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_813, DATASZ_HWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_8b(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_808 = NULL,*mcr_7b5 = NULL;
	/*template:	1001111001100011000000 RN RD  => INSN_OPCODE(I_UCVTF ISET_ARM64 FM_CVT A_NA S_SCALAR T_FP T_UINT DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_808, mcr_7b5, I_UCVTF, ISET_ARM64, FM_CVT, A_NA, S_SCALAR, T_FP, T_UINT, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_808, DATASZ_DWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_STACK_0201(found, mcr_7b5, DATASZ_DWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_8c(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81e = NULL,*mcr_7b5 = NULL;
	/*template:	1001111000100011000000 RN RD  => INSN_OPCODE(I_UCVTF ISET_ARM64 FM_CVT A_NA S_SCALAR T_FP T_UINT DATASZ_32b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_81e, mcr_7b5, I_UCVTF, ISET_ARM64, FM_CVT, A_NA, S_SCALAR, T_FP, T_UINT, DATASZ_32b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81e, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_STACK_0201(found, mcr_7b5, DATASZ_DWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_8d(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_808 = NULL,*mcr_82b = NULL;
	/*template:	0001111001100011000000 RN RD  => INSN_OPCODE(I_UCVTF ISET_ARM64 FM_CVT A_NA S_SCALAR T_FP T_UINT DATASZ_64b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_808, mcr_82b, I_UCVTF, ISET_ARM64, FM_CVT, A_NA, S_SCALAR, T_FP, T_UINT, DATASZ_64b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_808, DATASZ_DWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_STACK_0201(found, mcr_82b, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_8e(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81e = NULL,*mcr_82b = NULL;
	/*template:	0001111000100011000000 RN RD  => INSN_OPCODE(I_UCVTF ISET_ARM64 FM_CVT A_NA S_SCALAR T_FP T_UINT DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_81e, mcr_82b, I_UCVTF, ISET_ARM64, FM_CVT, A_NA, S_SCALAR, T_FP, T_UINT, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81e, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_STACK_0201(found, mcr_82b, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_8f(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_808 = NULL,*mcr_809 = NULL;
	/*template:	0111111001100001110110 RN RD  => INSN_OPCODE(I_UCVTF ISET_ARM64 FM_CVT A_NA S_SCALAR T_FP T_UINT DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_808, mcr_809, I_UCVTF, ISET_ARM64, FM_CVT, A_NA, S_SCALAR, T_FP, T_UINT, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_808, DATASZ_DWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_809, DATASZ_DWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_90(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81e = NULL,*mcr_81f = NULL;
	/*template:	0111111000100001110110 RN RD  => INSN_OPCODE(I_UCVTF ISET_ARM64 FM_CVT A_NA S_SCALAR T_FP T_UINT DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_81e, mcr_81f, I_UCVTF, ISET_ARM64, FM_CVT, A_NA, S_SCALAR, T_FP, T_UINT, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81e, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81f, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_91(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_80d = NULL,*mcr_809 = NULL;
	/*template:	0101111011100000001110 RN RD  => INSN_OPCODE(I_SUQADD ISET_ARM64 FM_ADD A_NA S_SCALAR T_UINT T_UINT DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_80d, mcr_809, I_SUQADD, ISET_ARM64, FM_ADD, A_NA, S_SCALAR, T_UINT, T_UINT, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_80d, DATASZ_DWORD, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_809, DATASZ_DWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_92(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_823 = NULL,*mcr_81f = NULL;
	/*template:	0101111010100000001110 RN RD  => INSN_OPCODE(I_SUQADD ISET_ARM64 FM_ADD A_NA S_SCALAR T_UINT T_UINT DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_823, mcr_81f, I_SUQADD, ISET_ARM64, FM_ADD, A_NA, S_SCALAR, T_UINT, T_UINT, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_823, DATASZ_SWORD, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81f, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_93(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_810 = NULL,*mcr_813 = NULL;
	/*template:	0101111001100000001110 RN RD  => INSN_OPCODE(I_SUQADD ISET_ARM64 FM_ADD A_NA S_SCALAR T_UINT T_UINT DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_810, mcr_813, I_SUQADD, ISET_ARM64, FM_ADD, A_NA, S_SCALAR, T_UINT, T_UINT, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_810, DATASZ_HWORD, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_813, DATASZ_HWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_94(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_800 = NULL,*mcr_804 = NULL;
	/*template:	0101111000100000001110 RN RD  => INSN_OPCODE(I_SUQADD ISET_ARM64 FM_ADD A_NA S_SCALAR T_UINT T_UINT DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_800, mcr_804, I_SUQADD, ISET_ARM64, FM_ADD, A_NA, S_SCALAR, T_UINT, T_UINT, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_800, DATASZ_BYTE, READ_WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_804, DATASZ_BYTE, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_95(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_763 = NULL;
	/*template:	01111000000 IMM9 00 RN RT  => INSN_OPCODE(I_STURH ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_763, I_STURH, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202(found, mcr_763, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_96(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_763 = NULL;
	/*template:	00111000000 IMM9 00 RN RT  => INSN_OPCODE(I_STURB ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_763, I_STURB, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202(found, mcr_763, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_97(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_816 = NULL,*mcr_763 = NULL;
	/*template:	00111100100 IMM9 00 RN RT  => INSN_OPCODE(I_STUR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_128b DATASZ_128b DATASZ_128b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_816, mcr_763, I_STUR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_128b, DATASZ_128b, DATASZ_128b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_QWORD_0201(found, mcr_816, DATASZ_QWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202(found, mcr_763, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_98(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_806 = NULL,*mcr_763 = NULL;
	/*template:	11111100000 IMM9 00 RN RT  => INSN_OPCODE(I_STUR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_806, mcr_763, I_STUR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_806, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202(found, mcr_763, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_99(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81c = NULL,*mcr_763 = NULL;
	/*template:	10111100000 IMM9 00 RN RT  => INSN_OPCODE(I_STUR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_81c, mcr_763, I_STUR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81c, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202(found, mcr_763, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_9a(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_811 = NULL,*mcr_763 = NULL;
	/*template:	01111100000 IMM9 00 RN RT  => INSN_OPCODE(I_STUR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_811, mcr_763, I_STUR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_811, DATASZ_HWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202(found, mcr_763, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_9b(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_801 = NULL,*mcr_763 = NULL;
	/*template:	00111100000 IMM9 00 RN RT  => INSN_OPCODE(I_STUR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_801, mcr_763, I_STUR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_801, DATASZ_BYTE, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202(found, mcr_763, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_9c(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7ba = NULL,*mcr_763 = NULL;
	/*template:	11111000000 IMM9 00 RN RT  => INSN_OPCODE(I_STUR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_7ba, mcr_763, I_STUR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0201(found, mcr_7ba, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202(found, mcr_763, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_9d(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_763 = NULL;
	/*template:	10111000000 IMM9 00 RN RT  => INSN_OPCODE(I_STUR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_763, I_STUR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202(found, mcr_763, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_9e(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_763 = NULL;
	/*template:	01111000000 IMM9 10 RN RT  => INSN_OPCODE(I_STTRH ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_763, I_STTRH, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202(found, mcr_763, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_9f(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_763 = NULL;
	/*template:	00111000000 IMM9 10 RN RT  => INSN_OPCODE(I_STTRB ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_763, I_STTRB, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202(found, mcr_763, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_a0(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7ba = NULL,*mcr_763 = NULL;
	/*template:	11111000000 IMM9 10 RN RT  => INSN_OPCODE(I_STTR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_7ba, mcr_763, I_STTR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0201(found, mcr_7ba, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202(found, mcr_763, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_a1(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_763 = NULL;
	/*template:	10111000000 IMM9 10 RN RT  => INSN_OPCODE(I_STTR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_763, I_STTR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_0202(found, mcr_763, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_a2(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_74f = NULL,*mcr_ffffffe3 = NULL;
	/*template:	01111000001 RM 011 S 10 RN RT  => INSN_OPCODE(I_STRH ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_74f, I_STRH, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_74f, mcr_ffffffe3, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_0201(found, mcr_ffffffe3, DATASZ_UNDEF, LSL, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_a3(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_750 = NULL,*mcr_ffffffe4 = NULL;
	/*template:	01111000001 RM 111 S 10 RN RT  => INSN_OPCODE(I_STRH ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_750, I_STRH, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_750, mcr_ffffffe4, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_0201(found, mcr_ffffffe4, DATASZ_UNDEF, SXTX, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_a4(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_77c = NULL,*mcr_ffffffe6 = NULL;
	/*template:	01111000001 RM EXTw S 10 RN RT  => INSN_OPCODE(I_STRH ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_77c, I_STRH, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SWORD_REGISTER_INDEX_1202(found, mcr_77c, mcr_ffffffe6, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_0111(found, mcr_ffffffe6, DATASZ_UNDEF, vars[BDFVar__EXTw], vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_a5(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_788 = NULL,*mcr_ffffffb2 = NULL;
	/*template:	0111100100 IMM12 RN RT  => INSN_OPCODE(I_STRH ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_788, I_STRH, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_UNSIGNED_IMMEDIATE_INDEX_1201(found, mcr_788, mcr_ffffffb2, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb2, DATASZ_UNDEF, ONE, vals[BDFVar__IMM12 - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_a6(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_76b = NULL;
	/*template:	01111000000 IMM9 11 RN RT  => INSN_OPCODE(I_STRH ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_76b, I_STRH, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_WRITEBACK_0202(found, mcr_76b, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_a7(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_773 = NULL;
	/*template:	01111000000 IMM9 01 RN RT  => INSN_OPCODE(I_STRH ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_773, I_STRH, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_POST_INDEX_0202(found, mcr_773, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_a8(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_751 = NULL,*mcr_ffffffe1 = NULL;
	/*template:	00111000001 RM 011010 RN RT  => INSN_OPCODE(I_STRB ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_751, I_STRB, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_751, mcr_ffffffe1, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_0300(found, mcr_ffffffe1, DATASZ_UNDEF, LSL, CI0);}
	}
	}
	return found;
}
int arm64_encoder_a9(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_752 = NULL,*mcr_ffffffe5 = NULL;
	/*template:	00111000001 RM 111010 RN RT  => INSN_OPCODE(I_STRB ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_752, I_STRB, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_752, mcr_ffffffe5, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_0200(found, mcr_ffffffe5, DATASZ_UNDEF, SXTX);}
	}
	}
	return found;
}
int arm64_encoder_aa(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_77d = NULL,*mcr_ffffffe9 = NULL;
	/*template:	00111000001 RM EXTw 010 RN RT  => INSN_OPCODE(I_STRB ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_77d, I_STRB, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SWORD_REGISTER_INDEX_1202(found, mcr_77d, mcr_ffffffe9, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_0110(found, mcr_ffffffe9, DATASZ_UNDEF, vars[BDFVar__EXTw]);}
	}
	}
	return found;
}
int arm64_encoder_ab(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_785 = NULL;
	/*template:	0011100100 IMM12 RN RT  => INSN_OPCODE(I_STRB ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_785, I_STRB, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_UNSIGNED_IMMEDIATE_INDEX_0202(found, mcr_785, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM12 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_ac(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_76b = NULL;
	/*template:	00111000000 IMM9 11 RN RT  => INSN_OPCODE(I_STRB ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_76b, I_STRB, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_WRITEBACK_0202(found, mcr_76b, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_ad(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_773 = NULL;
	/*template:	00111000000 IMM9 01 RN RT  => INSN_OPCODE(I_STRB ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_773, I_STRB, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_POST_INDEX_0202(found, mcr_773, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_ae(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_816 = NULL,*mcr_74d = NULL,*mcr_ffffffd8 = NULL,*mcr_ffffffb0 = NULL;
	/*template:	00111100101 RM 011 S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_128b DATASZ_128b DATASZ_128b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_816, mcr_74d, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_128b, DATASZ_128b, DATASZ_128b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_QWORD_0201(found, mcr_816, DATASZ_QWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_74d, mcr_ffffffd8, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffd8, mcr_ffffffb0, DATASZ_UNDEF, LSL);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb0, DATASZ_UNDEF, TWO, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_af(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_816 = NULL,*mcr_74e = NULL,*mcr_ffffffd9 = NULL,*mcr_ffffffb0 = NULL;
	/*template:	00111100101 RM 111 S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_128b DATASZ_128b DATASZ_128b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_816, mcr_74e, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_128b, DATASZ_128b, DATASZ_128b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_QWORD_0201(found, mcr_816, DATASZ_QWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_74e, mcr_ffffffd9, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffd9, mcr_ffffffb0, DATASZ_UNDEF, SXTX);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb0, DATASZ_UNDEF, TWO, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_b0(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_816 = NULL,*mcr_77b = NULL,*mcr_ffffffde = NULL,*mcr_ffffffb0 = NULL;
	/*template:	00111100101 RM EXTw S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_128b DATASZ_128b DATASZ_128b )*/
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_816, mcr_77b, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_128b, DATASZ_128b, DATASZ_128b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_QWORD_0201(found, mcr_816, DATASZ_QWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SWORD_REGISTER_INDEX_1202(found, mcr_77b, mcr_ffffffde, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1110(found, mcr_ffffffde, mcr_ffffffb0, DATASZ_UNDEF, vars[BDFVar__EXTw]);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb0, DATASZ_UNDEF, TWO, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_b1(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_806 = NULL,*mcr_753 = NULL,*mcr_ffffffda = NULL,*mcr_ffffffc7 = NULL;
	/*template:	11111100001 RM 011 S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_806, mcr_753, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_806, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_753, mcr_ffffffda, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffda, mcr_ffffffc7, DATASZ_UNDEF, LSL);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffc7, DATASZ_UNDEF, ONE, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_b2(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_806 = NULL,*mcr_754 = NULL,*mcr_ffffffdb = NULL,*mcr_ffffffc7 = NULL;
	/*template:	11111100001 RM 111 S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_806, mcr_754, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_806, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_754, mcr_ffffffdb, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffdb, mcr_ffffffc7, DATASZ_UNDEF, SXTX);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffc7, DATASZ_UNDEF, ONE, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_b3(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_806 = NULL,*mcr_77e = NULL,*mcr_ffffffdf = NULL,*mcr_ffffffc7 = NULL;
	/*template:	11111100001 RM EXTw S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_806, mcr_77e, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_806, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SWORD_REGISTER_INDEX_1202(found, mcr_77e, mcr_ffffffdf, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1110(found, mcr_ffffffdf, mcr_ffffffc7, DATASZ_UNDEF, vars[BDFVar__EXTw]);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffc7, DATASZ_UNDEF, ONE, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_b4(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81c = NULL,*mcr_755 = NULL,*mcr_ffffffdc = NULL,*mcr_ffffffb3 = NULL;
	/*template:	10111100001 RM 011 S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_81c, mcr_755, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81c, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_755, mcr_ffffffdc, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffdc, mcr_ffffffb3, DATASZ_UNDEF, LSL);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb3, DATASZ_UNDEF, ONE, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_b5(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81c = NULL,*mcr_756 = NULL,*mcr_ffffffdd = NULL,*mcr_ffffffb3 = NULL;
	/*template:	10111100001 RM 111 S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_81c, mcr_756, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81c, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_756, mcr_ffffffdd, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffdd, mcr_ffffffb3, DATASZ_UNDEF, SXTX);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb3, DATASZ_UNDEF, ONE, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_b6(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81c = NULL,*mcr_77f = NULL,*mcr_ffffffe0 = NULL,*mcr_ffffffb3 = NULL;
	/*template:	10111100001 RM EXTw S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_81c, mcr_77f, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81c, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SWORD_REGISTER_INDEX_1202(found, mcr_77f, mcr_ffffffe0, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1110(found, mcr_ffffffe0, mcr_ffffffb3, DATASZ_UNDEF, vars[BDFVar__EXTw]);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb3, DATASZ_UNDEF, ONE, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_b7(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_811 = NULL,*mcr_74f = NULL,*mcr_ffffffe3 = NULL;
	/*template:	01111100001 RM 011 S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_811, mcr_74f, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_811, DATASZ_HWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_74f, mcr_ffffffe3, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_0201(found, mcr_ffffffe3, DATASZ_UNDEF, LSL, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_b8(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_811 = NULL,*mcr_750 = NULL,*mcr_ffffffe4 = NULL;
	/*template:	01111100001 RM 111 S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_811, mcr_750, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_811, DATASZ_HWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_750, mcr_ffffffe4, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_0201(found, mcr_ffffffe4, DATASZ_UNDEF, SXTX, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_b9(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_811 = NULL,*mcr_77c = NULL,*mcr_ffffffe6 = NULL;
	/*template:	01111100001 RM EXTw S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_811, mcr_77c, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_811, DATASZ_HWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SWORD_REGISTER_INDEX_1202(found, mcr_77c, mcr_ffffffe6, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_0111(found, mcr_ffffffe6, DATASZ_UNDEF, vars[BDFVar__EXTw], vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_ba(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_801 = NULL,*mcr_751 = NULL,*mcr_ffffffe1 = NULL;
	/*template:	00111100001 RM 011010 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_801, mcr_751, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_801, DATASZ_BYTE, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_751, mcr_ffffffe1, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_0300(found, mcr_ffffffe1, DATASZ_UNDEF, LSL, CI0);}
	}
	}
	return found;
}
int arm64_encoder_bb(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_801 = NULL,*mcr_752 = NULL,*mcr_ffffffe5 = NULL;
	/*template:	00111100001 RM 111010 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_801, mcr_752, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_801, DATASZ_BYTE, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_752, mcr_ffffffe5, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_0200(found, mcr_ffffffe5, DATASZ_UNDEF, SXTX);}
	}
	}
	return found;
}
int arm64_encoder_bc(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_801 = NULL,*mcr_77d = NULL,*mcr_ffffffe9 = NULL;
	/*template:	00111100001 RM EXTw 010 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_801, mcr_77d, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_801, DATASZ_BYTE, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SWORD_REGISTER_INDEX_1202(found, mcr_77d, mcr_ffffffe9, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_0110(found, mcr_ffffffe9, DATASZ_UNDEF, vars[BDFVar__EXTw]);}
	}
	}
	return found;
}
int arm64_encoder_bd(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_816 = NULL,*mcr_787 = NULL,*mcr_ffffffb1 = NULL;
	/*template:	0011110110 IMM12 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_128b DATASZ_128b DATASZ_128b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_816, mcr_787, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_128b, DATASZ_128b, DATASZ_128b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_QWORD_0201(found, mcr_816, DATASZ_QWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_UNSIGNED_IMMEDIATE_INDEX_1201(found, mcr_787, mcr_ffffffb1, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb1, DATASZ_UNDEF, FOUR, vals[BDFVar__IMM12 - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_be(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_806 = NULL,*mcr_789 = NULL,*mcr_ffffffb4 = NULL;
	/*template:	1111110100 IMM12 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_806, mcr_789, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_806, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_UNSIGNED_IMMEDIATE_INDEX_1201(found, mcr_789, mcr_ffffffb4, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb4, DATASZ_UNDEF, THREE, vals[BDFVar__IMM12 - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_bf(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81c = NULL,*mcr_78a = NULL,*mcr_ffffffb5 = NULL;
	/*template:	1011110100 IMM12 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_81c, mcr_78a, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81c, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_UNSIGNED_IMMEDIATE_INDEX_1201(found, mcr_78a, mcr_ffffffb5, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb5, DATASZ_UNDEF, TWO, vals[BDFVar__IMM12 - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_c0(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_811 = NULL,*mcr_788 = NULL,*mcr_ffffffb2 = NULL;
	/*template:	0111110100 IMM12 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_811, mcr_788, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_811, DATASZ_HWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_UNSIGNED_IMMEDIATE_INDEX_1201(found, mcr_788, mcr_ffffffb2, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb2, DATASZ_UNDEF, ONE, vals[BDFVar__IMM12 - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_c1(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_801 = NULL,*mcr_785 = NULL;
	/*template:	0011110100 IMM12 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_801, mcr_785, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_801, DATASZ_BYTE, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_UNSIGNED_IMMEDIATE_INDEX_0202(found, mcr_785, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM12 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_c2(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_816 = NULL,*mcr_76b = NULL;
	/*template:	00111100100 IMM9 11 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_128b DATASZ_128b DATASZ_128b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_816, mcr_76b, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_128b, DATASZ_128b, DATASZ_128b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_QWORD_0201(found, mcr_816, DATASZ_QWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_WRITEBACK_0202(found, mcr_76b, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_c3(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_806 = NULL,*mcr_76b = NULL;
	/*template:	11111100000 IMM9 11 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_806, mcr_76b, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_806, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_WRITEBACK_0202(found, mcr_76b, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_c4(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81c = NULL,*mcr_76b = NULL;
	/*template:	10111100000 IMM9 11 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_81c, mcr_76b, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81c, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_WRITEBACK_0202(found, mcr_76b, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_c5(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_811 = NULL,*mcr_76b = NULL;
	/*template:	01111100000 IMM9 11 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_811, mcr_76b, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_811, DATASZ_HWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_WRITEBACK_0202(found, mcr_76b, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_c6(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_801 = NULL,*mcr_76b = NULL;
	/*template:	00111100000 IMM9 11 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_801, mcr_76b, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_801, DATASZ_BYTE, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_WRITEBACK_0202(found, mcr_76b, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_c7(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_816 = NULL,*mcr_773 = NULL;
	/*template:	00111100100 IMM9 01 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_128b DATASZ_128b DATASZ_128b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_816, mcr_773, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_128b, DATASZ_128b, DATASZ_128b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_QWORD_0201(found, mcr_816, DATASZ_QWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_POST_INDEX_0202(found, mcr_773, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_c8(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_806 = NULL,*mcr_773 = NULL;
	/*template:	11111100000 IMM9 01 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_806, mcr_773, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_806, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_POST_INDEX_0202(found, mcr_773, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_c9(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81c = NULL,*mcr_773 = NULL;
	/*template:	10111100000 IMM9 01 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_81c, mcr_773, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81c, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_POST_INDEX_0202(found, mcr_773, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_ca(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_811 = NULL,*mcr_773 = NULL;
	/*template:	01111100000 IMM9 01 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_811, mcr_773, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_811, DATASZ_HWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_POST_INDEX_0202(found, mcr_773, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_cb(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_801 = NULL,*mcr_773 = NULL;
	/*template:	00111100000 IMM9 01 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SIMD T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_801, mcr_773, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SIMD, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_801, DATASZ_BYTE, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_POST_INDEX_0202(found, mcr_773, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_cc(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7ba = NULL,*mcr_753 = NULL,*mcr_ffffffda = NULL,*mcr_ffffffc7 = NULL;
	/*template:	11111000001 RM 011 S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_7ba, mcr_753, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0201(found, mcr_7ba, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_753, mcr_ffffffda, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffda, mcr_ffffffc7, DATASZ_UNDEF, LSL);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffc7, DATASZ_UNDEF, ONE, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_cd(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7ba = NULL,*mcr_754 = NULL,*mcr_ffffffdb = NULL,*mcr_ffffffc7 = NULL;
	/*template:	11111000001 RM 111 S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_7ba, mcr_754, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0201(found, mcr_7ba, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_754, mcr_ffffffdb, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffdb, mcr_ffffffc7, DATASZ_UNDEF, SXTX);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffc7, DATASZ_UNDEF, ONE, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_ce(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7ba = NULL,*mcr_77e = NULL,*mcr_ffffffdf = NULL,*mcr_ffffffc7 = NULL;
	/*template:	11111000001 RM EXTw S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_7ba, mcr_77e, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0201(found, mcr_7ba, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SWORD_REGISTER_INDEX_1202(found, mcr_77e, mcr_ffffffdf, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1110(found, mcr_ffffffdf, mcr_ffffffc7, DATASZ_UNDEF, vars[BDFVar__EXTw]);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_FILL_0201(found, mcr_ffffffc7, DATASZ_UNDEF, ONE, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_cf(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_755 = NULL,*mcr_ffffffdc = NULL,*mcr_ffffffb3 = NULL;
	/*template:	10111000001 RM 011 S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_755, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_755, mcr_ffffffdc, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffdc, mcr_ffffffb3, DATASZ_UNDEF, LSL);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb3, DATASZ_UNDEF, ONE, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_d0(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_756 = NULL,*mcr_ffffffdd = NULL,*mcr_ffffffb3 = NULL;
	/*template:	10111000001 RM 111 S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_756, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_DWORD_REGISTER_INDEX_1202(found, mcr_756, mcr_ffffffdd, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1200(found, mcr_ffffffdd, mcr_ffffffb3, DATASZ_UNDEF, SXTX);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb3, DATASZ_UNDEF, ONE, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_d1(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_77f = NULL,*mcr_ffffffe0 = NULL,*mcr_ffffffb3 = NULL;
	/*template:	10111000001 RM EXTw S 10 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_77f, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SWORD_REGISTER_INDEX_1202(found, mcr_77f, mcr_ffffffe0, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__RM - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {EXTEND_1110(found, mcr_ffffffe0, mcr_ffffffb3, DATASZ_UNDEF, vars[BDFVar__EXTw]);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb3, DATASZ_UNDEF, ONE, vals[BDFVar__S - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_d2(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7ba = NULL,*mcr_789 = NULL,*mcr_ffffffb4 = NULL;
	/*template:	1111100100 IMM12 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_7ba, mcr_789, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0201(found, mcr_7ba, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_UNSIGNED_IMMEDIATE_INDEX_1201(found, mcr_789, mcr_ffffffb4, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb4, DATASZ_UNDEF, THREE, vals[BDFVar__IMM12 - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_d3(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_78a = NULL,*mcr_ffffffb5 = NULL;
	/*template:	1011100100 IMM12 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_78a, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_UNSIGNED_IMMEDIATE_INDEX_1201(found, mcr_78a, mcr_ffffffb5, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffb5, DATASZ_UNDEF, TWO, vals[BDFVar__IMM12 - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_d4(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7ba = NULL,*mcr_76b = NULL;
	/*template:	11111000000 IMM9 11 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_7ba, mcr_76b, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0201(found, mcr_7ba, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_WRITEBACK_0202(found, mcr_76b, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_d5(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_76b = NULL;
	/*template:	10111000000 IMM9 11 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_76b, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_INDEX_WRITEBACK_0202(found, mcr_76b, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_d6(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7ba = NULL,*mcr_773 = NULL;
	/*template:	11111000000 IMM9 01 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_7ba, mcr_773, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0201(found, mcr_7ba, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_POST_INDEX_0202(found, mcr_773, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_d7(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_773 = NULL;
	/*template:	10111000000 IMM9 01 RN RT  => INSN_OPCODE(I_STR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_773, I_STR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_SIGNED_IMMEDIATE_POST_INDEX_0202(found, mcr_773, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER], vals[BDFVar__IMM9 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_d8(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_74a = NULL;
	/*template:	0100100010011111111111 RN RT  => INSN_OPCODE(I_STLRH ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_16b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_74a, I_STLRH, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_16b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_0201(found, mcr_74a, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_d9(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_74a = NULL;
	/*template:	0000100010011111111111 RN RT  => INSN_OPCODE(I_STLRB ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_8b DATASZ_8b DATASZ_8b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_74a, I_STLRB, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_8b, DATASZ_8b, DATASZ_8b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_0201(found, mcr_74a, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_da(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7ba = NULL,*mcr_74a = NULL;
	/*template:	1100100010011111111111 RN RT  => INSN_OPCODE(I_STLR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_7ba, mcr_74a, I_STLR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0201(found, mcr_7ba, DATASZ_DWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_0201(found, mcr_74a, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_db(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_74a = NULL;
	/*template:	1000100010011111111111 RN RT  => INSN_OPCODE(I_STLR ISET_ARM64 FM_STORE A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_32b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_74a, I_STLR, ISET_ARM64, FM_STORE, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_32b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_MEMORY_0201(found, mcr_74a, DATASZ_32b, WRITE, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_dc(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81e = NULL,*mcr_809 = NULL;
	/*template:	0111111010100001001010 RN RD  => INSN_OPCODE(I_SQXTUN ISET_ARM64 FM_MOV A_NA S_SCALAR T_UINT T_SINT DATASZ_32b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_81e, mcr_809, I_SQXTUN, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_UINT, T_SINT, DATASZ_32b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81e, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_809, DATASZ_DWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_dd(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_812 = NULL,*mcr_81f = NULL;
	/*template:	0111111001100001001010 RN RD  => INSN_OPCODE(I_SQXTUN ISET_ARM64 FM_MOV A_NA S_SCALAR T_UINT T_SINT DATASZ_16b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_812, mcr_81f, I_SQXTUN, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_UINT, T_SINT, DATASZ_16b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_812, DATASZ_HWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81f, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_de(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_802 = NULL,*mcr_813 = NULL;
	/*template:	0111111000100001001010 RN RD  => INSN_OPCODE(I_SQXTUN ISET_ARM64 FM_MOV A_NA S_SCALAR T_UINT T_SINT DATASZ_8b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_802, mcr_813, I_SQXTUN, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_UINT, T_SINT, DATASZ_8b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_802, DATASZ_BYTE, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_813, DATASZ_HWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_df(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_81e = NULL,*mcr_809 = NULL;
	/*template:	01011111010100001010010 RN RD  => INSN_OPCODE(I_SQXTN ISET_ARM64 FM_MOV A_NA S_SCALAR T_SINT T_SINT DATASZ_32b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_81e, mcr_809, I_SQXTN, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_SINT, T_SINT, DATASZ_32b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81e, DATASZ_SWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_809, DATASZ_DWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_e0(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_812 = NULL,*mcr_81f = NULL;
	/*template:	01011111001100001010010 RN RD  => INSN_OPCODE(I_SQXTN ISET_ARM64 FM_MOV A_NA S_SCALAR T_SINT T_SINT DATASZ_16b DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_812, mcr_81f, I_SQXTN, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_SINT, T_SINT, DATASZ_16b, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_812, DATASZ_HWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_SWORD_0201(found, mcr_81f, DATASZ_SWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_e1(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_802 = NULL,*mcr_813 = NULL;
	/*template:	01011111000100001010010 RN RD  => INSN_OPCODE(I_SQXTN ISET_ARM64 FM_MOV A_NA S_SCALAR T_SINT T_SINT DATASZ_8b DATASZ_16b DATASZ_16b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_802, mcr_813, I_SQXTN, ISET_ARM64, FM_MOV, A_NA, S_SCALAR, T_SINT, T_SINT, DATASZ_8b, DATASZ_16b, DATASZ_16b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_BYTE_0201(found, mcr_802, DATASZ_BYTE, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_HWORD_0201(found, mcr_813, DATASZ_HWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_e2(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_808 = NULL,*mcr_809 = NULL;
	/*template:	0101111011100000101110 RN RD  => INSN_OPCODE(I_ABS ISET_ARM64 FM_ABS A_NA S_SCALAR T_INT T_SINT DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_808, mcr_809, I_ABS, ISET_ARM64, FM_ABS, A_NA, S_SCALAR, T_INT, T_SINT, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_808, DATASZ_DWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_REGISTER_SIMD_SCALAR_DWORD_0201(found, mcr_809, DATASZ_DWORD, READ, vals[BDFVar__RN - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_e3(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7b7 = NULL,*mcr_7ae = NULL,*mcr_fffffffa = NULL;
	/*template:	0 IMM2 10000 IMM19 RD  => INSN_OPCODE(I_ADR ISET_ARM64 FM_ADD A_NA S_SCALAR T_SINT T_SINT DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_7b7, mcr_7ae, I_ADR, ISET_ARM64, FM_ADD, A_NA, S_SCALAR, T_SINT, T_SINT, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0201(found, mcr_7b7, DATASZ_DWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_POINTER_1200(found, mcr_7ae, mcr_fffffffa, DATASZ_21b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_0102(found, mcr_fffffffa, DATASZ_UNDEF, vals[BDFVar__IMM19 - BDFVar__VARNUMBER], vals[BDFVar__IMM2 - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_e4(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7b7 = NULL,*mcr_7af = NULL,*mcr_ffffffab = NULL,*mcr_fffffffa = NULL;
	/*template:	1 IMM2 10000 IMM19 RD  => INSN_OPCODE(I_ADRP ISET_ARM64 FM_ADD A_NA S_SCALAR T_SINT T_SINT DATASZ_64b DATASZ_64b DATASZ_64b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_7b7, mcr_7af, I_ADRP, ISET_ARM64, FM_ADD, A_NA, S_SCALAR, T_SINT, T_SINT, DATASZ_64b, DATASZ_64b, DATASZ_64b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_DWORD_OR_ZERO_0201(found, mcr_7b7, DATASZ_DWORD, WRITE, vals[BDFVar__RD - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_POINTER_1200(found, mcr_7af, mcr_ffffffab, DATASZ_21b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_1200(found, mcr_ffffffab, mcr_fffffffa, DATASZ_UNDEF, TWELVE);}
	if (found == TRUE) {
		if (found == TRUE) {CONCATENATE_0102(found, mcr_fffffffa, DATASZ_UNDEF, vals[BDFVar__IMM19 - BDFVar__VARNUMBER], vals[BDFVar__IMM2 - BDFVar__VARNUMBER]);}
	}
	}
	}
	return found;
}
int arm64_encoder_e5(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_832 = NULL,*mcr_7b3 = NULL,*mcr_ffffffbc = NULL;
	/*template:	00110101 IMM19 RT  => INSN_OPCODE(I_CBNZ ISET_ARM64 FM_CJUMP A_NA S_SCALAR T_UNDEF T_INT DATASZ_UNDEF DATASZ_32b DATASZ_32b )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_2a00(found, input, mcr_832, mcr_7b3, I_CBNZ, ISET_ARM64, FM_CJUMP, A_NA, S_SCALAR, T_UNDEF, T_INT, DATASZ_UNDEF, DATASZ_32b, DATASZ_32b);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_REGISTER_SWORD_OR_ZERO_0201(found, mcr_832, DATASZ_SWORD, READ, vals[BDFVar__RT - BDFVar__VARNUMBER]);}
		if (found == TRUE) {OPRN_POINTER_1200(found, mcr_7b3, mcr_ffffffbc, DATASZ_21b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffbc, DATASZ_UNDEF, TWO, vals[BDFVar__IMM19 - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
#endif
