/*
   Copyright (C) 2004 - 2018 Université de Versailles Saint-Quentin-en-Yvelines (UVSQ)

   This file is part of MAQAO.

  MAQAO is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public License
   as published by the Free Software Foundation; either version 3
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */


/**
* \file arm64_revfct_0.c
* \brief This file contains the bodies of functions for reversing the semantic actions
* \warning This file has been automatically generated by MINJAG from file arm64_6bf96bbfcca0afd1af78d50ba75869a8.bdf and should not be modified
* */
#include <stdlib.h>
#include "arm64_arch.h"
#include "arm64_sym.h"
#include "asmblutils.h"
#include "arm64_revmacros.h"
#include "arm64_revfct.h"
#ifdef BIN_VAL_0_0000
int arm64_encoder_1(void* input, void** vars, paramcoding_t* vals) {
	/*EXTnx:	000  => BIN_VAL_0()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_0_0000(found, input);
	return found;
}
int arm64_encoder_2(void* input, void** vars, paramcoding_t* vals) {
	/*SHFT:	00  => BIN_VAL_0()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_0_0000(found, input);
	return found;
}
int arm64_encoder_3(void* input, void** vars, paramcoding_t* vals) {
	/*AS:	00  => BIN_VAL_0()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_0_0000(found, input);
	return found;
}
int arm64_encoder_4(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	00000  => BIN_VAL_0()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_0_0000(found, input);
	return found;
}
int arm64_encoder_5(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	00000  => BIN_VAL_0()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_0_0000(found, input);
	return found;
}
int arm64_encoder_6(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	00000  => BIN_VAL_0()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_0_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_10_0000
int arm64_encoder_7(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	01010  => BIN_VAL_10()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_10_0000(found, input);
	return found;
}
int arm64_encoder_8(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	01010  => BIN_VAL_10()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_10_0000(found, input);
	return found;
}
int arm64_encoder_9(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	01010  => BIN_VAL_10()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_10_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_11_0000
int arm64_encoder_a(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	01011  => BIN_VAL_11()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_11_0000(found, input);
	return found;
}
int arm64_encoder_b(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	01011  => BIN_VAL_11()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_11_0000(found, input);
	return found;
}
int arm64_encoder_c(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	01011  => BIN_VAL_11()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_11_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_12_0000
int arm64_encoder_d(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	01100  => BIN_VAL_12()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_12_0000(found, input);
	return found;
}
int arm64_encoder_e(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	01100  => BIN_VAL_12()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_12_0000(found, input);
	return found;
}
int arm64_encoder_f(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	01100  => BIN_VAL_12()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_12_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_13_0000
int arm64_encoder_10(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	01101  => BIN_VAL_13()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_13_0000(found, input);
	return found;
}
int arm64_encoder_11(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	01101  => BIN_VAL_13()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_13_0000(found, input);
	return found;
}
int arm64_encoder_12(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	01101  => BIN_VAL_13()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_13_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_14_0000
int arm64_encoder_13(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	01110  => BIN_VAL_14()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_14_0000(found, input);
	return found;
}
int arm64_encoder_14(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	01110  => BIN_VAL_14()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_14_0000(found, input);
	return found;
}
int arm64_encoder_15(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	01110  => BIN_VAL_14()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_14_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_15_0000
int arm64_encoder_16(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	01111  => BIN_VAL_15()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_15_0000(found, input);
	return found;
}
int arm64_encoder_17(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	01111  => BIN_VAL_15()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_15_0000(found, input);
	return found;
}
int arm64_encoder_18(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	01111  => BIN_VAL_15()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_15_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_16_0000
int arm64_encoder_19(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	10000  => BIN_VAL_16()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_16_0000(found, input);
	return found;
}
int arm64_encoder_1a(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	10000  => BIN_VAL_16()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_16_0000(found, input);
	return found;
}
int arm64_encoder_1b(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	10000  => BIN_VAL_16()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_16_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_17_0000
int arm64_encoder_1c(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	10001  => BIN_VAL_17()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_17_0000(found, input);
	return found;
}
int arm64_encoder_1d(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	10001  => BIN_VAL_17()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_17_0000(found, input);
	return found;
}
int arm64_encoder_1e(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	10001  => BIN_VAL_17()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_17_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_18_0000
int arm64_encoder_1f(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	10010  => BIN_VAL_18()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_18_0000(found, input);
	return found;
}
int arm64_encoder_20(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	10010  => BIN_VAL_18()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_18_0000(found, input);
	return found;
}
int arm64_encoder_21(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	10010  => BIN_VAL_18()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_18_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_19_0000
int arm64_encoder_22(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	10011  => BIN_VAL_19()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_19_0000(found, input);
	return found;
}
int arm64_encoder_23(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	10011  => BIN_VAL_19()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_19_0000(found, input);
	return found;
}
int arm64_encoder_24(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	10011  => BIN_VAL_19()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_19_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_1_0000
int arm64_encoder_25(void* input, void** vars, paramcoding_t* vals) {
	/*EXTnx:	001  => BIN_VAL_1()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_1_0000(found, input);
	return found;
}
int arm64_encoder_26(void* input, void** vars, paramcoding_t* vals) {
	/*SHFT:	01  => BIN_VAL_1()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_1_0000(found, input);
	return found;
}
int arm64_encoder_27(void* input, void** vars, paramcoding_t* vals) {
	/*AS:	01  => BIN_VAL_1()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_1_0000(found, input);
	return found;
}
int arm64_encoder_28(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	00001  => BIN_VAL_1()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_1_0000(found, input);
	return found;
}
int arm64_encoder_29(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	00001  => BIN_VAL_1()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_1_0000(found, input);
	return found;
}
int arm64_encoder_2a(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	00001  => BIN_VAL_1()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_1_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_20_0000
int arm64_encoder_2b(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	10100  => BIN_VAL_20()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_20_0000(found, input);
	return found;
}
int arm64_encoder_2c(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	10100  => BIN_VAL_20()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_20_0000(found, input);
	return found;
}
int arm64_encoder_2d(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	10100  => BIN_VAL_20()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_20_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_21_0000
int arm64_encoder_2e(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	10101  => BIN_VAL_21()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_21_0000(found, input);
	return found;
}
int arm64_encoder_2f(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	10101  => BIN_VAL_21()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_21_0000(found, input);
	return found;
}
int arm64_encoder_30(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	10101  => BIN_VAL_21()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_21_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_22_0000
int arm64_encoder_31(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	10110  => BIN_VAL_22()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_22_0000(found, input);
	return found;
}
int arm64_encoder_32(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	10110  => BIN_VAL_22()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_22_0000(found, input);
	return found;
}
int arm64_encoder_33(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	10110  => BIN_VAL_22()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_22_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_23_0000
int arm64_encoder_34(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	10111  => BIN_VAL_23()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_23_0000(found, input);
	return found;
}
int arm64_encoder_35(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	10111  => BIN_VAL_23()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_23_0000(found, input);
	return found;
}
int arm64_encoder_36(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	10111  => BIN_VAL_23()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_23_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_24_0000
int arm64_encoder_37(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	11000  => BIN_VAL_24()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_24_0000(found, input);
	return found;
}
int arm64_encoder_38(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	11000  => BIN_VAL_24()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_24_0000(found, input);
	return found;
}
int arm64_encoder_39(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	11000  => BIN_VAL_24()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_24_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_25_0000
int arm64_encoder_3a(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	11001  => BIN_VAL_25()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_25_0000(found, input);
	return found;
}
int arm64_encoder_3b(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	11001  => BIN_VAL_25()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_25_0000(found, input);
	return found;
}
int arm64_encoder_3c(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	11001  => BIN_VAL_25()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_25_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_26_0000
int arm64_encoder_3d(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	11010  => BIN_VAL_26()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_26_0000(found, input);
	return found;
}
int arm64_encoder_3e(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	11010  => BIN_VAL_26()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_26_0000(found, input);
	return found;
}
int arm64_encoder_3f(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	11010  => BIN_VAL_26()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_26_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_27_0000
int arm64_encoder_40(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	11011  => BIN_VAL_27()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_27_0000(found, input);
	return found;
}
int arm64_encoder_41(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	11011  => BIN_VAL_27()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_27_0000(found, input);
	return found;
}
int arm64_encoder_42(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	11011  => BIN_VAL_27()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_27_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_28_0000
int arm64_encoder_43(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	11100  => BIN_VAL_28()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_28_0000(found, input);
	return found;
}
int arm64_encoder_44(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	11100  => BIN_VAL_28()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_28_0000(found, input);
	return found;
}
int arm64_encoder_45(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	11100  => BIN_VAL_28()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_28_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_29_0000
int arm64_encoder_46(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	11101  => BIN_VAL_29()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_29_0000(found, input);
	return found;
}
int arm64_encoder_47(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	11101  => BIN_VAL_29()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_29_0000(found, input);
	return found;
}
int arm64_encoder_48(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	11101  => BIN_VAL_29()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_29_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_2_0000
int arm64_encoder_49(void* input, void** vars, paramcoding_t* vals) {
	/*EXTnx:	010  => BIN_VAL_2()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_2_0000(found, input);
	return found;
}
int arm64_encoder_4a(void* input, void** vars, paramcoding_t* vals) {
	/*EXTw:	010  => BIN_VAL_2()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_2_0000(found, input);
	return found;
}
int arm64_encoder_4b(void* input, void** vars, paramcoding_t* vals) {
	/*SHFT:	10  => BIN_VAL_2()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_2_0000(found, input);
	return found;
}
int arm64_encoder_4c(void* input, void** vars, paramcoding_t* vals) {
	/*AS:	10  => BIN_VAL_2()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_2_0000(found, input);
	return found;
}
int arm64_encoder_4d(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	00010  => BIN_VAL_2()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_2_0000(found, input);
	return found;
}
int arm64_encoder_4e(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	00010  => BIN_VAL_2()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_2_0000(found, input);
	return found;
}
int arm64_encoder_4f(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	00010  => BIN_VAL_2()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_2_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_30_0000
int arm64_encoder_50(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	11110  => BIN_VAL_30()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_30_0000(found, input);
	return found;
}
int arm64_encoder_51(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	11110  => BIN_VAL_30()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_30_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_3_0000
int arm64_encoder_52(void* input, void** vars, paramcoding_t* vals) {
	/*EXTx:	011  => BIN_VAL_3()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_3_0000(found, input);
	return found;
}
int arm64_encoder_53(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	00011  => BIN_VAL_3()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_3_0000(found, input);
	return found;
}
int arm64_encoder_54(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	00011  => BIN_VAL_3()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_3_0000(found, input);
	return found;
}
int arm64_encoder_55(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	00011  => BIN_VAL_3()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_3_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_4_0000
int arm64_encoder_56(void* input, void** vars, paramcoding_t* vals) {
	/*EXTnx:	100  => BIN_VAL_4()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_4_0000(found, input);
	return found;
}
int arm64_encoder_57(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	00100  => BIN_VAL_4()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_4_0000(found, input);
	return found;
}
int arm64_encoder_58(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	00100  => BIN_VAL_4()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_4_0000(found, input);
	return found;
}
int arm64_encoder_59(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	00100  => BIN_VAL_4()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_4_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_5_0000
int arm64_encoder_5a(void* input, void** vars, paramcoding_t* vals) {
	/*EXTnx:	101  => BIN_VAL_5()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_5_0000(found, input);
	return found;
}
int arm64_encoder_5b(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	00101  => BIN_VAL_5()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_5_0000(found, input);
	return found;
}
int arm64_encoder_5c(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	00101  => BIN_VAL_5()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_5_0000(found, input);
	return found;
}
int arm64_encoder_5d(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	00101  => BIN_VAL_5()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_5_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_6_0000
int arm64_encoder_5e(void* input, void** vars, paramcoding_t* vals) {
	/*EXTnx:	110  => BIN_VAL_6()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_6_0000(found, input);
	return found;
}
int arm64_encoder_5f(void* input, void** vars, paramcoding_t* vals) {
	/*EXTw:	110  => BIN_VAL_6()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_6_0000(found, input);
	return found;
}
int arm64_encoder_60(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	00110  => BIN_VAL_6()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_6_0000(found, input);
	return found;
}
int arm64_encoder_61(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	00110  => BIN_VAL_6()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_6_0000(found, input);
	return found;
}
int arm64_encoder_62(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	00110  => BIN_VAL_6()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_6_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_7_0000
int arm64_encoder_63(void* input, void** vars, paramcoding_t* vals) {
	/*EXTx:	111  => BIN_VAL_7()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_7_0000(found, input);
	return found;
}
int arm64_encoder_64(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	00111  => BIN_VAL_7()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_7_0000(found, input);
	return found;
}
int arm64_encoder_65(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	00111  => BIN_VAL_7()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_7_0000(found, input);
	return found;
}
int arm64_encoder_66(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	00111  => BIN_VAL_7()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_7_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_8_0000
int arm64_encoder_67(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	01000  => BIN_VAL_8()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_8_0000(found, input);
	return found;
}
int arm64_encoder_68(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	01000  => BIN_VAL_8()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_8_0000(found, input);
	return found;
}
int arm64_encoder_69(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	01000  => BIN_VAL_8()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_8_0000(found, input);
	return found;
}
#endif
#ifdef BIN_VAL_9_0000
int arm64_encoder_6a(void* input, void** vars, paramcoding_t* vals) {
	/*RNn2l:	01001  => BIN_VAL_9()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_9_0000(found, input);
	return found;
}
int arm64_encoder_6b(void* input, void** vars, paramcoding_t* vals) {
	/*RTnl:	01001  => BIN_VAL_9()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_9_0000(found, input);
	return found;
}
int arm64_encoder_6c(void* input, void** vars, paramcoding_t* vals) {
	/*RMns:	01001  => BIN_VAL_9()*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	BIN_VAL_9_0000(found, input);
	return found;
}
#endif
#ifdef INSN_OPCODE_0a00
int arm64_encoder_6d(void* input, void** vars, paramcoding_t* vals) {
	/*template:	11010110101111110000001111100000  => INSN_OPCODE(I_DRPS ISET_ARM64 FM_HW A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_0a00(found, input, I_DRPS, ISET_ARM64, FM_HW, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	return found;
}
int arm64_encoder_6e(void* input, void** vars, paramcoding_t* vals) {
	/*template:	11010110100111110000001111100000  => INSN_OPCODE(I_ERET ISET_ARM64 FM_HW A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_0a00(found, input, I_ERET, ISET_ARM64, FM_HW, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	return found;
}
int arm64_encoder_6f(void* input, void** vars, paramcoding_t* vals) {
	/*template:	11010101000000110011111111011111  => INSN_OPCODE(I_ISB ISET_ARM64 FM_SYNC A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_0a00(found, input, I_ISB, ISET_ARM64, FM_SYNC, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	return found;
}
int arm64_encoder_70(void* input, void** vars, paramcoding_t* vals) {
	/*template:	11010110010111110000001111000000  => INSN_OPCODE(I_RET ISET_ARM64 FM_RET A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vals;
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_0a00(found, input, I_RET, ISET_ARM64, FM_RET, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	return found;
}
#endif
#ifdef INSN_OPCODE_1a00
int arm64_encoder_71(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_727 = NULL;
	/*template:	11010100000 IMM16 00001  => INSN_OPCODE(I_SVC ISET_ARM64 FM_OS A_NA S_SCALAR T_UNDEF T_UNDEF DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_727, I_SVC, ISET_ARM64, FM_OS, A_NA, S_SCALAR, T_UNDEF, T_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_IMMEDIATE_0201(found, mcr_727, DATASZ_16b, READ, vals[BDFVar__IMM16 - BDFVar__VARNUMBER]);}
	}
	return found;
}
int arm64_encoder_72(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7b1 = NULL,*mcr_ffffff9a = NULL;
	/*template:	000101 IMM26  => INSN_OPCODE(I_B ISET_ARM64 FM_JUMP A_JUMP S_SCALAR T_UNDEF T_SINT DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_7b1, I_B, ISET_ARM64, FM_JUMP, A_JUMP, S_SCALAR, T_UNDEF, T_SINT, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_POINTER_1200(found, mcr_7b1, mcr_ffffff9a, DATASZ_28b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {SIGNED_LEFT_SHIFT_0201(found, mcr_ffffff9a, DATASZ_UNDEF, TWO, vals[BDFVar__IMM26 - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
int arm64_encoder_73(void* input, void** vars, paramcoding_t* vals) {
	void *mcr_7b2 = NULL,*mcr_ffffffbd = NULL;
	/*template:	100101 IMM26  => INSN_OPCODE(I_BL ISET_ARM64 FM_CALL A_CALL S_SCALAR T_UNDEF T_SINT DATASZ_UNDEF DATASZ_UNDEF DATASZ_UNDEF )*/
	(void)vars;
	int found = TRUE;
	INSN_OPCODE_1a00(found, input, mcr_7b2, I_BL, ISET_ARM64, FM_CALL, A_CALL, S_SCALAR, T_UNDEF, T_SINT, DATASZ_UNDEF, DATASZ_UNDEF, DATASZ_UNDEF);
	if (found == TRUE) {
		if (found == TRUE) {OPRN_POINTER_1200(found, mcr_7b2, mcr_ffffffbd, DATASZ_28b, READ);}
	if (found == TRUE) {
		if (found == TRUE) {LEFT_SHIFT_0201(found, mcr_ffffffbd, DATASZ_UNDEF, TWO, vals[BDFVar__IMM26 - BDFVar__VARNUMBER]);}
	}
	}
	return found;
}
#endif
